added bitcoind client & syncing
botanix-labs/Macbeth pull request #105
Opened 2024-02-26 21:41 UTC by BatiGencho

This MR changes the mempool impl to bitcoind introducing a new client and integration for syncing state. There are also clippy fixes and other rusty improvements.

Tickets:

- https://github.com/botanix-labs/botanix/issues/342
- https://github.com/botanix-labs/botanix/issues/343

2024-03-01 13:58 UTC, arminsabouri reviewed
I just had one open question. Awesome work!

2024-03-01 13:58 UTC, arminsabouri commented on crates/consensus/authority/src/block_builder.rs
> +        match self.bitcoind_client.is_synced().await {
This code looks correct but im not sure whether it belong here or in the main function. i.e is there any point to starting reth until the bitcoind client is sync'd? Maybe we should busy loop until this is the case in main. I'll leave this as a open question. Lmk what you think

2024-03-01 14:04 UTC, BatiGencho commented on crates/consensus/authority/src/block_builder.rs
> +        match self.bitcoind_client.is_synced().await {
I though of it too, actually wanted to leave a note. It definitely makes sense to await the sync in the start (poa_builder.rs) - I will move the code there, not an issue. Thanks for pointing this out to me.

2024-03-01 14:06 UTC, arminsabouri commented on crates/consensus/authority/src/block_builder.rs
> +        match self.bitcoind_client.is_synced().await {
Great! after that happy to get this merged

2024-03-01 17:41 UTC, scottmillner commented on crates/consensus/authority/src/block_builder.rs
> +        match self.bitcoind_client.is_synced().await {
awesome sauce! looks great! will ✅ once sync check is in main function
The Mighty Mutex strikes again!!

2024-03-04 11:08 UTC, BatiGencho commented
@0xBEEFCAF3 I have addressed your request. Do you mind going over it again.

2024-03-04 13:50 UTC, arminsabouri requested changes
Everything looks good. Just want to make sure we don't expose any real credentials

2024-03-04 13:50 UTC, arminsabouri commented on Makefile
> +	--bitcoind.password "mempool" \
These are the actual creds for the signet rpc right? Can we read these from env var?

2024-03-04 13:50 UTC, arminsabouri commented on crates/btc-wallet/src/bitcoind.rs
> +    password: Option<String>,
Do these have to be optional? Seems like they are required via the expect() below

2024-03-04 13:50 UTC, arminsabouri commented on crates/node-core/src/args/bitcoind_args.rs
> +    pub username: Option<String>,
Same thing here. Do the creds have to be optional?

2024-03-04 17:26 UTC, BatiGencho commented on crates/node-core/src/args/bitcoind_args.rs
> +    pub username: Option<String>,
I wasnt sure if bitcoind always needs creds, but that seems to be the case. I have removed the Options now.

2024-03-04 17:26 UTC, BatiGencho commented on crates/btc-wallet/src/bitcoind.rs
> +    password: Option<String>,
I wasnt sure if bitcoind always needs creds, but that seems to be the case. I have removed the Options now.

2024-03-04 17:27 UTC, BatiGencho commented on Makefile
> +	--bitcoind.password "mempool" \
They were, I removed them. Was using them for testing. The vals are now being read from .env file.

2024-03-04 19:48 UTC, arminsabouri approved these changes

2024-03-04 19:56 UTC, scottmillner approved these changes

2024-03-04 20:03 UTC, merged