Utxomerkle
botanix-labs/Macbeth pull request #122
Opened 2024-03-11 07:56 UTC by ozymandias-rex

This PR:

- adds an endpoint to retrieve all the utxos
- updates the Merkle Tree stored in the db on every pegin
- adds a remove_txo endpoint
closes #https://github.com/botanix-labs/botanix/issues/294

2024-03-13 19:44 UTC, scottmillner commented on bin/btc-server/src/merkle.rs
> +
i see  `construct_merkle_tree` and `construct_merkle_tree_from_utxos` aren't be used...do we plan to use these at some point?

one creates a tree of Utxos while the other creates a tree of hashed Utxos...why do we need both?

2024-03-13 19:51 UTC, scottmillner commented
@ozymandias-rex awesome sauce!  just had a question around two helper methods and left a comment

2024-03-14 01:21 UTC, ozymandias-rex commented on bin/btc-server/src/merkle.rs
> +
nice catch ! removed the unused ones

2024-03-14 01:47 UTC, scottmillner approved these changes

2024-03-14 08:20 UTC, ozymandias-rex commented
Notes 

- [ ] We probably want a type alias on the merkle tree.

2024-03-14 13:03 UTC, arminsabouri requested changes
This looks great! Just a few things around the database changes

2024-03-14 13:03 UTC, arminsabouri commented on bin/btc-server/src/database.rs
> +    merkle_trees: sled::Tree,
Nit: maybe a better name for this would be `utxo_merkel_tree`. As there should only be one tree

2024-03-14 13:03 UTC, arminsabouri commented on bin/btc-server/src/database.rs
> +        let txid_bytes = bitcoin::consensus::encode::serialize(txid);
Im not sure if we should index the merkel tree by a particular txid. Since its repersenting all UTXOs (txid, vout pairs) that are currently spendable. Might make sense to construct this new model similar to how  `PUBKEY_PACKAGE` is constructed.

2024-03-14 13:03 UTC, arminsabouri commented on bin/btc-server/src/merkle.rs
> +// pub fn construct_merkle_tree(utxos: &[Utxo]) -> MerkleTree<MerkleSha256> {
Can we remove this commented out part?

2024-03-14 13:03 UTC, arminsabouri commented on bin/btc-server/src/database.rs
> +        let txid_bytes = bitcoin::consensus::encode::serialize(txid);
There should ideally be an gRPC endpoint to get "the" UTXO merkel root. Not for a particular txid.
This root repersents all the UTXO that are spendable. The key here is that federation members have majority consensus on this [UTXO set].

2024-03-14 21:04 UTC, BatiGencho approved these changes

2024-03-14 21:04 UTC, BatiGencho commented
Great job!

2024-03-18 14:11 UTC, arminsabouri commented
@0xBEEFCAF3 To re-review and @ozymandias-rex to rebase

2024-03-18 15:27 UTC, arminsabouri approved these changes
Looks good!

2024-03-19 11:34 UTC, merged

2024-03-19 12:24 UTC, arminsabouri commented
@ozymandias-rex not a big deal rn. But in the future can you rebase and merge the changes instead of creating the merge commit. And these could probably all be squshed into one. Makes rebasing easier and commits become atomic.

2024-03-21 19:31 UTC, ozymandias-rex commented
Apologies @0xBEEFCAF3  will rebase and merge next time