Implement UTXO selection
botanix-labs/Macbeth pull request #149
Opened 2024-03-28 11:56 UTC by stevenroose

Based on https://github.com/botanix-labs/Macbeth/pull/146.

2024-04-08 13:36 UTC, arminsabouri commented on bin/btc-server/src/database.rs
> +        self.db.insert(KEY_UTXO_MERKLE_ROOT, root.to_byte_array().to_vec())?;
Do we need to do a flush here?

2024-04-09 17:02 UTC, stevenroose commented on bin/btc-server/src/database.rs
> +        self.db.insert(KEY_UTXO_MERKLE_ROOT, root.to_byte_array().to_vec())?;
We never flush in the db impls, the caller flushes.

2024-04-15 15:38 UTC, stevenroose commented
Rebased etc. Still pending on the utxo_merkle_root being available inside the eth code. That's the only todo, indicated as `todo!()` :)

2024-04-15 18:33 UTC, arminsabouri commented
@stevenroose This pr adds them
https://github.com/botanix-labs/Macbeth/pull/163
Will rebase and merge then update this thread

2024-05-08 19:56 UTC, stevenroose commented
Definitely review carefully!

2024-05-13 12:02 UTC, arminsabouri commented on bin/btc-server/src/main.rs
> +            Ok(TxIndex::new(100, vec![], BlockHash::all_zeros()))
Can we define 100 in a const or config somewhere?

2024-05-13 12:02 UTC, arminsabouri commented on bin/btc-server/src/txindex.rs
> +}
Can we remove this test?

2024-05-13 12:02 UTC, arminsabouri commented on bin/btc-server/src/txindex.rs
> +    /// We take the database closure to reduce coupling with database mobule.
module typo

2024-05-13 12:02 UTC, arminsabouri commented on bin/btc-server/src/txindex.rs
> +            txs: HashMap::with_capacity(txs.len()),
Won't the list of txs grow?

2024-05-13 12:02 UTC, arminsabouri commented on bin/btc-server/client/src/btc_server.rs
> +    /// The merkle root of our wallet's UTXO.
Nit: "UTXO set"

2024-05-13 12:02 UTC, arminsabouri commented on crates/consensus/authority/src/block_fetcher.rs
> +                                        utxo_merkle_root: todo!(),
Should be pretty easy to get these. I'm more familiar with this part of the code. I can help

2024-05-13 12:02 UTC, arminsabouri commented on crates/consensus/authority/src/utils.rs
> +        utxo_merkle_root: todo!(),
Leaving a comment on these todo's so we dont forget

2024-05-13 12:02 UTC, arminsabouri commented on bin/btc-server/src/main.rs
> +const FINALIZED_HEIGHT: u32 = 6; //TODO(stevenroose) change this with config var
Should this be config? Or hardcoded and changed with new software releases. im thinking if different federation members have different txindexes the utxo selection will be underministic?

2024-05-13 12:02 UTC, arminsabouri commented on bin/btc-server/src/cordinator.rs
> -        self.db.add_remove_utxos(selected_inputs.into_iter(), change_outputs.into_iter())?;
For my own understanding. Are utxos now removed / added during txIndex sync? Once they pass the confirmation window?

2024-05-13 12:28 UTC, stevenroose commented on bin/btc-server/src/main.rs
> +            Ok(TxIndex::new(100, vec![], BlockHash::all_zeros()))
That's done in a later commit, sorry.

2024-05-13 12:28 UTC, stevenroose commented on bin/btc-server/src/main.rs
> +            Ok(TxIndex::new(100, vec![], BlockHash::all_zeros()))
And set to 6, FWIW

2024-05-13 12:28 UTC, stevenroose commented on bin/btc-server/src/txindex.rs
> +}
Yeah sure, I did that because I planned to do some better test cases.

2024-05-13 12:30 UTC, stevenroose commented on bin/btc-server/src/txindex.rs
> +            txs: HashMap::with_capacity(txs.len()),
It does, but capacity is just the initial allocation. It's just to add the initial batch, so we don't have to potentially allocate a bunch of times each time we add something.

2024-05-13 12:32 UTC, stevenroose commented on crates/consensus/authority/src/block_fetcher.rs
> +                                        utxo_merkle_root: todo!(),
I added them in future commits, this was mostly just to separate the concerns into different commits. I recognize that's probably not ideal. I could push the protos commit to the back so that I can add the fields right away maybe.

2024-05-13 12:32 UTC, stevenroose commented on crates/consensus/authority/src/utils.rs
> +        utxo_merkle_root: todo!(),
see [previous comment](https://github.com/botanix-labs/Macbeth/pull/149#discussion_r1598396569)

2024-05-13 12:33 UTC, stevenroose commented on bin/btc-server/src/main.rs
> +const FINALIZED_HEIGHT: u32 = 6; //TODO(stevenroose) change this with config var
I think probably be part of some genesis spec/config somewhere. I don't really know where that would go/come from. Suggestion?

2024-05-13 12:34 UTC, stevenroose commented on bin/btc-server/src/cordinator.rs
> -        self.db.add_remove_utxos(selected_inputs.into_iter(), change_outputs.into_iter())?;
Yeah, just not here. They are dropped once they are "finalized", ie when they pass the conf window indeed.

2024-05-13 17:31 UTC, arminsabouri commented on bin/btc-server/src/main.rs
> +const FINALIZED_HEIGHT: u32 = 6; //TODO(stevenroose) change this with config var
Yeah this should be some extension of the `ChainSpec` struct

2024-05-13 17:31 UTC, arminsabouri commented on crates/consensus/authority/src/block_fetcher.rs
> +                                        utxo_merkle_root: todo!(),
All good!

2024-05-13 17:32 UTC, arminsabouri commented
You may need to run `make fmt`

2024-05-14 13:25 UTC, PhoenixCodeCraft commented
Wanted to add the issue on the coinbase transaction support here as it belongs in the UTXO selection.
https://github.com/botanix-labs/botanix/issues/390

2024-05-15 09:08 UTC, BatiGencho submitted a review, later dismissed
It looks code-wise good to me, I believe I also understand the mechanism behind it. What about integration tests ? Are there any to be added ?

2024-05-15 09:08 UTC, BatiGencho commented
@stevenroose I believe you need to rebase it and run `make fmt`

2024-05-23 12:39 UTC, BatiGencho submitted a review, later dismissed

2024-05-28 13:47 UTC, BatiGencho submitted a review, later dismissed

2024-05-29 06:49 UTC, BatiGencho submitted a review, later dismissed

2024-06-11 14:04 UTC, arminsabouri commented
Getting this error when making the tx as the coordinator
```
2024-06-11T13:52:29.839953Z ERROR Failed to make pegout tx e=Call(Status { code: Internal, message: "internal error: Failed to make tx: txindex sync: bitcoind RPC error: JSON error: invalid type: sequence, expected a string", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 11 Jun 2024 13:52:29 GMT", "content-length": "0"} }, source: None })
```

2024-06-11 15:32 UTC, arminsabouri commented
Heads up @stevenroose  Lint failing

2024-06-11 15:51 UTC, arminsabouri requested changes
tNACK
I keep running into 
```
2024-06-11T13:52:29.839953Z ERROR Failed to make pegout tx e=Call(Status { code: Internal, message: "internal error: Failed to make tx: txindex sync: bitcoind RPC error: JSON error: invalid type: sequence, expected a string", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 11 Jun 2024 13:52:29 GMT", "content-length": "0"} }, source: None })
```

I suspect this is coming from this line https://github.com/botanix-labs/Macbeth/blob/pegout-conflict/bin/btc-server/src/txindex.rs#L277

but im unclear what field bitcoin is complaining about specifically

2024-06-18 17:51 UTC, arminsabouri reviewed
Over all this is looking good. Starting review but I have some initial questions

2024-06-18 17:51 UTC, arminsabouri commented on bin/btc-server/src/main.rs
> +        if let Some(latest) = db.get_txindex_finalized_block()? {
in what case would this be None?

2024-06-18 17:51 UTC, arminsabouri commented on bin/btc-server/src/signer.rs
> +        let tx_timestamp = SystemTime::now(); // We're signing it for the first time now.
Im not sure how this timestamp is used but at this stage in signing the signers have signed they are just finalizing the signing round. I.e ensuring the witness provided by the coordinator is correct.

2024-06-19 14:11 UTC, stevenroose commented on bin/btc-server/src/main.rs
> +        if let Some(latest) = db.get_txindex_finalized_block()? {
First startup. This is like the "is this our first run or not" clause.

2024-06-19 14:14 UTC, stevenroose commented on bin/btc-server/src/signer.rs
> +        let tx_timestamp = SystemTime::now(); // We're signing it for the first time now.
The timestamp isn't used for now. I think it will be overwritten by block height in any case. I could actually remove it now, but let's see, CI might pass :)

2024-06-23 13:28 UTC, arminsabouri commented
tACK [5403915](https://github.com/botanix-labs/Macbeth/pull/149/commits/5403915469d15938d437c4b06b4a91654216f4df)

Had to fix a couple things and disable the IBD check in txindex but int., functional and unit tests are passing for me

2024-06-23 14:42 UTC, arminsabouri commented
Not sure why its saying e2e is failing they are all passing on CI
https://github.com/botanix-labs/Macbeth/actions/runs/9633849175/job/26568736468?pr=149#step:9:29914

2024-06-23 22:38 UTC, arminsabouri approved these changes
Ack

2024-06-23 22:39 UTC, merged