increased dynamic test suite
botanix-labs/Macbeth pull request #153
Opened 2024-04-04 11:23 UTC by BatiGencho

2024-04-05 12:10 UTC, arminsabouri requested changes
Great work. Just noticed a few things left in that could get deleted

2024-04-05 12:10 UTC, arminsabouri commented on Makefile
> -	cargo run --bin btc-server -- --btc-network "${BITCOIND_NETWORK}" --identifier 1 --address 0.0.0.0:8081 --db "./db2" --min-signers 2 --max-signers 2 --toml ./config.toml  --fee-rate-diff-percentage
Why change this?

2024-04-05 12:10 UTC, arminsabouri commented on bin/test-suite/Cargo.toml
> +reth-ecies.workspace = true
do we need ecies as a dependency?

2024-04-05 12:10 UTC, arminsabouri commented on bin/test-suite/src/mint_contract_abi.rs
> +            "/home/evgeni/Documents/BOTANIX/Macbeth/bin/test-suite/mint_contract_abi.json",
Lets change this to `../mint_contract_abi.json`

2024-04-05 12:10 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/poa_node.rs
> +        let botanix_genesis_filepath = Path::new("./").join("botanix_tesnet.json");
Typo
```suggestion
        let botanix_genesis_filepath = Path::new("./").join("botanix_testnet.json");
```

2024-04-05 12:10 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_signing.rs
> +    */
Any reason to comment this out?

2024-04-05 12:10 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_signing.rs
> +    */
Samething here

2024-04-05 12:10 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_signing.rs
> +    */
I think this is the most important part of this test

2024-04-05 12:10 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/pbft/mod.rs
> +
Can we delete this?

2024-04-05 12:10 UTC, arminsabouri commented on output.txt
> +cd ./bin/test-suite && \
Could delete

2024-04-05 12:13 UTC, BatiGencho commented on bin/test-suite/Cargo.toml
> +reth-ecies.workspace = true
yes, this is needed as we need to derive the peerid from the pub key which reth needs when we are connecting the peers. There is a method inside of that crate that does this for us.

2024-04-05 12:14 UTC, BatiGencho commented on bin/test-suite/src/mint_contract_abi.rs
> +            "/home/evgeni/Documents/BOTANIX/Macbeth/bin/test-suite/mint_contract_abi.json",
done

2024-04-05 12:14 UTC, BatiGencho commented on output.txt
> +cd ./bin/test-suite && \
done

2024-04-05 12:15 UTC, BatiGencho commented on bin/test-suite/src/suite/consensus/frost/poa_node.rs
> +        let botanix_genesis_filepath = Path::new("./").join("botanix_tesnet.json");
done

2024-04-05 12:19 UTC, BatiGencho commented on bin/test-suite/src/suite/consensus/pbft/mod.rs
> +
done, i added a .gitkeep file to remind us that pbft is to be added soon there

2024-04-05 12:29 UTC, BatiGencho commented on bin/test-suite/src/suite/consensus/frost/test_signing.rs
> +    */
The signing part fails in the last step with:

 Failed to broadcast tx: JSON-RPC error: RPC error response: RpcError { code: -25, message: "bad-txns-inputs-missingorspent", data: None }
[2024-04-05T12:21:18Z ERROR btc_server::server] INTERNAL ERROR: Failed to finalize signing: Failed to broadcast tx: JSON-RPC error: RPC error response: RpcError { code: -25, message: "bad-txns-inputs-missingorspent", data: None }

2024-04-05 12:29 UTC, BatiGencho commented on bin/test-suite/src/suite/consensus/frost/test_signing.rs
> +    */
same as above ,need to investigate a bit further

2024-04-05 12:40 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_signing.rs
> +    */
This ussually means the signers signed for utxos that don't exist. I can help with this

2024-04-05 12:42 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_signing.rs
> +    }
We should have a hardcoded vec of 2. With two eth addresses here. As there should only be 2 inputs being spent here

2024-04-05 12:42 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_signing.rs
> +    let mut btc_addresses: Vec<Address> = vec![];
Same thing here.

2024-04-05 15:23 UTC, stevenroose commented
Just a general comment towards the future, when doing a lot of formatting changes, it would be nice if they could be separated from actual code changes in a separate commit or so.

2024-04-09 13:16 UTC, arminsabouri reviewed
Looks great! just a few more nits

2024-04-09 13:16 UTC, arminsabouri commented on bin/btc-server/src/dkg.rs
> +                    // ?
Did this get resolved?

2024-04-09 13:16 UTC, arminsabouri commented on bin/btc-server/src/main.rs
> +        let btcd_url = format!("{}:{}", host, port);
Nit: btcd is a alternative bitcoin implementation. can we rename to `bitcoind_url`

2024-04-09 13:16 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/btc_server.rs
> +) -> Vec<SpawnedBtcServer> {
Should # of servers come from a function param. I could see some tests needing a specific set up of nodes. Not a request for a change we could update in the future if need be.

2024-04-09 13:16 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/poa_node.rs
> +        let secp: secp256k1::Secp256k1<secp256k1::All> = secp256k1::Secp256k1::new();
Nit: could move this out of the loop

2024-04-09 13:16 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_signing.rs
> +    assert!(err.message().contains("bad-txns-inputs-missingorspent"));
```suggestion
    // Test should fail here after `psbt.finalize_mut()`. These inputs don't actually exist on the regtest chain so there is nothing to be spent. In the future we can generate some addresses send funds and use those outpoints for this test.
    assert!(err.message().contains("bad-txns-inputs-missingorspent"));
```

2024-04-09 16:20 UTC, stevenroose commented on bin/test-suite/src/suite/consensus/frost/poa_node.rs
> +        let secp: secp256k1::Secp256k1<secp256k1::All> = secp256k1::Secp256k1::new();
nit: and the type annotation is not needed ;)

2024-04-09 16:24 UTC, BatiGencho commented on bin/btc-server/src/dkg.rs
> +                    // ?
yep, all good here.

2024-04-09 16:24 UTC, BatiGencho commented on bin/btc-server/src/main.rs
> +        let btcd_url = format!("{}:{}", host, port);
changed,

2024-04-09 16:25 UTC, BatiGencho commented on bin/test-suite/src/suite/consensus/frost/btc_server.rs
> +) -> Vec<SpawnedBtcServer> {
the # servers is the max number of signers. I have removed the instance param.

2024-04-09 16:25 UTC, BatiGencho commented on bin/test-suite/src/suite/consensus/frost/poa_node.rs
> +        let secp: secp256k1::Secp256k1<secp256k1::All> = secp256k1::Secp256k1::new();
done

2024-04-09 16:25 UTC, BatiGencho commented on bin/test-suite/src/suite/consensus/frost/test_signing.rs
> +    assert!(err.message().contains("bad-txns-inputs-missingorspent"));
added

2024-04-09 16:58 UTC, stevenroose commented
I tried to run it, but didn't really work :/ Various errors. Also the hard-coded paths in .env is not ideal.

```
2024-04-09T16:57:41.030045Z ERROR Test suite panicked PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: Bitcoind client could not achieve synced status within 60secs. Exiting...
```

Does the suite check if all the configs in `.env` make sense (like if the dirs exist, if the bitcoind is reachable etc) before running the daemons?

2024-04-11 14:10 UTC, arminsabouri approved these changes

2024-04-11 20:23 UTC, merged