executor: Fix various issues in Mint contract validation
botanix-labs/Macbeth pull request #16
Opened 2023-10-11 23:53 UTC by stevenroose

Closes https://github.com/botanix-labs/botanix/issues/154, https://github.com/botanix-labs/botanix/issues/155.

Depends on https://github.com/botanix-labs/botanix/pull/166.

Triggered by reading https://github.com/botanix-labs/Macbeth/pull/12, I found some bugs in the validation code.

I tried to break it into various commits, but it was so many details that I'm going to leave comments in the code instead. That way we can also have discussions in these comment threads.

This code is so critical for this system, it should really be reviewed carefully.

2023-10-11 23:54 UTC, stevenroose commented on crates/interfaces/src/executor.rs
> +    MintContractViolation,
Added an error variant for this because failing the mint contract check is a consensus violation and should fail block validation.

2023-10-11 23:55 UTC, stevenroose commented on crates/revm/src/executor.rs
> +fn botanix_mint_contract_checks(result: &ExecutionResult) -> Result<(), BlockExecutionError> {
Bundling all our stuff into a single method (or file even better), makes it a lot easier lateron to merge in upstream changes because it minimizes the actual diff inside the upstream code.

2023-10-11 23:55 UTC, stevenroose commented on crates/revm/src/executor.rs
> +        if log.topics[0] == *MINT_TOPIC {
Made this an explicit check for the first topic. Can someone confirm that all logs have at least one topic? Because if that is not the case, this code could potentially panic.

2023-10-11 23:57 UTC, stevenroose commented on crates/revm/src/executor.rs
> +                    return Err(BlockValidationError::MintContractViolation.into());
This error case was previously just a `continue`, which would mean that the error would simply be ignored. Now, these errors are a bit special, they shouldn't really happen and they would likely mean that our own interpretation of the log structure is wrong. But ignoring is definitely not a good idea. It's hard to evaluate which of these errors can be triggered by users.

2023-10-11 23:58 UTC, stevenroose commented on crates/revm/src/executor.rs
> +                            }
Without this block the the above `let ret = block_source_clone.get_block_header(block_hash).await.ok();`, which turns the channel value into an `Option`, the block source failing would cause that spinloop to go on for 100 seconds and then timing out instead of erroring out early.

2023-10-11 23:58 UTC, stevenroose commented on crates/revm/src/executor.rs
> +                    // callsite
This spinloop thing should really really not be here. I think you do it because for the first testnet you don't want to add any data to the botanix headers, do I remember that correctly?

2023-10-11 23:59 UTC, stevenroose commented on crates/revm/src/executor.rs
> +                                if counter == 10_000 {
Is a 100 seconds not a lot of time?

2023-10-12 00:13 UTC, stevenroose commented on crates/revm/src/executor.rs
> +            if result.is_success() && transaction.to() == Some(*MINT_CONTRACT_ADDRESS) {
So two things here: (1) most obviously, we only do our checks if this tx is a call to our mint contract. Any other contract we don't care about. But (2) this code misinterpreted the concept of "tx success"; check also the changed line below in the Receipt struct.

The previous code would just change the receipt of the tx. This literally has no effect on state. That line below basically disregards all our checks and just makes the receipt show unsuccesful but that has absolutely no effect. Any user could just pegin any amount in the system without a valid proof 😅

What the success flag means is whether the solidity execution of the tx was succesful. If not, it means no state changes have happened. So basically if an error already occurred in Solidity, the state is reverted and we also don't have to do any further checks. (Tbh I would presume no logs would be produced either so that's probably not a problem.)

2023-10-12 00:14 UTC, stevenroose commented on crates/revm/src/executor.rs
> +                botanix_mint_contract_checks(&result)?;
This is maybe the most important change. The error return here. Before, mint check failure would just set the success flag in the receipt to false, but txs would still be accepted. To actually invalidate the tx, we need to somehow upstream indicate that a consensus rule was violated. That's what this error return does here.

2023-10-12 15:02 UTC, arminsabouri requested changes
There are some good points being made but largely this code conflicts with #13 
Let's merge #13 in first and revisit this.

2023-10-12 15:02 UTC, arminsabouri commented on crates/interfaces/src/executor.rs
> +    //TODO(stevenroose) this should be removed in later versions
What is expected from putting your username by a TODO? Are you signifying you made it or your going to solve it?

2023-10-12 15:02 UTC, arminsabouri commented on crates/interfaces/src/executor.rs
> +    //TODO(stevenroose) this should be removed in later versions
Regardless I think we need this variant independent of where we are retrieving block headers

2023-10-12 15:02 UTC, arminsabouri commented on crates/revm/src/executor.rs
> +                    // callsite
This was removed in #13

2023-10-12 15:02 UTC, arminsabouri commented on crates/revm/src/executor.rs
> +                                if counter == 10_000 {
Again removed in #13

2023-10-12 15:02 UTC, arminsabouri commented on crates/revm/src/executor.rs
> +                botanix_mint_contract_checks(&result)?;
These are two different things
If you return an Err from the executor the whole bundle of txs will be rejected. But still in the mempool.

If you set the tx receipt to false, other txs can me mined while this one is dropped from the mempool

2023-10-12 15:02 UTC, arminsabouri commented on crates/revm/src/executor.rs
> +            if result.is_success() && transaction.to() == Some(*MINT_CONTRACT_ADDRESS) {
>most obviously, we only do our checks if this tx is a call to our mint contract.

This check is in peginData.validate(). Do we need it again here?

2023-10-12 15:02 UTC, arminsabouri commented on crates/revm/src/executor.rs
> +                            }
This mechanism was removed in #13

2023-10-12 15:02 UTC, arminsabouri commented on crates/revm/src/executor.rs
> +            if result.is_success() && transaction.to() == Some(*MINT_CONTRACT_ADDRESS) {
>Any user could just pegin any amount in the system without a valid proof 😅

This isn't entirely true if the tx fails execution (receipt.success == false) it will not be mined.

2023-10-12 15:50 UTC, stevenroose commented on crates/revm/src/executor.rs
> +            if result.is_success() && transaction.to() == Some(*MINT_CONTRACT_ADDRESS) {
> > most obviously, we only do our checks if this tx is a call to our mint contract.
> 
> This check is in peginData.validate(). Do we need it again here?

I don't think this is true. peginData.validate has no context to make this check

2023-10-12 15:51 UTC, stevenroose commented on crates/revm/src/executor.rs
> +            if result.is_success() && transaction.to() == Some(*MINT_CONTRACT_ADDRESS) {
> > Any user could just pegin any amount in the system without a valid proof 😅
> 
> This isn't entirely true if the tx fails execution (receipt.success == false) it will not be mined.

How so? Failed txs in ethereum are mined, they don't have effect on state, but the gas is paid and they are part of the block. AFAIK

2023-10-12 15:52 UTC, stevenroose commented on crates/interfaces/src/executor.rs
> +    //TODO(stevenroose) this should be removed in later versions
> What is expected from putting your username by a TODO? Are you signifying you made it or your going to solve it?

Oh, I think it's a convention, this happens automatically if I type "todo". I think it serves mostly to indicate who made the todo so that if you have questions about it, you know who to talk with.

2023-10-12 15:52 UTC, stevenroose commented on crates/interfaces/src/executor.rs
> +    //TODO(stevenroose) this should be removed in later versions
> Regardless I think we need this variant independent of where we are retrieving block headers

Could you explain in what kind of scenario that would be?

2023-10-12 15:56 UTC, stevenroose commented on crates/revm/src/executor.rs
> +                botanix_mint_contract_checks(&result)?;
Hmm, I might not correctly understand the context here then. Does the mempool call the `.transact(tx, sender)` method of the multi `.execute_transactions(block)` method? Ok I checked and it seems the `.transact()` method is only called from within `.execute_transactions()` so my second commit might not be needed. I have to check better what context this code is run in. Because Ethereum for sure mines transactions that fail execution because they have to pay gas.

2023-10-12 16:33 UTC, scottmillner commented on crates/revm/src/executor.rs
> +        if log.topics[0] == *MINT_TOPIC {
that's correct, all logs have at least one topic
an anonymous event won't have a signature topic but still has at least one topic

2023-10-13 13:31 UTC, stevenroose commented on crates/revm/src/executor.rs
> +        if log.topics[0] == *MINT_TOPIC {
Anonymous events? I didn't know about those. How do they work?

2023-10-13 13:31 UTC, stevenroose commented on crates/revm/src/executor.rs
> +        if log.topics[0] == *MINT_TOPIC {
Thanks for checking, btw!

2023-10-13 13:59 UTC, scottmillner commented on crates/revm/src/executor.rs
> +        if log.topics[0] == *MINT_TOPIC {
np! 
anonymouse events are rarely used (ive never used one)
if you put the `anonymous` keyword after the event in the contract, the signature topic is omitted so a client can't search for it easily...not sure the benefit of that lol

2023-10-13 14:23 UTC, stevenroose commented on crates/revm/src/executor.rs
> +        if log.topics[0] == *MINT_TOPIC {
But then if you do `anonymous event NoArguments();`, won't that have 0 topics?

2023-10-16 13:53 UTC, scottmillner commented on crates/revm/src/executor.rs
> +        if log.topics[0] == *MINT_TOPIC {
good point! yeah best to revert this change

2023-10-16 18:24 UTC, stevenroose commented on crates/revm/src/executor.rs
> +        if log.topics[0] == *MINT_TOPIC {
changed

2023-10-16 18:25 UTC, stevenroose commented
Updated this with the changes you just merged, Armin.

2023-10-18 15:36 UTC, arminsabouri commented on crates/interfaces/src/executor.rs
> +    //TODO(stevenroose) this should be removed in later versions
When #18 gets merged this won't be an issue anymore.
Resolving

2023-10-18 15:37 UTC, stevenroose commented on crates/interfaces/src/executor.rs
> +    //TODO(stevenroose) this should be removed in later versions
I can rebase this after that.

2023-10-18 15:37 UTC, arminsabouri commented on crates/revm/src/executor.rs
> +                .expect("can't pegin without recent headers known")
I can update this code when after #18  gets merged

2023-10-18 15:40 UTC, arminsabouri approved these changes
Nice! I can rebase #18 after this gets merged.

2023-10-18 15:40 UTC, arminsabouri commented on crates/revm/src/executor.rs
> +        // Botanix mint contract validation
Nit: these checks cover both mint and withdrawals

2023-10-18 15:41 UTC, arminsabouri commented on crates/revm/src/executor.rs
> +        // Botanix mint contract validation
On second thought I don't think this Mr should make this change the whole file calls the genesis contract a "mint contract". So we'll refactor the names as somepoint

2023-10-18 17:08 UTC, merged