Scott/378 feature block subsidy is split between block producer and botanix
botanix-labs/Macbeth pull request #167
Opened 2024-04-12 19:00 UTC by scottmillner

currently using a placeholder address for botanix...will replace with actual once we have it

Overview of how fees work now:

1. Transaction fees are sent to the beneficiary address (revm sets coinbase address to beneficiary) during tx execution.
2. After block execution and during post state updates, block rewards are sent to the beneficiary.
3. Since the beneficiary is set to the burn address of 0x0..., all fees and rewards are burned
4. At this point, Botanix is deflationary: tx fees paid by senders have been burned.
5. `processor.execute` has been refactored to determine the total block fees as it executes txs (`best_transactions_from_payload` does this and I used this as reference)
6. During post state checks/updates, `apply_post_execution_state_change` has been refactored to accept the `total_block_fees`
7. The above method calls `post_block_balance_increments` which has been refactored to split `total_block_fees` between botanix and the block builder and update/commit their new balances.
8. At this point, Botanix is back to it's exact peg of 21million since the previously burned fees have been added to botanix and the block builder accounts.
9. `test_block_builder` has been refactored to assert that block fees are split correctly.
10. Have tested manually as well.

![Screenshot 2024-04-17 at 1 47 14 PM (3)](https://github.com/botanix-labs/Macbeth/assets/22253830/fb4578c6-1dc0-4673-8758-ff87816359c3)

2024-04-15 14:18 UTC, arminsabouri commented on crates/revm/src/state_change.rs
> +        let base_block_reward = calc::block_reward(base_block_reward, ommers.len());
is it possible to add `block_reward_split` as a trait ext instead of a utility?

2024-04-15 14:22 UTC, BatiGencho approved these changes

2024-04-15 14:45 UTC, arminsabouri requested changes
we should also set the beneficiary during block template construction to a unspendable address. Not sure what that would be in eth land? 0x0?

2024-04-15 21:30 UTC, scottmillner commented on crates/revm/src/state_change.rs
> +        let base_block_reward = calc::block_reward(base_block_reward, ommers.len());
not quite following...which trait would this be extending?

`state_change.rs` is just functions related to state change and aren't part of a struct or trait
and `calc.rs` which the state change methods use is the same: just a file of methods not related to a trait or struct

maybe i should move the method to `calc.rs`?

2024-04-15 21:39 UTC, scottmillner commented
> we should also set the beneficiary during block template construction to a unspendable address. Not sure what that would be in eth land? 0x0?

why wouldn't we want to set it to the block producer like we currently do in `build_header_template`?

```
// derive beneficary address being the producuing block federation member address
let beneficiary_pub_key = secp256k1::PublicKey::from_secret_key(secp, sk);
let beneficiary_address = public_key_to_address(beneficiary_pub_key);
```

are you saying the beneficiary would always be `0x0` and `block_reward_split` would be responsible for determining the beneficary?

2024-04-16 12:37 UTC, arminsabouri commented
> > we should also set the beneficiary during block template construction to a unspendable address. Not sure what that would be in eth land? 0x0?
> 
> why wouldn't we want to set it to the block producer like we currently do in `build_header_template`?
> 
> ```
> // derive beneficary address being the producuing block federation member address
> let beneficiary_pub_key = secp256k1::PublicKey::from_secret_key(secp, sk);
> let beneficiary_address = public_key_to_address(beneficiary_pub_key);
> ```
> 
> are you saying the beneficiary would always be `0x0` and `block_reward_split` would be responsible for determining the beneficary?

Yeah essentially. I think we either have the block fee reward either gets distributed via benefeciary (normal path). Or gets split via this incrementing balance logic. But you can't have both?

2024-04-16 14:12 UTC, scottmillner commented
> > > we should also set the beneficiary during block template construction to a unspendable address. Not sure what that would be in eth land? 0x0?
> > 
> > 
> > why wouldn't we want to set it to the block producer like we currently do in `build_header_template`?
> > ```
> > // derive beneficary address being the producuing block federation member address
> > let beneficiary_pub_key = secp256k1::PublicKey::from_secret_key(secp, sk);
> > let beneficiary_address = public_key_to_address(beneficiary_pub_key);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > are you saying the beneficiary would always be `0x0` and `block_reward_split` would be responsible for determining the beneficary?
> 
> Yeah essentially. I think we either have the block fee reward either gets distributed via benefeciary (normal path). Or gets split via this incrementing balance logic. But you can't have both?

2024-04-16 15:41 UTC, scottmillner commented
> > > > we should also set the beneficiary during block template construction to a unspendable address. Not sure what that would be in eth land? 0x0?
> > > 
> > > 
> > > why wouldn't we want to set it to the block producer like we currently do in `build_header_template`?
> > > ```
> > > // derive beneficary address being the producuing block federation member address
> > > let beneficiary_pub_key = secp256k1::PublicKey::from_secret_key(secp, sk);
> > > let beneficiary_address = public_key_to_address(beneficiary_pub_key);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > are you saying the beneficiary would always be `0x0` and `block_reward_split` would be responsible for determining the beneficary?
> > 
> > 
> > Yeah essentially. I think we either have the block fee reward either gets distributed via benefeciary (normal path). Or gets split via this incrementing balance logic. But you can't have both?

recap of offline discussion: beneficiary should be set to 0x0 so block reward (PoW 5eth + ommers reward) gets burned and incrementing balance logic handles all the rewards

2024-04-17 19:33 UTC, scottmillner commented
> we should also set the beneficiary during block template construction to a unspendable address. Not sure what that would be in eth land? 0x0?

done

2024-04-17 19:38 UTC, scottmillner commented on crates/primitives/src/transaction/mod.rs
>          // Compare the fee with max_priority_fee_per_gas (or gas price for non-EIP1559 transactions)
this change was made before but must've got lost in a rebase...it makes sure we don't burn the base fee but include it in the block fees

2024-04-17 19:57 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_block_builder.rs
> +                    assert_eq!(botanix_block_reward, total_block_reward / 5); // 20%
🔥 🔥 🔥 🔥 🔥 🔥 
nice

2024-04-17 19:57 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
> +        let block_builder_pub_key = secp256k1::PublicKey::from_secret_key(secp, sk);
nit: im hoping we can drop `secp` as there is a global context now available in the library.
Something like `secp256k1::PublicKey::from_secret_key_global(sk)` would make that transition easier

2024-04-17 19:57 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_block_builder.rs
> +                    // verfigy 80/20 block reward split is correct
Typo

```suggestion
                    // verify 80/20 block reward split is correct
```

2024-04-17 19:57 UTC, arminsabouri commented on crates/consensus/common/src/utils.rs
> +}
can we re-name this to `get_block_producer_address`. Only b/c in the multi signer context (PBFT) this is going to get confusing. And eventually we'll move this to the header ext as well

2024-04-17 22:38 UTC, scottmillner commented on crates/consensus/common/src/utils.rs
> +}
done

2024-04-17 22:38 UTC, scottmillner commented on bin/test-suite/src/suite/consensus/frost/test_block_builder.rs
> +                    // verfigy 80/20 block reward split is correct
done

2024-04-17 22:39 UTC, scottmillner commented on crates/consensus/authority/src/lib.rs
> +        let block_builder_pub_key = secp256k1::PublicKey::from_secret_key(secp, sk);
done

2024-04-18 12:54 UTC, arminsabouri commented on crates/primitives/src/constants/mod.rs
> +pub const BOTANIX_FEES_RECIPIENT: &str = "0x4e0f6e05C8ca4b3dc2B7b7Ad6249B149b1980394";
Just curious is this an address of one of the two fed members?

2024-04-18 12:55 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
> +        let (receipts, gas_used, total_block_fees) =
Whats the difference between gas_used and total_block_fees?

2024-04-18 13:52 UTC, scottmillner commented on crates/consensus/authority/src/lib.rs
> +        let (receipts, gas_used, total_block_fees) =
in this context, `gas_used` is the total gas needed for all the txs in the block

and `total_block_fees` = is the total fees paid for all the txs in the block

a `tx_fee` = `gas` * `gas_price`

`gas_price` = `base_fee` + `tip`

2024-04-18 13:55 UTC, scottmillner commented on crates/primitives/src/constants/mod.rs
> +pub const BOTANIX_FEES_RECIPIENT: &str = "0x4e0f6e05C8ca4b3dc2B7b7Ad6249B149b1980394";
it's an address i use for testing...more than happy to share it's private key or switch to another account

just needed something for testing and confirm fees were being distributed correctly

2024-04-18 19:28 UTC, arminsabouri commented on crates/consensus/common/src/utils.rs
> +        // assert!(validate_poa_block_beneficiary(&header, &authority_signers).is_ok());
Can we just remove this test?

2024-04-18 19:29 UTC, arminsabouri commented on crates/primitives/src/constants/mod.rs
> +pub const BOTANIX_FEES_RECIPIENT: &str = "0x4e0f6e05C8ca4b3dc2B7b7Ad6249B149b1980394";
Is it possible to one of the keys of the fed members?

2024-04-18 19:30 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
> +        let (receipts, gas_used, total_block_fees) =
Understood. Thanks

2024-04-18 22:29 UTC, scottmillner commented on crates/consensus/common/src/utils.rs
> +        // assert!(validate_poa_block_beneficiary(&header, &authority_signers).is_ok());
will do, was just leaving it for when we eventually set the beneficiary to block producer when we're not PoA and fully decentralized...but that's a wee bit off in the future lol

and done!

2024-04-18 22:48 UTC, scottmillner commented on crates/primitives/src/constants/mod.rs
> +pub const BOTANIX_FEES_RECIPIENT: &str = "0x4e0f6e05C8ca4b3dc2B7b7Ad6249B149b1980394";
yes sir, and done!

2024-04-19 15:23 UTC, arminsabouri approved these changes
Nice work!

2024-04-19 15:23 UTC, arminsabouri commented on crates/consensus/common/src/utils.rs
> +        assert!(result.is_ok());
Sorry I should have noticed this before 
can we have a test case for the opposite condition? Fails for anything that is not burn address. I know the code is really dead simple. but it would be good to have this fail if that code changes by accident

2024-04-19 15:58 UTC, scottmillner commented on crates/consensus/common/src/utils.rs
> +        assert!(result.is_ok());
done!

2024-04-19 16:38 UTC, merged