added cleanup tasks for stale entities
botanix-labs/Macbeth pull request #189
Opened 2024-05-16 12:15 UTC by BatiGencho

2024-05-16 13:35 UTC, arminsabouri reviewed
I had a general comment about block height vs timestamp

2024-05-16 13:35 UTC, arminsabouri commented on crates/consensus/authority/src/pbft.rs
> +const BLOCK_TIME_DURATION_SECS: u64 = 1 * 10;
10 seconds? I think we are using 60 second blocks right now.
In the near future this should all get defined in chainspec somewhere so we dont have block times flying around everywhere

2024-05-16 13:35 UTC, arminsabouri commented on crates/consensus/authority/src/pbft.rs
> +            >,
Do you need to define the whole type here? Shouldnt it be infered?

2024-05-16 13:35 UTC, arminsabouri commented on crates/consensus/authority/src/pbft.rs
> +                        if sealed_block.timestamp < unix_timestamp() - sleep_duration.as_secs() {
Have you considered using block height instead of timestamp?
i.e if block.height < best_height - 2 -> remove ?

2024-05-16 13:35 UTC, arminsabouri commented on crates/consensus/authority/src/signing.rs
> +const BLOCK_TIME_DURATION_SECS: u64 = 1 * 10;
Same comment as above?

2024-05-16 13:35 UTC, arminsabouri commented on crates/consensus/authority/src/pbft.rs
> +                        if sealed_block.timestamp < unix_timestamp() - sleep_duration.as_secs() {
In the forking logic branch i have added the client into this struct so getting the best block height should be easy

2024-05-22 14:33 UTC, scottmillner commented on crates/consensus/authority/src/pbft.rs
> +                        if sealed_block.timestamp < unix_timestamp() - sleep_duration.as_secs() {
i have a preference of height instead of timestamp as well...in general prefer not to use timestamps if we don't have to

2024-05-22 14:36 UTC, stevenroose requested changes
I looked at the code, but I have no idea what "stale txs", "stale blocks" and "sealed blocks" are..

2024-05-22 14:36 UTC, stevenroose commented on crates/consensus/authority/src/pbft.rs
> +            >,
Exactly, like above. If you prefer to be more explicit, please don't use 7 lines for a type indication..

2024-05-22 14:36 UTC, stevenroose commented on crates/consensus/authority/src/pbft.rs
> +                        let best_block_height = (best_block_height - 2).max(0);
can this go negative? if the type is unsigned here, this might panic and you should use `best_block_height.saturating_sub(2)` to get the same result.

2024-05-22 14:36 UTC, stevenroose commented on crates/consensus/authority/src/pbft.rs
> +                        let best_block_height = (best_block_height - 2).max(0);
And frankly block heights should be unsigned..

2024-05-28 12:44 UTC, arminsabouri commented on crates/consensus/authority/src/pbft.rs
> +                        sealed_block.timestamp >= unix_timestamp() - sleep_duration.as_secs()
Leaving my original comment here again. Can we use block heights here instead of timestamps?
i.e if best_block.height - sealed_block.height  > 2 -> clean up

2024-05-28 12:44 UTC, arminsabouri commented on crates/consensus/authority/src/pbft.rs
> +    impl ReceiptProviderIdExt for ClientMock {}
This is going to conflict with 
#191 that uses mockEth client defined in the reth utils

2024-05-29 05:12 UTC, stevenroose approved these changes

2024-05-29 12:31 UTC, arminsabouri approved these changes

2024-05-29 12:31 UTC, merged