added time-based test logic and pbft test cases mechanisms
botanix-labs/Macbeth pull request #190
Opened 2024-05-16 14:47 UTC by BatiGencho

- added time-based validity checks
- added the ability to await all btc servers before running tests
- added a pbft e2e test (currently commented out)
- added the ability to signal the exact moment when signing has finished via session ids
- added better output and display traits masking long hex blocks
- reworked the time logic to be based on secs than on minutes and thus be more precise
- increased grpc timeout, ping and healthcheck durations
- added 2 new btc server grpc endpoints
- fixes to test-suite
- e2e tests renaming
- fmt, cleanup

2024-05-21 18:10 UTC, arminsabouri commented on bin/btc-server/proto/btc_server.proto
> +    FINALIZED = 1;
Should we have failed? 
If we a signing session for a epoch that expired then a different coord picked it up the prev one should be "failed"

2024-05-21 18:10 UTC, arminsabouri commented on bin/btc-server/src/cordinator.rs
> +            }
we talked about this in person but just for the record.
We know if signing was successful by calling finalize() (from the miniscript crate). Finalize checks the agg sig against each input. But in order for finalize to work each signer and coord needs to save the final PSBT with the witness. Im not sure if they persist the final psbt or if they just check it in the finalize endpoint.

2024-05-21 18:10 UTC, arminsabouri commented on bin/btc-server/src/database.rs
> +        println!("Signing session ids {:?}", signing_session_ids);
just a TODO for an assertion here

2024-05-23 12:12 UTC, BatiGencho commented on bin/btc-server/src/cordinator.rs
> +            }
fixed

2024-05-23 12:12 UTC, BatiGencho commented on bin/btc-server/proto/btc_server.proto
> +    FINALIZED = 1;
added

2024-05-23 12:12 UTC, BatiGencho commented on bin/btc-server/src/database.rs
> +        println!("Signing session ids {:?}", signing_session_ids);
added

2024-05-28 14:18 UTC, arminsabouri commented
Blocked
- Armin: Coin Selection error: Insufficient funds: sat available of sat needed keeps coming quite often and breaks the test suite. Shows up in e2e FROST test.
- Evgeni: dkg not finalizing. 
- Evgeni: Cleaning up logs

2024-05-30 00:23 UTC, arminsabouri requested changes

2024-05-30 00:23 UTC, arminsabouri commented on bin/btc-server/src/database.rs
> +            info!("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
rm this

2024-05-30 00:23 UTC, arminsabouri commented on bin/btc-server/src/database.rs
> +            info!("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX {:?}", signing_session_id);
samething here

2024-05-30 00:23 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/common/events.rs
> +            info!(
Could remove this

2024-05-30 00:23 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/mod.rs
>          // dkg tests
uncomment tests

2024-05-30 00:23 UTC, arminsabouri commented on crates/consensus/authority/src/pbft.rs
> +        // }
Do we want to keep these?

2024-05-30 00:23 UTC, arminsabouri commented on crates/consensus/authority/src/pbft.rs
> +    async fn validate_block(&self, block: &SealedBlock) -> Result<bool, Error> {
Is this used? Any plans to use if not?

2024-05-30 10:54 UTC, BatiGencho commented on bin/btc-server/src/database.rs
> +            info!("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
done

2024-05-30 10:54 UTC, BatiGencho commented on bin/btc-server/src/database.rs
> +            info!("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX {:?}", signing_session_id);
done

2024-05-30 10:54 UTC, BatiGencho commented on crates/consensus/authority/src/pbft.rs
> +        // }
yes, I have reactivated the checks

2024-05-30 10:55 UTC, BatiGencho commented on crates/consensus/authority/src/pbft.rs
> +    async fn validate_block(&self, block: &SealedBlock) -> Result<bool, Error> {
it is being used, indeed

2024-05-30 12:37 UTC, arminsabouri commented on crates/consensus/authority/src/pbft.rs
> +        }
This check is really similar to the is_inturn check we do can we just re-use that here?

2024-05-30 12:37 UTC, arminsabouri commented on crates/consensus/authority/src/pbft.rs
> +        }
Additionally I've added some tighter bounds around the timestamp that can proposed by a peer in https://github.com/botanix-labs/Macbeth/pull/191

2024-05-30 12:37 UTC, arminsabouri commented on crates/consensus/authority/src/pbft.rs
> +        if block.timestamp >= end + BLOCK_TIME_VALIDITY_CRITERIA_RELAXATION.as_secs() {
b/c of the relaxation time, is there a possibility that two blocks produced by two peers are valid for the same minute time slot?

2024-06-04 16:53 UTC, arminsabouri reviewed
Two small questions

2024-06-04 16:53 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/pbft/test_pbft_disconnect.rs
> +    test_fed_members
What event is suppose to happen in the 10 seconds that this peer's peers are disconnected?

2024-06-04 16:53 UTC, arminsabouri commented on crates/primitives/src/header_ext.rs
> +        if current_in_turn_index != (signer_index as u64) {
Can we re-use the method defined in utils here
https://github.com/botanix-labs/Macbeth/pull/190/files#diff-70d823804b6ce466fbab201283c5261894ba0ba35696b2902c9abeced5815ab4R268

They seem to be doing the samething

2024-06-04 16:56 UTC, arminsabouri commented on crates/consensus/authority/src/pbft.rs
> +                let msg = secp256k1::Message::from_digest_slice(
What was the reasoning behind this change?

2024-06-05 14:01 UTC, BatiGencho commented on crates/consensus/authority/src/pbft.rs
> +                let msg = secp256k1::Message::from_digest_slice(
The linter suggested this as the from_slice is already deprecated.

2024-06-05 15:21 UTC, BatiGencho commented on bin/test-suite/src/suite/consensus/pbft/test_pbft_disconnect.rs
> +    test_fed_members
I am expecting a pbft restart

2024-06-05 15:32 UTC, BatiGencho commented on crates/primitives/src/header_ext.rs
> +        if current_in_turn_index != (signer_index as u64) {
This creates a circular dependency. The edh header rs is inside hte primitives crate  which the consensus is using. We cannot import the consensus back into it.

2024-06-05 19:24 UTC, merged