consolidate all botanix consensus checks to AuthorityConsensus
botanix-labs/Macbeth pull request #230
Opened 2024-06-07 13:04 UTC by BatiGencho

2024-06-10 12:53 UTC, arminsabouri requested changes
Approach ACK.
Bit of tidying required but overall great. Really like that we replace chainspec in a few places with consensus

2024-06-10 12:53 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
> +            &mut header.extra_data.to_vec().as_slice(),
Can you use the header ext trait functions here?

2024-06-10 12:53 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
> +        let sig_hash = create_authority_sighash(&mut header.clone(), &extra_data);
Same thing here

2024-06-10 12:53 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
> +        extra_data.validate_authority_signature(&sig_hash.to_vec(), authority_signers).map_err(
Can we use `check_authority_sig_add` from header_ext. And check the number of valid signatures = number of authorities. In the future this will be dynamic.

2024-06-10 12:53 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
> +        reth_consensus_common::validation::validate_header_standalone(header, &self.chain_spec)?;
Do we want to do `self::validate_block_standalone()` here instead?

2024-06-10 12:53 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
> +        reth_consensus_common::validation::validate_block_standalone(block, &self.chain_spec)
Same thing here

2024-06-10 12:53 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
> +        reth_consensus_common::validation::validate_header_standalone(header, &self.chain_spec)?;
I'm thinking since we only consider blocks valid if they pass poa consensus checks we should also validate the EDH.

2024-06-10 12:53 UTC, arminsabouri commented on crates/consensus/common/src/validation.rs
> +// }
Could remove unused

2024-06-10 12:53 UTC, arminsabouri commented on crates/consensus/common/src/utils.rs
> +// /// Validate poa block beneficiary
If this is no longer used. Lets remove

2024-06-10 12:53 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
> +
We also want to call `validate_timestamp()` from the header_ext.

2024-06-10 16:39 UTC, scottmillner commented
acking that ive reviewed and will review again as commits come in

2024-06-11 08:29 UTC, BatiGencho commented on crates/consensus/authority/src/lib.rs
> +        let sig_hash = create_authority_sighash(&mut header.clone(), &extra_data);
done

2024-06-11 08:29 UTC, BatiGencho commented on crates/consensus/authority/src/lib.rs
> +        extra_data.validate_authority_signature(&sig_hash.to_vec(), authority_signers).map_err(
done

2024-06-11 08:33 UTC, BatiGencho commented on crates/consensus/common/src/utils.rs
> +// /// Validate poa block beneficiary
done

2024-06-11 08:35 UTC, BatiGencho commented on crates/consensus/authority/src/lib.rs
> +
done

2024-06-12 05:59 UTC, BatiGencho commented on crates/consensus/common/src/validation.rs
> +// }
done

2024-06-12 08:15 UTC, BatiGencho commented on crates/consensus/authority/src/lib.rs
> +        reth_consensus_common::validation::validate_header_standalone(header, &self.chain_spec)?;
not sure what you mean here ?

2024-06-12 08:15 UTC, BatiGencho commented on crates/consensus/authority/src/lib.rs
> +        reth_consensus_common::validation::validate_block_standalone(block, &self.chain_spec)
can you please clarify

2024-06-12 13:33 UTC, BatiGencho commented on crates/consensus/authority/src/lib.rs
> +            &mut header.extra_data.to_vec().as_slice(),
done

2024-06-12 14:05 UTC, arminsabouri commented on crates/optimism/consensus/src/lib.rs
> -        // with OP-stack Bedrock activation number determines when TTD (eth Merge) has been reached.
We shouldnt be hitting the op stack consensus stuff but is the a reason for remove this code?
Should we panic instead?

2024-06-12 14:05 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
> +        reth_consensus_common::validation::validate_header_standalone(header, &self.chain_spec)?;
@BatiGencho Just following up on this one

2024-06-12 14:05 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
> +        // Validate the authority signature and signature came from one of the authorities
```suggestion
        // Validate a quorum of authority signatures
```

2024-06-12 14:05 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
> +        // Validate EDH serialization and signature on block
One more thing came to mind. Do we want to also run the common consensus standalone validation here?

2024-06-12 20:41 UTC, BatiGencho commented on crates/optimism/consensus/src/lib.rs
> -        // with OP-stack Bedrock activation number determines when TTD (eth Merge) has been reached.
fixed as it was on the poA-consensus.

2024-06-12 20:41 UTC, BatiGencho commented on crates/consensus/authority/src/lib.rs
> +        // Validate the authority signature and signature came from one of the authorities
renamed

2024-06-12 21:21 UTC, BatiGencho commented on crates/consensus/authority/src/lib.rs
> +        // Validate EDH serialization and signature on block
done

2024-06-12 21:25 UTC, BatiGencho commented on crates/consensus/authority/src/lib.rs
> +        reth_consensus_common::validation::validate_block_standalone(block, &self.chain_spec)
added

2024-06-12 21:27 UTC, BatiGencho commented on crates/consensus/authority/src/lib.rs
> +        reth_consensus_common::validation::validate_header_standalone(header, &self.chain_spec)?;
This is the method api:
  
    fn validate_header(&self, header: &SealedHeader) -> Result<(), ConsensusError> {
        reth_consensus_common::validation::validate_header_standalone(header, &self.chain_spec)?;
        Ok(())
    }
    
    I cannot add :
    
    pub fn validate_header_standalone(
    header: &SealedHeader,
    chain_spec: &ChainSpec,
) -> Result<(), ConsensusError> {

underneath it, as this would break the api and cause issues throughout reth.

2024-06-13 03:10 UTC, arminsabouri submitted a review, later dismissed

2024-06-13 12:58 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
> +        reth_consensus_common::validation::validate_header_standalone(header, &self.chain_spec)?;
Yeah i also had this realization. I think its fine for now. I need to sit down at somepoint and walk thru where all the consensus changes happen

2024-06-13 17:03 UTC, scottmillner submitted a review, later dismissed
lgtm but would wait for armin's ✅

2024-06-17 18:47 UTC, arminsabouri requested changes
Small Nit

2024-06-17 18:47 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
>          reth_consensus_common::validation::validate_block_standalone(block, &self.chain_spec)
I believe this is checking the same thing twice

2024-06-17 18:48 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
>          reth_consensus_common::validation::validate_block_standalone(block, &self.chain_spec)
Probably good to just run `reth_consensus_common::validation::validate_block_standalone`

2024-06-18 05:55 UTC, BatiGencho commented on crates/consensus/authority/src/lib.rs
>          reth_consensus_common::validation::validate_block_standalone(block, &self.chain_spec)
done

2024-06-18 13:43 UTC, arminsabouri submitted a review, later dismissed

2024-06-18 13:43 UTC, arminsabouri commented
Waiting for e2e tests to pass then good to merge

2024-06-18 17:05 UTC, scottmillner approved these changes

2024-06-21 03:09 UTC, arminsabouri approved these changes

2024-06-21 03:10 UTC, merged