extended chain.toml with is-testnet boolean
botanix-labs/Macbeth pull request #285
Opened 2024-07-09 21:31 UTC by BatiGencho

2024-07-12 04:26 UTC, arminsabouri approved these changes

2024-07-12 07:20 UTC, scottmillner submitted a review, later dismissed

2024-07-14 06:40 UTC, arminsabouri requested changes
Just noticed that we we're not using this is_testnet for its intended usage.

2024-07-14 06:40 UTC, arminsabouri commented on crates/node-core/src/args/genesis_args.rs
> +    pub is_testnet: bool,
My idea was the use this bool to switch between 3636 and the mainnet chainspec (which we dont have defined in code yet). And remove the idea of pasing chain as a param in cli flags. Can we do that with this boolean?

2024-07-14 12:53 UTC, arminsabouri submitted a review, later dismissed

2024-07-15 14:31 UTC, scottmillner commented on .github/workflows/lint.yml
> +    # Commenting out for now, will re-enable after final upstream merge
this is the only actual change in this file (the others are just formatting)

i don't think we're gaining much from this test but ill add back once we finish the last upstream merge

2024-07-16 09:00 UTC, merged