Refactor most of the Minting contract log parsing and handling code
botanix-labs/Macbeth pull request #293
Opened 2024-07-16 12:20 UTC by stevenroose

2024-07-17 11:00 UTC, stevenroose commented
If you want to read some code that is actually readable, you can always review the second commit, which contains the bulk of this change, and then verify that the last commit only does `make fmt` ;)

2024-07-19 09:38 UTC, arminsabouri commented on contracts/src/Minting.sol
> +
Im probably not the best person to review this part
tagging @scottmillner to take a look

2024-07-19 09:38 UTC, arminsabouri commented on contracts/src/Minting.sol
>          uint256 amount,
Do we use amount anywhere? Seems like mint amount should suffice

2024-07-19 09:38 UTC, arminsabouri commented on crates/consensus/authority/src/block_builder.rs
> +                        let pegin_match = try_parse_mint_event(log).expect("passed EVM check");
Comment justifiying the expect
```suggestion
                        // Mint event should have already been validated in during evm execution (in processor.rs) 
                        let pegin_match = try_parse_mint_event(log).expect("passed EVM check");
```

2024-07-19 09:38 UTC, arminsabouri commented on crates/consensus/authority/src/block_builder.rs
> +                            }
Should we continue here?
There is no reason to try to parse a burn event if already have a pegin.
Or maybe a if elseif

2024-07-19 09:38 UTC, arminsabouri commented on crates/consensus/authority/src/block_fetcher.rs
> +                                        }
Same comment here?

2024-07-19 09:38 UTC, arminsabouri commented on crates/consensus/authority/src/block_fetcher.rs
> +                                                //TODO(stevenroose) should this happen here?
Not a req for change.
I agree with this. Duplicate code. Ideally we have some Pegin/Pegout Processor util or struct

2024-07-19 09:38 UTC, arminsabouri commented on crates/revm/src/processor.rs
> +            .unwrap_or_else(|| bitcoin::Network::Regtest);
Maybe we should just panic here if no network is defined. If you are processing the botanix logs then this should be defined

2024-07-19 09:38 UTC, arminsabouri commented on crates/revm/src/processor.rs
> +            if pegin_data.bitcoin_block_height >= bitcoin_checkpoint.1 {
Is this correct? The error returned in the height is below the checkpoint. But here we are checking if the pegin block height is great than or eq to the checkpoint.

2024-07-19 09:38 UTC, arminsabouri commented on crates/revm/src/processor.rs
> +                    if aggregate_value == pegin_data.amount {
Should this be mint_amount? Or are those the same thing now?

2024-07-23 10:09 UTC, scottmillner commented on crates/consensus/authority/src/block_builder.rs
> +                            }
i guess you could have a contract that batches both pegins and pegouts in a single transaction so there could be pegin and pegout receipts in one tx...that is technically possible

2024-07-23 13:00 UTC, scottmillner commented on crates/revm/src/processor.rs
> +                    if aggregate_value == pegin_data.amount {
it's the same thing now

`Minting.sol` has been refactored to only emit a single event that contains both the original amount and the final mint amount

`try_parse_mint()` will set `PeginData.amount` to the final mint amount

and amount will be less than aggregate value bc tx cost is deducted from original amount

2024-07-23 13:17 UTC, scottmillner commented on contracts/src/Minting.sol
>          uint256 amount,
we don't but it's cheap to include in the event and my preference is to keep it
makes it very transparent if anyone really wanted to dig through logs and make sure everything is above board

2024-07-23 13:18 UTC, scottmillner commented
acking it all looks good
just needs an error message to be updated...see armin's comment

2024-07-24 17:48 UTC, scottmillner commented on crates/revm/src/processor.rs
> +            if pegin_data.bitcoin_block_height >= bitcoin_checkpoint.1 {
the check is correct but the error message isn't

- `bitcoin_checkpoint` is the header at the required depth (`let height = height.saturating_sub(pegin_conf_depth as usize - 1);`)
- so the pegin `bitcoin_block_height` should be equal or less than the checkpoint

ive updated the error message to reflect that and added a comment to explain

2024-07-24 17:51 UTC, scottmillner commented on crates/revm/src/processor.rs
> +            .unwrap_or_else(|| bitcoin::Network::Regtest);
done!

2024-07-25 03:39 UTC, scottmillner commented on contracts/src/Minting.sol
>          uint256 amount,
actually forgot you can only have 4 topics so will just use mint
that's why the int tests were failing: the topic hash was incorrect since the last topic wasn't being included

2024-07-26 18:00 UTC, arminsabouri requested changes
tNack
getting this on a pegin
```
Botanix Minting contract event validation failed: InvalidPeginData { error: "pegin height 350 greater than checkpoint of 353", revert_address: 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266, revert_amount: 9999932007753125000 }
```

Not sure why the int. test is passing

2024-07-26 18:10 UTC, arminsabouri commented
> tNack getting this on a pegin
> 
> ```
> Botanix Minting contract event validation failed: InvalidPeginData { error: "pegin height 350 greater than checkpoint of 353", revert_address: 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266, revert_amount: 9999932007753125000 }
> ```
> 
> Not sure why the int. test is passing

I believe the fix needed for this is here: https://github.com/botanix-labs/Macbeth/pull/314

When I manually add that check my pegin passes

2024-07-30 07:21 UTC, rwlockbg submitted a review, later dismissed

2024-07-30 13:43 UTC, arminsabouri commented on crates/revm/src/processor.rs
> +                    if aggregate_value == pegin_data.amount {
`if aggregate_value == pegin_data.amount`
Cab you explain the logic here? Is it due to the refund? 
Is it possible that a refund reciever isnt defined and the refund never occurs?

2024-07-30 13:43 UTC, arminsabouri commented on crates/revm/src/processor.rs
> +                    if aggregate_value == pegin_data.amount {
Additionally what is its greater? Should this be >= ?

2024-07-30 13:43 UTC, arminsabouri commented on crates/revm/src/processor.rs
> +                            error!("Botanix Minting contract event validation failed: {:?}", e);
```suggestion
                            error!("Botanix Minting contract burn event validation failed: {:?}", e);
```

2024-07-30 13:43 UTC, arminsabouri commented on crates/revm/src/processor.rs
> +                                        EthersU256::from_little_endian(pegout_amount.as_le_slice()),
Should gas be account for here?

2024-07-30 13:43 UTC, arminsabouri commented on crates/revm/src/processor.rs
> +                                        EthersU256::from_little_endian(pegout_amount.as_le_slice()),
Otherwise if someone can keep calling burn without having some account balance decremented won't that create supply that doesnt exist?

2024-07-30 14:53 UTC, scottmillner commented on crates/revm/src/processor.rs
> +                    if aggregate_value == pegin_data.amount {
yes, it is do to the refund so the aggregate amount should always be lower than the `amount` passed to the contract call

the `refundAddress` has to be passed to the contract call since it's part of the method signature, if it's not passed the call will fail

yes, it should be `>=`...nice catch!
done!

2024-07-30 15:00 UTC, scottmillner commented on crates/revm/src/processor.rs
> +                                        EthersU256::from_little_endian(pegout_amount.as_le_slice()),
gas is paid by the sender of the call to `mint()` which is sidecar at the moment but could be anyone

the EVM enforces that you have enough funds to cover gas and that has already been decremented from the sender account since this is a valid tx it terms of the EVM. It's just our additional logic that reverts it.  So gas has been handled correctly by the EVM before it gets to our custom validation logic.  All our logic needs to do is decrement the amount that was transferred to the destination address which we parse from `emit Mint(destination, amount, bitcoinBlockHeight, metadata);` in the call method.

TL;DR
it's impossible to call `burn()` without having enough ether to cover gas due to normal EVM rules

2024-07-30 17:56 UTC, arminsabouri commented on crates/revm/src/processor.rs
> +                    if aggregate_value == pegin_data.amount {
Nice!

2024-08-01 12:05 UTC, arminsabouri commented
@scottmillner Do you mind running thru some manual pegin/pegouts on this PR? As well as the functional test suite?

2024-08-02 15:09 UTC, merged