fix(poa_node): create edh limit on max inputs
botanix-labs/Macbeth pull request #311
Opened 2024-07-26 07:40 UTC by rwlockbg

Task: https://github.com/botanix-labs/botanix/issues/537
Int. test: https://github.com/botanix-labs/botanix/issues/534

2024-07-26 08:31 UTC, scottmillner submitted a review, later dismissed

2024-07-26 11:32 UTC, arminsabouri commented on bin/btc-server/src/cordinator.rs
> +            .take(max_allowed_inputs)
The problem here could be that certain UTXOs may get starved. 
Is there anyway to present BDK's coinselection algorithm the full utxo set and have the algorithm choose the best tx that only spends 100 inputs?

2024-07-26 13:54 UTC, rwlockbg commented on bin/btc-server/src/cordinator.rs
> +            .take(max_allowed_inputs)
I am not sure about this :) Maybe you could have a quick look and give me some guidelines

2024-07-26 17:38 UTC, arminsabouri commented on bin/btc-server/src/cordinator.rs
> +            .take(max_allowed_inputs)
Yeah I can help with this

2024-07-29 13:12 UTC, arminsabouri commented on bin/btc-server/src/cordinator.rs
> +            .take(max_allowed_inputs)
There doesnt seem like there is a way to restrict the size or number of inputs using the BDK coin selection algos. 
Perhaps we can select the first lowsest value UTXOs first. I'm not sure yet. It may be the case that we are also trying to optimize for something that isnt a problem yet.

2024-07-29 13:12 UTC, arminsabouri commented
Can we add https://github.com/botanix-labs/botanix/issues/534 as part of this PR

2024-07-29 14:52 UTC, rwlockbg commented
> Can we add [botanix-labs/botanix#534](https://github.com/botanix-labs/botanix/issues/534) as part of this PR

Yes, I will add it there.

2024-08-05 12:31 UTC, arminsabouri requested changes
Some things to fix. I am going to assign over to my self as rwlock is out of town this week

2024-08-05 12:31 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
> +pub const MAX_EDH_SIZE: usize = 5 * 8005; // 8005 - 100 spents
Not sure I understand this calculation?

2024-08-13 20:26 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_edh_size_limit.rs
> +    bitcoind_rpc.generate_to_address((NUM_PEGINS).into(), &address).expect("generate to address");
Do you mean to create `NUM_PEGINS ` blocks? 
101 should be sufficient

2024-08-19 16:50 UTC, rwlockbg commented on bin/btc-server/src/cordinator.rs
> +            .take(max_allowed_inputs)
@scottmillner @0xBEEFCAF3 Do we still want this change that I originally did or not ? Acc. to Armins comment, it looks as if we rather not cap here ?

2024-08-19 16:53 UTC, scottmillner commented on bin/btc-server/src/cordinator.rs
> +            .take(max_allowed_inputs)
should we revisit the value of this ticket and what we gain from it?

2024-08-22 06:41 UTC, rwlockbg commented on bin/btc-server/src/cordinator.rs
> +            .take(max_allowed_inputs)
removed

2024-08-22 12:44 UTC, arminsabouri commented
[fix: remvoved utxo capping (reverted back)](https://github.com/botanix-labs/Macbeth/pull/311/commits/1d45358509cfcd8dc3c0657a9ffe2c9fbf80073a) 
Can we just drop the original commit instead of having two commits: one that introduces a change and another one that removes that change

2024-08-22 14:18 UTC, arminsabouri commented
Int. test going forward: it would be great if the test being introduced in this PR can be refactored to do a multi pegin / multi pegout.

2024-08-22 15:37 UTC, closed without merging

2024-08-22 15:37 UTC, scottmillner commented
superceded by: https://github.com/botanix-labs/Macbeth/pull/362