fix(btc_server): remove pegin-conf cli flag
botanix-labs/Macbeth pull request #323
Opened 2024-07-31 12:39 UTC by rwlockbg

Ticket: https://github.com/botanix-labs/botanix/issues/579

2024-07-31 13:29 UTC, arminsabouri requested changes

2024-07-31 13:29 UTC, arminsabouri commented on bin/btc-server/src/util.rs
> +        bitcoin::Network::Testnet => 2,
I would panic on everything execpt regtest  and signet.

2024-07-31 13:29 UTC, arminsabouri commented on bin/btc-server/src/util.rs
> +        bitcoin::Network::Testnet => 2,
confirmation depth for our testnet should be 1

2024-07-31 14:23 UTC, rwlockbg commented on bin/btc-server/src/util.rs
> +        bitcoin::Network::Testnet => 2,
fixed

2024-07-31 15:31 UTC, arminsabouri commented on bin/btc-server/src/util.rs
> +        bitcoin::Network::Testnet | bitcoin::Network::Signet => 1,
I think we need to include regtest here. Otherwise our local set ups and int. should fail

2024-07-31 15:34 UTC, arminsabouri commented on bin/btc-server/src/util.rs
> +        bitcoin::Network::Testnet | bitcoin::Network::Signet => 1,
Added this

2024-07-31 20:29 UTC, arminsabouri approved these changes

2024-07-31 21:43 UTC, rwlockbg commented on bin/btc-server/src/util.rs
> +        bitcoin::Network::Testnet | bitcoin::Network::Signet => 1,
thx

2024-08-01 15:07 UTC, arminsabouri approved these changes
@rwlockbg force pushed a rebase and dropped the merge commit. Waiting for CI to pass before merging

2024-08-01 15:20 UTC, merged