Some refactoring of pages + changes to text and typos
botanix-labs/Macbeth pull request #347
Opened 2024-08-16 16:02 UTC by jeffgeudens

Based on https://github.com/botanix-labs/botanix/issues/626

2024-08-16 16:16 UTC, arminsabouri requested changes

2024-08-16 16:16 UTC, arminsabouri commented on book/intro.md
> +matter for what they're doing.
Not sure I understand this

2024-08-16 16:16 UTC, arminsabouri commented on book/run/observability.md
> +# Logs and observability
Why truncate this?

2024-08-16 16:16 UTC, arminsabouri commented on book/cli/poa.md
> +          Soft limit for the byte size of a `PooledTransactions` response on assembling a `GetPooledTransactions` request. Spec`d at 2 MiB.
why a back tick here?

2024-08-16 16:16 UTC, arminsabouri commented on book/cli/poa.md
> -# `reth poa`
technically this should be `reth poa` as we are running the reth binary with the poa command.

I think this is fine

2024-08-19 07:53 UTC, jeffgeudens commented on book/intro.md
> +matter for what they're doing.
Sorry, this was a mistake. Forgot to replace the text. Will fix.

2024-08-19 07:54 UTC, jeffgeudens commented on book/run/observability.md
> +# Logs and observability
To have consistency on all pages. Same wording in the title on the page, table of contents on the left and list overview on the "Run a node" page.

2024-08-19 07:55 UTC, jeffgeudens commented on book/cli/poa.md
> +          Soft limit for the byte size of a `PooledTransactions` response on assembling a `GetPooledTransactions` request. Spec`d at 2 MiB.
Makes that the formatting looks better on the page. If you visit https://books.botanixlabs.dev/cli/poa.html , you'll see that a lot of the code is yellow. This is solved by using the back tick here.

2024-08-19 07:57 UTC, jeffgeudens commented on book/cli/poa.md
> -# `reth poa`
Will change it back

2024-08-21 12:48 UTC, arminsabouri approved these changes
Commits squashed. 
lets wait till CI passes then good to merge

2024-08-21 14:13 UTC, merged