added cargo audit and coverage to ci/cd
botanix-labs/Macbeth pull request #361
Opened 2024-08-22 15:06 UTC by rwlockbg

2024-08-22 19:20 UTC, arminsabouri requested changes

2024-08-22 19:20 UTC, arminsabouri commented on .github/workflows/coverage.yml
> +        branches: [feature/poA-consensus]
This branch is no longer used

2024-08-27 14:31 UTC, arminsabouri commented
@rwlockbg just need to fix the conflict here

2024-09-17 09:37 UTC, rwlockbg commented on .github/workflows/coverage.yml
> +        branches: [feature/poA-consensus]
removed

2024-09-19 12:43 UTC, arminsabouri commented
@rwlockbg do you mind dropping the merge commits? In general i would rebase the latest changes rather than introducing merge commits.
https://github.com/botanix-labs/botanix/blob/master/CONTRIBUTING.MD

2024-09-19 16:22 UTC, arminsabouri commented
Looks like we have some permission issues
```
debug - 2024-09-19 15:54:25,068 -- Commit creating result --- {"result": "RequestResult(error=RequestError(code='HTTP Error 403', params={}, description='{\"detail\":\"You do not have permission to perform this action.\"}'), warnings=[], status_code=403, text='{\"detail\":\"You do not have permission to perform this action.\"}')"}
error - 2024-09-19 15:54:25,0[68](https://github.com/botanix-labs/Macbeth/actions/runs/10944526500/job/30386605055?pr=361#step:9:69) -- Commit creating failed: {"detail":"You do not have permission to perform this action."}
```

2024-09-20 06:36 UTC, rwlockbg commented
> Looks like we have some permission issues
> 
> ```
> debug - 2024-09-19 15:54:25,068 -- Commit creating result --- {"result": "RequestResult(error=RequestError(code='HTTP Error 403', params={}, description='{\"detail\":\"You do not have permission to perform this action.\"}'), warnings=[], status_code=403, text='{\"detail\":\"You do not have permission to perform this action.\"}')"}
> error - 2024-09-19 15:54:25,0[68](https://github.com/botanix-labs/Macbeth/actions/runs/10944526500/job/30386605055?pr=361#step:9:69) -- Commit creating failed: {"detail":"You do not have permission to perform this action."}
> ```

@birozuru SInce I am not the owner of the repo, this error pops up. Rememeber that when you run the coverage, it was all fine with codecov ?

2024-09-20 07:36 UTC, birozuru commented
> > Looks like we have some permission issues
> > ```
> > debug - 2024-09-19 15:54:25,068 -- Commit creating result --- {"result": "RequestResult(error=RequestError(code='HTTP Error 403', params={}, description='{\"detail\":\"You do not have permission to perform this action.\"}'), warnings=[], status_code=403, text='{\"detail\":\"You do not have permission to perform this action.\"}')"}
> > error - 2024-09-19 15:54:25,0[68](https://github.com/botanix-labs/Macbeth/actions/runs/10944526500/job/30386605055?pr=361#step:9:69) -- Commit creating failed: {"detail":"You do not have permission to perform this action."}
> > ```
> 
> @birozuru SInce I am not the owner of the repo, this error pops up. Rememeber that when you run the coverage, it was all fine with codecov ?

Yeah seems like it's permission issues on your github_token

2024-09-23 06:31 UTC, rwlockbg commented
@birozuru @0xBEEFCAF3 lets merge this MR and @birozuru will replace my token with his codedev token ?

2024-09-23 09:23 UTC, birozuru commented
> @birozuru @0xBEEFCAF3 lets merge this MR and @birozuru will replace my token with his codedev token ?

Gonna replace now and rerun the workflow.

2024-09-24 08:45 UTC, birozuru approved these changes
Codecov token updated. LGTM

2024-09-24 14:14 UTC, arminsabouri approved these changes

2024-09-24 14:15 UTC, merged