edh limit max inputs cherry pick
botanix-labs/Macbeth pull request #362
Opened 2024-08-22 15:35 UTC by scottmillner

supercedes: https://github.com/botanix-labs/Macbeth/pull/311

2024-08-22 18:00 UTC, arminsabouri requested changes
Had one question about an unwrap. And a couple other things

2024-08-22 18:00 UTC, arminsabouri commented on bin/btc-server/src/signer.rs
> +            .unwrap();
Unwrap seems strictly worse

2024-08-22 18:00 UTC, arminsabouri commented on crates/consensus/auto-seal/Cargo.toml
> +bitcoin.workspace = true
Is this change related? Or just fixing the build

2024-08-22 18:00 UTC, arminsabouri commented on crates/botanix-lib/src/peg_contract.rs
> +pub mod tests {
Did we accidentally remove these tests?

2024-08-22 19:39 UTC, scottmillner commented on bin/btc-server/src/signer.rs
> +            .unwrap();
agreed, rolledback

2024-08-22 19:39 UTC, scottmillner commented on crates/consensus/auto-seal/Cargo.toml
> +bitcoin.workspace = true
not related nor needed...rolledback

2024-08-22 19:39 UTC, scottmillner commented on crates/botanix-lib/src/peg_contract.rs
> +pub mod tests {
mistake...it included two tests twice...rolledback

2024-08-23 22:33 UTC, arminsabouri approved these changes
CodeACk
Just squash the last two commits and we are good to go

2024-08-27 14:26 UTC, merged