feature(pegout): metadata should be pegout version
botanix-labs/Macbeth pull request #377
Opened 2024-09-03 17:02 UTC by scottmillner

2024-09-03 17:19 UTC, arminsabouri requested changes

2024-09-03 17:19 UTC, arminsabouri commented on crates/botanix-lib/src/mint_validation.rs
> +    // TODO: add decode_log_payload for pegout
Nice todo !

2024-09-03 17:19 UTC, arminsabouri commented on crates/botanix-lib/src/mint_validation.rs
> +        )));
If we upgrade the network with v1 then some older client will always reject any version that is not v0. As long as a supermajority upgrade then we can upgrade to v1. But this would be a hardfork. Instead for a softfork what we want is to provide the same fields (destination, amount) and append future additional fields. So in short It should be fine to not check the version here. In the future upgraded client will know that there are additional fields pass the old (maybe deprecated ones).

2024-09-03 17:31 UTC, scottmillner commented on crates/botanix-lib/src/mint_validation.rs
> +        )));
ah yep, refactored to check and print legacy version if detected
can add legacy support when needed

2024-09-05 11:26 UTC, arminsabouri approved these changes
Nits only

2024-09-05 11:26 UTC, arminsabouri commented on crates/botanix-lib/src/peg_contract.rs
> +    // current version of the pegout which is checked during validation
```suggestion
    // current version of the pegout data structure
```

2024-09-05 11:26 UTC, arminsabouri commented on crates/botanix-lib/src/mint_validation.rs
> +        info!("Legacy pegout submitted, version: {}", metadata[0].to_string());
```suggestion
        info!("unexpected pegout version submitted, version: {}", metadata[0].to_string());
```

2024-09-05 14:17 UTC, merged