rework: fully reworked integration test suite
botanix-labs/Macbeth pull request #406
Opened 2024-09-27 12:24 UTC by rwlockbg

2024-09-27 12:33 UTC, arminsabouri submitted a review, later dismissed
ApproachAck

2024-10-01 16:36 UTC, arminsabouri commented
@rwlockbg do you mind dropping these merge commits when this PR is ready for review 
Thanks

2024-10-07 17:17 UTC, arminsabouri requested changes
Really impressive how much ground you have covered. 
I Have roughly reviewed 50% of this code change.

2024-10-07 17:17 UTC, arminsabouri commented on Makefile
> +	--validators 1
is validators the number of comet nodes? In that case isnt that he same value as max-signers?

2024-10-07 17:17 UTC, arminsabouri commented on bin/test-suite/.gitignore
> +# config.toml
Could remove?

2024-10-07 17:17 UTC, arminsabouri commented on bin/test-suite/src/shutdown.rs
> +mod tests {
Nice tests!!! 👍

2024-10-07 17:17 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/bitcoind/test_bitcoind_networking.rs
> +    // TODO: Implement bitcoind networking test
What would be the test you would want to see here?

2024-10-07 17:17 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/cometbft/test_cometbft_networking.rs
> +    // TODO: Implement CometBFT networking test
Same thing here: 
What would be the test you would want to see here?

2024-10-07 17:17 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/common/bitcoind_node.rs
> +        }
Should this take as argument a location to bitcoind? I imagine we all have a different dir strucuture?

2024-10-07 17:17 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/common/bitcoind_node.rs
> +    pub fn await_initialization(&self) -> anyhow::Result<()> {
Should this be blocking?

2024-10-07 17:17 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/common/bitcoind_node.rs
> +    pub fn await_initialization(&self) -> anyhow::Result<()> {
Maybe wait till the response from getblockchaininfo isSyncing response is false?

2024-10-07 17:17 UTC, arminsabouri commented on test_runner.sh
>  tests_to_run=("dkg_flow" "utxo_commitment" "many_inputs_signing")
Are there any more tests you want to add back in? Maybe block signing? frost e2e will not work as is b/c pegouts are currently disabled.

2024-10-07 22:02 UTC, rwlockbg commented on Makefile
> +	--validators 1
its the num of rpc_nodes. I have renamed it now, wrong naming... sorry

2024-10-07 22:02 UTC, rwlockbg commented on bin/test-suite/.gitignore
> +# config.toml
done

2024-10-07 22:03 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/common/bitcoind_node.rs
> +        }
Not needed, the working directory is irrelevant where it sits... it is just a temp one, I have refactored it now.

2024-10-07 22:03 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/common/bitcoind_node.rs
> +    pub fn await_initialization(&self) -> anyhow::Result<()> {
yep, will add it tomorrow.

2024-10-08 15:38 UTC, arminsabouri reviewed
Couple more nits and questions

2024-10-08 15:38 UTC, arminsabouri commented on Makefile
> +	--rpc-nodes 1
Should this be configurable on the individual tests?
Some tests may need x rpc nodes while others need none

2024-10-08 15:38 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/common/bitcoind_node.rs
> +    pub botanix_eth_client: Option<BotanixEthClient>,
Do we need this?

2024-10-08 15:38 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/common/comet_node.rs
> +    let args = vec!["init", "--home", &working_dir_str];
add TODO to add -k flag

2024-10-09 07:50 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/common/bitcoind_node.rs
> +    pub botanix_eth_client: Option<BotanixEthClient>,
nope, removed

2024-10-09 07:50 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/common/comet_node.rs
> +    let args = vec!["init", "--home", &working_dir_str];
added it back

2024-10-09 07:54 UTC, rwlockbg commented on Makefile
> +	--rpc-nodes 1
If we do it that way , then we might as well specify the nb. of min/max signers = poa nodes. Right now , this is the highest number of rpc nodes to be spawned by the test suite. If the individual tests should use them or not, that is up to them to decide. Same applies to min/max signers = poa nodes. You can specify the federation scale this way, tests will then decide on how many of them they need. Again, nothing against your idea, but it might make sense to apply it to all poa, rpc  etc.

2024-10-09 07:55 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/cometbft/test_cometbft_networking.rs
> +    // TODO: Implement CometBFT networking test
Lets keep them empty for now. We can add later meaningful tests in a separate MR.

2024-10-09 07:55 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/bitcoind/test_bitcoind_networking.rs
> +    // TODO: Implement bitcoind networking test
Lets keep them empty for now. We can add later meaningful tests in a separate MR.

2024-10-09 13:15 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/bitcoind/test_bitcoind_networking.rs
> +    // TODO: Implement bitcoind networking test
But what would you want to test here? If we dont have ideas for a test yet I would say lets remove and save time on CI

2024-10-09 13:16 UTC, arminsabouri commented on Makefile
> +	--rpc-nodes 1
makes sense. Thanks

2024-10-09 13:18 UTC, arminsabouri commented on test_runner.sh
>  tests_to_run=("dkg_flow" "utxo_commitment" "many_inputs_signing")
@rwlockbg Following up on this point

2024-10-09 13:18 UTC, arminsabouri commented on test_runner.sh
>  tests_to_run=("dkg_flow" "utxo_commitment" "many_inputs_signing")
@rwlockbg Following up on this point

2024-10-09 20:52 UTC, birozuru commented
# eBurger report

2024-10-09 20:53 UTC, birozuru commented
# Slither report
**THIS CHECKLIST IS NOT COMPLETE**. Use `--show-ignored-findings` to show all the results.
Summary
 - [arbitrary-send-eth](#arbitrary-send-eth) (2 results) (High)
 - [events-access](#events-access) (1 results) (Low)
 - [events-maths](#events-maths) (2 results) (Low)
 - [missing-zero-check](#missing-zero-check) (2 results) (Low)
 - [calls-loop](#calls-loop) (1 results) (Low)
 - [timestamp](#timestamp) (1 results) (Low)
 - [solc-version](#solc-version) (1 results) (Informational)
 - [reentrancy-unlimited-gas](#reentrancy-unlimited-gas) (3 results) (Informational)
 - [too-many-digits](#too-many-digits) (1 results) (Informational)
## arbitrary-send-eth
Impact: High
Confidence: Medium
 - [ ] ID-0
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L33-L42) sends eth to arbitrary user
	Dangerous calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-1
[Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Minting.sol#L45-L84) sends eth to arbitrary user
	Dangerous calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Minting.sol#L45-L84


## events-access
Impact: Low
Confidence: Medium
 - [ ] ID-2
[Faucet.setOwner(address)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L53-L55) should emit an event for: 
	- [owner = account](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L54) 

https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L53-L55


## events-maths
Impact: Low
Confidence: Medium
 - [ ] ID-3
[Faucet.setLockTime(uint256)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L61-L63) should emit an event for: 
	- [lockTime = amount * 60](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L62) 

https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L61-L63


 - [ ] ID-4
[Faucet.setWithdrawAmount(uint256)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L57-L59) should emit an event for: 
	- [withdrawAmount = amount](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L58) 

https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L57-L59


## missing-zero-check
Impact: Low
Confidence: Medium
 - [ ] ID-5
[Faucet.setOwner(address).account](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L53) lacks a zero-check on :
		- [owner = account](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L54)

https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L53


 - [ ] ID-6
[Minting.mint(address,uint256,uint32,bytes,address).refundAddress](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Minting.sol#L50) lacks a zero-check on :
		- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Minting.sol#L50


## calls-loop
Impact: Low
Confidence: Medium
 - [ ] ID-7
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L33-L42) has external calls inside a loop: [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L33-L42


## timestamp
Impact: Low
Confidence: Medium
 - [ ] ID-8
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L33-L42) uses timestamp for comparisons
	Dangerous comparisons:
	- [require(bool,string)(block.timestamp >= nextRequestAt[account],Insufficient time between requests)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L36)

https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L33-L42


## solc-version
Impact: Informational
Confidence: High
 - [ ] ID-9
Version constraint ^0.8.13 contains known severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)
	- VerbatimInvalidDeduplication
	- FullInlinerNonExpressionSplitArgumentEvaluationOrder
	- MissingSideEffectsOnSelectorAccess
	- StorageWriteRemovalBeforeConditionalTermination
	- AbiReencodingHeadOverflowWithStaticArrayCleanup
	- DirtyBytesArrayToStorage
	- InlineAssemblyMemorySideEffects
	- DataLocationChangeInInternalOverride
	- NestedCalldataArrayAbiReencodingSizeValidation.
It is used by:
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L2)
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Minting.sol#L2)

https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L2


## reentrancy-unlimited-gas
Impact: Informational
Confidence: Medium
 - [ ] ID-10
Reentrancy in [Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L33-L42):
	External calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L40)
	Event emitted after the call(s):
	- [Transfer(account,withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L41)

https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-11
Reentrancy in [Faucet.withdrawFunds()](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L44-L47):
	External calls:
	- [address(owner).transfer(address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L45)
	Event emitted after the call(s):
	- [Withdraw(owner,address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L46)

https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a01e1744b071a29bc56509189/contracts/src/Faucet.sol#L44-L47


 - [ ] ID-12
Reentrancy in [Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/58b417ea4dfead4a0 [...]

2024-10-10 09:46 UTC, birozuru commented
# eBurger report

2024-10-10 09:46 UTC, birozuru commented
# Slither report
**THIS CHECKLIST IS NOT COMPLETE**. Use `--show-ignored-findings` to show all the results.
Summary
 - [arbitrary-send-eth](#arbitrary-send-eth) (2 results) (High)
 - [events-access](#events-access) (1 results) (Low)
 - [events-maths](#events-maths) (2 results) (Low)
 - [missing-zero-check](#missing-zero-check) (2 results) (Low)
 - [calls-loop](#calls-loop) (1 results) (Low)
 - [timestamp](#timestamp) (1 results) (Low)
 - [solc-version](#solc-version) (1 results) (Informational)
 - [reentrancy-unlimited-gas](#reentrancy-unlimited-gas) (3 results) (Informational)
 - [too-many-digits](#too-many-digits) (1 results) (Informational)
## arbitrary-send-eth
Impact: High
Confidence: Medium
 - [ ] ID-0
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L33-L42) sends eth to arbitrary user
	Dangerous calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-1
[Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Minting.sol#L45-L84) sends eth to arbitrary user
	Dangerous calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Minting.sol#L45-L84


## events-access
Impact: Low
Confidence: Medium
 - [ ] ID-2
[Faucet.setOwner(address)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L53-L55) should emit an event for: 
	- [owner = account](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L54) 

https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L53-L55


## events-maths
Impact: Low
Confidence: Medium
 - [ ] ID-3
[Faucet.setLockTime(uint256)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L61-L63) should emit an event for: 
	- [lockTime = amount * 60](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L62) 

https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L61-L63


 - [ ] ID-4
[Faucet.setWithdrawAmount(uint256)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L57-L59) should emit an event for: 
	- [withdrawAmount = amount](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L58) 

https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L57-L59


## missing-zero-check
Impact: Low
Confidence: Medium
 - [ ] ID-5
[Faucet.setOwner(address).account](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L53) lacks a zero-check on :
		- [owner = account](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L54)

https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L53


 - [ ] ID-6
[Minting.mint(address,uint256,uint32,bytes,address).refundAddress](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Minting.sol#L50) lacks a zero-check on :
		- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Minting.sol#L50


## calls-loop
Impact: Low
Confidence: Medium
 - [ ] ID-7
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L33-L42) has external calls inside a loop: [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L33-L42


## timestamp
Impact: Low
Confidence: Medium
 - [ ] ID-8
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L33-L42) uses timestamp for comparisons
	Dangerous comparisons:
	- [require(bool,string)(block.timestamp >= nextRequestAt[account],Insufficient time between requests)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L36)

https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L33-L42


## solc-version
Impact: Informational
Confidence: High
 - [ ] ID-9
Version constraint ^0.8.13 contains known severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)
	- VerbatimInvalidDeduplication
	- FullInlinerNonExpressionSplitArgumentEvaluationOrder
	- MissingSideEffectsOnSelectorAccess
	- StorageWriteRemovalBeforeConditionalTermination
	- AbiReencodingHeadOverflowWithStaticArrayCleanup
	- DirtyBytesArrayToStorage
	- InlineAssemblyMemorySideEffects
	- DataLocationChangeInInternalOverride
	- NestedCalldataArrayAbiReencodingSizeValidation.
It is used by:
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L2)
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Minting.sol#L2)

https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L2


## reentrancy-unlimited-gas
Impact: Informational
Confidence: Medium
 - [ ] ID-10
Reentrancy in [Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L33-L42):
	External calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L40)
	Event emitted after the call(s):
	- [Transfer(account,withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L41)

https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-11
Reentrancy in [Faucet.withdrawFunds()](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L44-L47):
	External calls:
	- [address(owner).transfer(address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L45)
	Event emitted after the call(s):
	- [Withdraw(owner,address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L46)

https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed0497ecb10b983e962237ca1f15/contracts/src/Faucet.sol#L44-L47


 - [ ] ID-12
Reentrancy in [Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/804e6bd36806ed049 [...]

2024-10-10 10:33 UTC, birozuru commented
# eBurger report

2024-10-10 10:34 UTC, birozuru commented
# Slither report
**THIS CHECKLIST IS NOT COMPLETE**. Use `--show-ignored-findings` to show all the results.
Summary
 - [arbitrary-send-eth](#arbitrary-send-eth) (2 results) (High)
 - [events-access](#events-access) (1 results) (Low)
 - [events-maths](#events-maths) (2 results) (Low)
 - [missing-zero-check](#missing-zero-check) (2 results) (Low)
 - [calls-loop](#calls-loop) (1 results) (Low)
 - [timestamp](#timestamp) (1 results) (Low)
 - [solc-version](#solc-version) (1 results) (Informational)
 - [reentrancy-unlimited-gas](#reentrancy-unlimited-gas) (3 results) (Informational)
 - [too-many-digits](#too-many-digits) (1 results) (Informational)
## arbitrary-send-eth
Impact: High
Confidence: Medium
 - [ ] ID-0
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L33-L42) sends eth to arbitrary user
	Dangerous calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-1
[Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Minting.sol#L45-L84) sends eth to arbitrary user
	Dangerous calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Minting.sol#L45-L84


## events-access
Impact: Low
Confidence: Medium
 - [ ] ID-2
[Faucet.setOwner(address)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L53-L55) should emit an event for: 
	- [owner = account](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L54) 

https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L53-L55


## events-maths
Impact: Low
Confidence: Medium
 - [ ] ID-3
[Faucet.setLockTime(uint256)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L61-L63) should emit an event for: 
	- [lockTime = amount * 60](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L62) 

https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L61-L63


 - [ ] ID-4
[Faucet.setWithdrawAmount(uint256)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L57-L59) should emit an event for: 
	- [withdrawAmount = amount](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L58) 

https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L57-L59


## missing-zero-check
Impact: Low
Confidence: Medium
 - [ ] ID-5
[Faucet.setOwner(address).account](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L53) lacks a zero-check on :
		- [owner = account](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L54)

https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L53


 - [ ] ID-6
[Minting.mint(address,uint256,uint32,bytes,address).refundAddress](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Minting.sol#L50) lacks a zero-check on :
		- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Minting.sol#L50


## calls-loop
Impact: Low
Confidence: Medium
 - [ ] ID-7
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L33-L42) has external calls inside a loop: [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L33-L42


## timestamp
Impact: Low
Confidence: Medium
 - [ ] ID-8
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L33-L42) uses timestamp for comparisons
	Dangerous comparisons:
	- [require(bool,string)(block.timestamp >= nextRequestAt[account],Insufficient time between requests)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L36)

https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L33-L42


## solc-version
Impact: Informational
Confidence: High
 - [ ] ID-9
Version constraint ^0.8.13 contains known severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)
	- VerbatimInvalidDeduplication
	- FullInlinerNonExpressionSplitArgumentEvaluationOrder
	- MissingSideEffectsOnSelectorAccess
	- StorageWriteRemovalBeforeConditionalTermination
	- AbiReencodingHeadOverflowWithStaticArrayCleanup
	- DirtyBytesArrayToStorage
	- InlineAssemblyMemorySideEffects
	- DataLocationChangeInInternalOverride
	- NestedCalldataArrayAbiReencodingSizeValidation.
It is used by:
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L2)
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Minting.sol#L2)

https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L2


## reentrancy-unlimited-gas
Impact: Informational
Confidence: Medium
 - [ ] ID-10
Reentrancy in [Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L33-L42):
	External calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L40)
	Event emitted after the call(s):
	- [Transfer(account,withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L41)

https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-11
Reentrancy in [Faucet.withdrawFunds()](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L44-L47):
	External calls:
	- [address(owner).transfer(address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L45)
	Event emitted after the call(s):
	- [Withdraw(owner,address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L46)

https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472537efe7a49c6090723630c0/contracts/src/Faucet.sol#L44-L47


 - [ ] ID-12
Reentrancy in [Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/46ef44e49ea79b472 [...]

2024-10-10 12:49 UTC, birozuru commented
# eBurger report

2024-10-10 12:49 UTC, birozuru commented
# Slither report
**THIS CHECKLIST IS NOT COMPLETE**. Use `--show-ignored-findings` to show all the results.
Summary
 - [arbitrary-send-eth](#arbitrary-send-eth) (2 results) (High)
 - [events-access](#events-access) (1 results) (Low)
 - [events-maths](#events-maths) (2 results) (Low)
 - [missing-zero-check](#missing-zero-check) (2 results) (Low)
 - [calls-loop](#calls-loop) (1 results) (Low)
 - [timestamp](#timestamp) (1 results) (Low)
 - [solc-version](#solc-version) (1 results) (Informational)
 - [reentrancy-unlimited-gas](#reentrancy-unlimited-gas) (3 results) (Informational)
 - [too-many-digits](#too-many-digits) (1 results) (Informational)
## arbitrary-send-eth
Impact: High
Confidence: Medium
 - [ ] ID-0
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L33-L42) sends eth to arbitrary user
	Dangerous calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-1
[Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Minting.sol#L45-L84) sends eth to arbitrary user
	Dangerous calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Minting.sol#L45-L84


## events-access
Impact: Low
Confidence: Medium
 - [ ] ID-2
[Faucet.setOwner(address)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L53-L55) should emit an event for: 
	- [owner = account](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L54) 

https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L53-L55


## events-maths
Impact: Low
Confidence: Medium
 - [ ] ID-3
[Faucet.setLockTime(uint256)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L61-L63) should emit an event for: 
	- [lockTime = amount * 60](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L62) 

https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L61-L63


 - [ ] ID-4
[Faucet.setWithdrawAmount(uint256)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L57-L59) should emit an event for: 
	- [withdrawAmount = amount](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L58) 

https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L57-L59


## missing-zero-check
Impact: Low
Confidence: Medium
 - [ ] ID-5
[Faucet.setOwner(address).account](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L53) lacks a zero-check on :
		- [owner = account](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L54)

https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L53


 - [ ] ID-6
[Minting.mint(address,uint256,uint32,bytes,address).refundAddress](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Minting.sol#L50) lacks a zero-check on :
		- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Minting.sol#L50


## calls-loop
Impact: Low
Confidence: Medium
 - [ ] ID-7
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L33-L42) has external calls inside a loop: [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L33-L42


## timestamp
Impact: Low
Confidence: Medium
 - [ ] ID-8
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L33-L42) uses timestamp for comparisons
	Dangerous comparisons:
	- [require(bool,string)(block.timestamp >= nextRequestAt[account],Insufficient time between requests)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L36)

https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L33-L42


## solc-version
Impact: Informational
Confidence: High
 - [ ] ID-9
Version constraint ^0.8.13 contains known severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)
	- VerbatimInvalidDeduplication
	- FullInlinerNonExpressionSplitArgumentEvaluationOrder
	- MissingSideEffectsOnSelectorAccess
	- StorageWriteRemovalBeforeConditionalTermination
	- AbiReencodingHeadOverflowWithStaticArrayCleanup
	- DirtyBytesArrayToStorage
	- InlineAssemblyMemorySideEffects
	- DataLocationChangeInInternalOverride
	- NestedCalldataArrayAbiReencodingSizeValidation.
It is used by:
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L2)
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Minting.sol#L2)

https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L2


## reentrancy-unlimited-gas
Impact: Informational
Confidence: Medium
 - [ ] ID-10
Reentrancy in [Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L33-L42):
	External calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L40)
	Event emitted after the call(s):
	- [Transfer(account,withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L41)

https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-11
Reentrancy in [Faucet.withdrawFunds()](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L44-L47):
	External calls:
	- [address(owner).transfer(address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L45)
	Event emitted after the call(s):
	- [Withdraw(owner,address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L46)

https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f27e9c5fd72a6bacccb1a68a/contracts/src/Faucet.sol#L44-L47


 - [ ] ID-12
Reentrancy in [Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/e5148c5babb82347f [...]

2024-10-10 13:29 UTC, birozuru commented
# eBurger report

2024-10-10 13:30 UTC, birozuru commented
# Slither report
**THIS CHECKLIST IS NOT COMPLETE**. Use `--show-ignored-findings` to show all the results.
Summary
 - [arbitrary-send-eth](#arbitrary-send-eth) (2 results) (High)
 - [events-access](#events-access) (1 results) (Low)
 - [events-maths](#events-maths) (2 results) (Low)
 - [missing-zero-check](#missing-zero-check) (2 results) (Low)
 - [calls-loop](#calls-loop) (1 results) (Low)
 - [timestamp](#timestamp) (1 results) (Low)
 - [solc-version](#solc-version) (1 results) (Informational)
 - [reentrancy-unlimited-gas](#reentrancy-unlimited-gas) (3 results) (Informational)
 - [too-many-digits](#too-many-digits) (1 results) (Informational)
## arbitrary-send-eth
Impact: High
Confidence: Medium
 - [ ] ID-0
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L33-L42) sends eth to arbitrary user
	Dangerous calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-1
[Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Minting.sol#L45-L84) sends eth to arbitrary user
	Dangerous calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Minting.sol#L45-L84


## events-access
Impact: Low
Confidence: Medium
 - [ ] ID-2
[Faucet.setOwner(address)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L53-L55) should emit an event for: 
	- [owner = account](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L54) 

https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L53-L55


## events-maths
Impact: Low
Confidence: Medium
 - [ ] ID-3
[Faucet.setLockTime(uint256)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L61-L63) should emit an event for: 
	- [lockTime = amount * 60](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L62) 

https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L61-L63


 - [ ] ID-4
[Faucet.setWithdrawAmount(uint256)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L57-L59) should emit an event for: 
	- [withdrawAmount = amount](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L58) 

https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L57-L59


## missing-zero-check
Impact: Low
Confidence: Medium
 - [ ] ID-5
[Faucet.setOwner(address).account](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L53) lacks a zero-check on :
		- [owner = account](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L54)

https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L53


 - [ ] ID-6
[Minting.mint(address,uint256,uint32,bytes,address).refundAddress](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Minting.sol#L50) lacks a zero-check on :
		- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Minting.sol#L50


## calls-loop
Impact: Low
Confidence: Medium
 - [ ] ID-7
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L33-L42) has external calls inside a loop: [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L33-L42


## timestamp
Impact: Low
Confidence: Medium
 - [ ] ID-8
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L33-L42) uses timestamp for comparisons
	Dangerous comparisons:
	- [require(bool,string)(block.timestamp >= nextRequestAt[account],Insufficient time between requests)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L36)

https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L33-L42


## solc-version
Impact: Informational
Confidence: High
 - [ ] ID-9
Version constraint ^0.8.13 contains known severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)
	- VerbatimInvalidDeduplication
	- FullInlinerNonExpressionSplitArgumentEvaluationOrder
	- MissingSideEffectsOnSelectorAccess
	- StorageWriteRemovalBeforeConditionalTermination
	- AbiReencodingHeadOverflowWithStaticArrayCleanup
	- DirtyBytesArrayToStorage
	- InlineAssemblyMemorySideEffects
	- DataLocationChangeInInternalOverride
	- NestedCalldataArrayAbiReencodingSizeValidation.
It is used by:
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L2)
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Minting.sol#L2)

https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L2


## reentrancy-unlimited-gas
Impact: Informational
Confidence: Medium
 - [ ] ID-10
Reentrancy in [Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L33-L42):
	External calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L40)
	Event emitted after the call(s):
	- [Transfer(account,withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L41)

https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-11
Reentrancy in [Faucet.withdrawFunds()](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L44-L47):
	External calls:
	- [address(owner).transfer(address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L45)
	Event emitted after the call(s):
	- [Withdraw(owner,address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L46)

https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed734cfc1e769d16557b5a5716/contracts/src/Faucet.sol#L44-L47


 - [ ] ID-12
Reentrancy in [Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/3ddea6af7fce29ed7 [...]

2024-10-10 14:11 UTC, birozuru commented
# eBurger report

2024-10-10 14:12 UTC, birozuru commented
# Slither report
**THIS CHECKLIST IS NOT COMPLETE**. Use `--show-ignored-findings` to show all the results.
Summary
 - [arbitrary-send-eth](#arbitrary-send-eth) (2 results) (High)
 - [events-access](#events-access) (1 results) (Low)
 - [events-maths](#events-maths) (2 results) (Low)
 - [missing-zero-check](#missing-zero-check) (2 results) (Low)
 - [calls-loop](#calls-loop) (1 results) (Low)
 - [timestamp](#timestamp) (1 results) (Low)
 - [solc-version](#solc-version) (1 results) (Informational)
 - [reentrancy-unlimited-gas](#reentrancy-unlimited-gas) (3 results) (Informational)
 - [too-many-digits](#too-many-digits) (1 results) (Informational)
## arbitrary-send-eth
Impact: High
Confidence: Medium
 - [ ] ID-0
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L33-L42) sends eth to arbitrary user
	Dangerous calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-1
[Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Minting.sol#L45-L84) sends eth to arbitrary user
	Dangerous calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Minting.sol#L45-L84


## events-access
Impact: Low
Confidence: Medium
 - [ ] ID-2
[Faucet.setOwner(address)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L53-L55) should emit an event for: 
	- [owner = account](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L54) 

https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L53-L55


## events-maths
Impact: Low
Confidence: Medium
 - [ ] ID-3
[Faucet.setLockTime(uint256)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L61-L63) should emit an event for: 
	- [lockTime = amount * 60](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L62) 

https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L61-L63


 - [ ] ID-4
[Faucet.setWithdrawAmount(uint256)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L57-L59) should emit an event for: 
	- [withdrawAmount = amount](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L58) 

https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L57-L59


## missing-zero-check
Impact: Low
Confidence: Medium
 - [ ] ID-5
[Faucet.setOwner(address).account](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L53) lacks a zero-check on :
		- [owner = account](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L54)

https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L53


 - [ ] ID-6
[Minting.mint(address,uint256,uint32,bytes,address).refundAddress](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Minting.sol#L50) lacks a zero-check on :
		- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Minting.sol#L50


## calls-loop
Impact: Low
Confidence: Medium
 - [ ] ID-7
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L33-L42) has external calls inside a loop: [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L33-L42


## timestamp
Impact: Low
Confidence: Medium
 - [ ] ID-8
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L33-L42) uses timestamp for comparisons
	Dangerous comparisons:
	- [require(bool,string)(block.timestamp >= nextRequestAt[account],Insufficient time between requests)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L36)

https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L33-L42


## solc-version
Impact: Informational
Confidence: High
 - [ ] ID-9
Version constraint ^0.8.13 contains known severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)
	- VerbatimInvalidDeduplication
	- FullInlinerNonExpressionSplitArgumentEvaluationOrder
	- MissingSideEffectsOnSelectorAccess
	- StorageWriteRemovalBeforeConditionalTermination
	- AbiReencodingHeadOverflowWithStaticArrayCleanup
	- DirtyBytesArrayToStorage
	- InlineAssemblyMemorySideEffects
	- DataLocationChangeInInternalOverride
	- NestedCalldataArrayAbiReencodingSizeValidation.
It is used by:
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L2)
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Minting.sol#L2)

https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L2


## reentrancy-unlimited-gas
Impact: Informational
Confidence: Medium
 - [ ] ID-10
Reentrancy in [Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L33-L42):
	External calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L40)
	Event emitted after the call(s):
	- [Transfer(account,withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L41)

https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-11
Reentrancy in [Faucet.withdrawFunds()](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L44-L47):
	External calls:
	- [address(owner).transfer(address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L45)
	Event emitted after the call(s):
	- [Withdraw(owner,address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L46)

https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb40d13c314237ec99864ba163/contracts/src/Faucet.sol#L44-L47


 - [ ] ID-12
Reentrancy in [Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/30e617e2f229e9cb4 [...]

2024-10-10 16:55 UTC, birozuru commented
# eBurger report

2024-10-10 16:56 UTC, birozuru commented
# Slither report
**THIS CHECKLIST IS NOT COMPLETE**. Use `--show-ignored-findings` to show all the results.
Summary
 - [arbitrary-send-eth](#arbitrary-send-eth) (2 results) (High)
 - [events-access](#events-access) (1 results) (Low)
 - [events-maths](#events-maths) (2 results) (Low)
 - [missing-zero-check](#missing-zero-check) (2 results) (Low)
 - [calls-loop](#calls-loop) (1 results) (Low)
 - [timestamp](#timestamp) (1 results) (Low)
 - [solc-version](#solc-version) (1 results) (Informational)
 - [reentrancy-unlimited-gas](#reentrancy-unlimited-gas) (3 results) (Informational)
 - [too-many-digits](#too-many-digits) (1 results) (Informational)
## arbitrary-send-eth
Impact: High
Confidence: Medium
 - [ ] ID-0
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L33-L42) sends eth to arbitrary user
	Dangerous calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-1
[Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Minting.sol#L45-L84) sends eth to arbitrary user
	Dangerous calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Minting.sol#L45-L84


## events-access
Impact: Low
Confidence: Medium
 - [ ] ID-2
[Faucet.setOwner(address)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L53-L55) should emit an event for: 
	- [owner = account](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L54) 

https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L53-L55


## events-maths
Impact: Low
Confidence: Medium
 - [ ] ID-3
[Faucet.setLockTime(uint256)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L61-L63) should emit an event for: 
	- [lockTime = amount * 60](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L62) 

https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L61-L63


 - [ ] ID-4
[Faucet.setWithdrawAmount(uint256)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L57-L59) should emit an event for: 
	- [withdrawAmount = amount](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L58) 

https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L57-L59


## missing-zero-check
Impact: Low
Confidence: Medium
 - [ ] ID-5
[Faucet.setOwner(address).account](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L53) lacks a zero-check on :
		- [owner = account](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L54)

https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L53


 - [ ] ID-6
[Minting.mint(address,uint256,uint32,bytes,address).refundAddress](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Minting.sol#L50) lacks a zero-check on :
		- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Minting.sol#L50


## calls-loop
Impact: Low
Confidence: Medium
 - [ ] ID-7
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L33-L42) has external calls inside a loop: [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L33-L42


## timestamp
Impact: Low
Confidence: Medium
 - [ ] ID-8
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L33-L42) uses timestamp for comparisons
	Dangerous comparisons:
	- [require(bool,string)(block.timestamp >= nextRequestAt[account],Insufficient time between requests)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L36)

https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L33-L42


## solc-version
Impact: Informational
Confidence: High
 - [ ] ID-9
Version constraint ^0.8.13 contains known severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)
	- VerbatimInvalidDeduplication
	- FullInlinerNonExpressionSplitArgumentEvaluationOrder
	- MissingSideEffectsOnSelectorAccess
	- StorageWriteRemovalBeforeConditionalTermination
	- AbiReencodingHeadOverflowWithStaticArrayCleanup
	- DirtyBytesArrayToStorage
	- InlineAssemblyMemorySideEffects
	- DataLocationChangeInInternalOverride
	- NestedCalldataArrayAbiReencodingSizeValidation.
It is used by:
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L2)
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Minting.sol#L2)

https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L2


## reentrancy-unlimited-gas
Impact: Informational
Confidence: Medium
 - [ ] ID-10
Reentrancy in [Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L33-L42):
	External calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L40)
	Event emitted after the call(s):
	- [Transfer(account,withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L41)

https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-11
Reentrancy in [Faucet.withdrawFunds()](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L44-L47):
	External calls:
	- [address(owner).transfer(address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L45)
	Event emitted after the call(s):
	- [Withdraw(owner,address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L46)

https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3cf73aa62dc1a5e7941eb691/contracts/src/Faucet.sol#L44-L47


 - [ ] ID-12
Reentrancy in [Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/50d5f5e52f1ed84c3 [...]

2024-10-10 17:49 UTC, birozuru commented
# eBurger report

2024-10-10 17:49 UTC, birozuru commented
# Slither report
**THIS CHECKLIST IS NOT COMPLETE**. Use `--show-ignored-findings` to show all the results.
Summary
 - [arbitrary-send-eth](#arbitrary-send-eth) (2 results) (High)
 - [events-access](#events-access) (1 results) (Low)
 - [events-maths](#events-maths) (2 results) (Low)
 - [missing-zero-check](#missing-zero-check) (2 results) (Low)
 - [calls-loop](#calls-loop) (1 results) (Low)
 - [timestamp](#timestamp) (1 results) (Low)
 - [solc-version](#solc-version) (1 results) (Informational)
 - [reentrancy-unlimited-gas](#reentrancy-unlimited-gas) (3 results) (Informational)
 - [too-many-digits](#too-many-digits) (1 results) (Informational)
## arbitrary-send-eth
Impact: High
Confidence: Medium
 - [ ] ID-0
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L33-L42) sends eth to arbitrary user
	Dangerous calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-1
[Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Minting.sol#L45-L84) sends eth to arbitrary user
	Dangerous calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Minting.sol#L45-L84


## events-access
Impact: Low
Confidence: Medium
 - [ ] ID-2
[Faucet.setOwner(address)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L53-L55) should emit an event for: 
	- [owner = account](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L54) 

https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L53-L55


## events-maths
Impact: Low
Confidence: Medium
 - [ ] ID-3
[Faucet.setLockTime(uint256)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L61-L63) should emit an event for: 
	- [lockTime = amount * 60](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L62) 

https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L61-L63


 - [ ] ID-4
[Faucet.setWithdrawAmount(uint256)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L57-L59) should emit an event for: 
	- [withdrawAmount = amount](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L58) 

https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L57-L59


## missing-zero-check
Impact: Low
Confidence: Medium
 - [ ] ID-5
[Faucet.setOwner(address).account](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L53) lacks a zero-check on :
		- [owner = account](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L54)

https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L53


 - [ ] ID-6
[Minting.mint(address,uint256,uint32,bytes,address).refundAddress](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Minting.sol#L50) lacks a zero-check on :
		- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Minting.sol#L50


## calls-loop
Impact: Low
Confidence: Medium
 - [ ] ID-7
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L33-L42) has external calls inside a loop: [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L33-L42


## timestamp
Impact: Low
Confidence: Medium
 - [ ] ID-8
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L33-L42) uses timestamp for comparisons
	Dangerous comparisons:
	- [require(bool,string)(block.timestamp >= nextRequestAt[account],Insufficient time between requests)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L36)

https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L33-L42


## solc-version
Impact: Informational
Confidence: High
 - [ ] ID-9
Version constraint ^0.8.13 contains known severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)
	- VerbatimInvalidDeduplication
	- FullInlinerNonExpressionSplitArgumentEvaluationOrder
	- MissingSideEffectsOnSelectorAccess
	- StorageWriteRemovalBeforeConditionalTermination
	- AbiReencodingHeadOverflowWithStaticArrayCleanup
	- DirtyBytesArrayToStorage
	- InlineAssemblyMemorySideEffects
	- DataLocationChangeInInternalOverride
	- NestedCalldataArrayAbiReencodingSizeValidation.
It is used by:
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L2)
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Minting.sol#L2)

https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L2


## reentrancy-unlimited-gas
Impact: Informational
Confidence: Medium
 - [ ] ID-10
Reentrancy in [Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L33-L42):
	External calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L40)
	Event emitted after the call(s):
	- [Transfer(account,withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L41)

https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-11
Reentrancy in [Faucet.withdrawFunds()](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L44-L47):
	External calls:
	- [address(owner).transfer(address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L45)
	Event emitted after the call(s):
	- [Withdraw(owner,address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L46)

https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b3e56cdca50d64ddd5ea10a6/contracts/src/Faucet.sol#L44-L47


 - [ ] ID-12
Reentrancy in [Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/b7c5653c6d1164e6b [...]

2024-10-10 19:16 UTC, arminsabouri submitted a review, later dismissed
tACK
Test results locally: 
Exit codes for each test:
dkg_flow: 0
utxo_commitment: 0
many_inputs_signing: 0

2024-10-10 20:34 UTC, birozuru commented
# eBurger report

2024-10-10 21:03 UTC, birozuru commented
# eBurger report

2024-10-10 21:03 UTC, birozuru commented
# Slither report
**THIS CHECKLIST IS NOT COMPLETE**. Use `--show-ignored-findings` to show all the results.
Summary
 - [arbitrary-send-eth](#arbitrary-send-eth) (2 results) (High)
 - [events-access](#events-access) (1 results) (Low)
 - [events-maths](#events-maths) (2 results) (Low)
 - [missing-zero-check](#missing-zero-check) (2 results) (Low)
 - [calls-loop](#calls-loop) (1 results) (Low)
 - [timestamp](#timestamp) (1 results) (Low)
 - [solc-version](#solc-version) (1 results) (Informational)
 - [reentrancy-unlimited-gas](#reentrancy-unlimited-gas) (3 results) (Informational)
 - [too-many-digits](#too-many-digits) (1 results) (Informational)
## arbitrary-send-eth
Impact: High
Confidence: Medium
 - [ ] ID-0
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L33-L42) sends eth to arbitrary user
	Dangerous calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-1
[Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Minting.sol#L45-L84) sends eth to arbitrary user
	Dangerous calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Minting.sol#L45-L84


## events-access
Impact: Low
Confidence: Medium
 - [ ] ID-2
[Faucet.setOwner(address)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L53-L55) should emit an event for: 
	- [owner = account](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L54) 

https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L53-L55


## events-maths
Impact: Low
Confidence: Medium
 - [ ] ID-3
[Faucet.setLockTime(uint256)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L61-L63) should emit an event for: 
	- [lockTime = amount * 60](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L62) 

https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L61-L63


 - [ ] ID-4
[Faucet.setWithdrawAmount(uint256)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L57-L59) should emit an event for: 
	- [withdrawAmount = amount](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L58) 

https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L57-L59


## missing-zero-check
Impact: Low
Confidence: Medium
 - [ ] ID-5
[Faucet.setOwner(address).account](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L53) lacks a zero-check on :
		- [owner = account](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L54)

https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L53


 - [ ] ID-6
[Minting.mint(address,uint256,uint32,bytes,address).refundAddress](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Minting.sol#L50) lacks a zero-check on :
		- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Minting.sol#L50


## calls-loop
Impact: Low
Confidence: Medium
 - [ ] ID-7
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L33-L42) has external calls inside a loop: [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L33-L42


## timestamp
Impact: Low
Confidence: Medium
 - [ ] ID-8
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L33-L42) uses timestamp for comparisons
	Dangerous comparisons:
	- [require(bool,string)(block.timestamp >= nextRequestAt[account],Insufficient time between requests)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L36)

https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L33-L42


## solc-version
Impact: Informational
Confidence: High
 - [ ] ID-9
Version constraint ^0.8.13 contains known severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)
	- VerbatimInvalidDeduplication
	- FullInlinerNonExpressionSplitArgumentEvaluationOrder
	- MissingSideEffectsOnSelectorAccess
	- StorageWriteRemovalBeforeConditionalTermination
	- AbiReencodingHeadOverflowWithStaticArrayCleanup
	- DirtyBytesArrayToStorage
	- InlineAssemblyMemorySideEffects
	- DataLocationChangeInInternalOverride
	- NestedCalldataArrayAbiReencodingSizeValidation.
It is used by:
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L2)
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Minting.sol#L2)

https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L2


## reentrancy-unlimited-gas
Impact: Informational
Confidence: Medium
 - [ ] ID-10
Reentrancy in [Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L33-L42):
	External calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L40)
	Event emitted after the call(s):
	- [Transfer(account,withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L41)

https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-11
Reentrancy in [Faucet.withdrawFunds()](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L44-L47):
	External calls:
	- [address(owner).transfer(address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L45)
	Event emitted after the call(s):
	- [Withdraw(owner,address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L46)

https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf33078370242a3e73d0bcd166ac78f/contracts/src/Faucet.sol#L44-L47


 - [ ] ID-12
Reentrancy in [Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/5c0f07f52cf330783 [...]

2024-10-11 13:22 UTC, arminsabouri submitted a review, later dismissed
tACK
Exit codes for each test:
dkg_flow: 0
utxo_commitment: 0
many_inputs_signing: 0

2024-10-11 15:47 UTC, scottmillner approved these changes

2024-10-11 20:35 UTC, merged