chore:Added local_setup.sh to automates and spin the nodes
botanix-labs/Macbeth pull request #446
Opened 2024-10-16 15:53 UTC by nagarajm87

* Added `local_script.sh` to spin all the nodes.
* Updated `Readme` for running the script.

2024-10-16 18:16 UTC, arminsabouri requested changes
Im glad we finally got around to doing something like this. This is super impressive. I had a couple questions and some requests for changes

2024-10-16 18:16 UTC, arminsabouri commented on binaries/bitcoin-tx
Do we need these are bitcoin binaries. Seems like we really just need bitcoind

2024-10-16 18:16 UTC, arminsabouri commented on local_setup.sh
> +    ./binaries/bitcoin-cli -rpcport=18443 -rpcuser=test123 -rpcpassword=test123 loadwallet "mywallet"
Could probably use the env vars  
-rpcuser=$RPC_USER -rpcpassword=$RPC_PASS

2024-10-16 18:16 UTC, arminsabouri commented on local_setup.sh
> +    sleep 60
Do we need to sleep for a minute here? esp since the last command is running the background

2024-10-16 18:16 UTC, arminsabouri commented on local_setup.sh
> +    sleep 60
Same thing here

2024-10-16 18:16 UTC, arminsabouri commented on local_setup.sh
> +    ./binaries/bitcoin-cli -regtest -rpcport=18443 -rpcuser=test123 -rpcpassword=test123 stop
Could also send sigint and not keeo a bitcoin-cli binary.

2024-10-16 18:16 UTC, arminsabouri commented on local_setup.sh
> +
Do we also need to kill the poa nodes?

2024-10-16 18:16 UTC, arminsabouri commented on local_setup.sh
> +HOME_DIR="$HOME/develop"
Maybe we can create the temp dirs in /tmp or somehere in the cwd (and the gitignore it)  ?

2024-10-17 07:15 UTC, nagarajm87 commented on binaries/bitcoin-tx
I kept the other bitcoin binaries to create wallet and generate some blocks.

2024-10-17 07:15 UTC, nagarajm87 commented on local_setup.sh
> +    ./binaries/bitcoin-cli -rpcport=18443 -rpcuser=test123 -rpcpassword=test123 loadwallet "mywallet"
will update this :)

2024-10-17 07:19 UTC, nagarajm87 commented on local_setup.sh
> +    sleep 60
I added a one-minute delay, so when running make start-btc-server-1, it starts with the compilation process, then proceeds to the launch phase.

2024-10-17 07:20 UTC, nagarajm87 commented on local_setup.sh
> +
will update it :)

2024-10-17 09:02 UTC, rwlockbg commented on binaries/bitcoin-tx
Naga, lets not include binaries here - this will blow up the pull duration, plus it sonly for ubuntu / macos. If we want to have the binaries, we need to publish them for all platforms. If you however want them , there is a lfg module for gitub for handling large files.

2024-10-17 09:04 UTC, rwlockbg commented on local_setup.sh
> +HOME_DIR="$HOME/develop"
agree, let that be a new  directory under root

2024-10-17 09:04 UTC, rwlockbg commented on local_setup.sh
> +HOME_DIR="$HOME/develop"
a temp one

2024-10-17 09:04 UTC, rwlockbg commented on local_setup.sh
> +    sleep 60
the btc server needs at most 10 secs or so to boot up, its pretty fast.

2024-10-17 14:08 UTC, arminsabouri commented on local_setup.sh
> +   ./binaries/bitcoind -datadir="$BITCOIN_NODE_DIR" -conf="$BITCOIN_NODE_DIR/bitcoin.conf" &
Could also consider passing the paths to the bitcoind and comet binaries.

2024-10-18 14:00 UTC, nagarajm87 commented on binaries/bitcoin-tx
I have removed the binaries, user need to provide the path

2024-10-18 14:02 UTC, nagarajm87 commented on local_setup.sh
> +    sleep 60
I have updated, sleep :)

2024-10-18 14:04 UTC, nagarajm87 commented on local_setup.sh
> +HOME_DIR="$HOME/develop"
updated created temp folder :)

2024-10-18 14:04 UTC, nagarajm87 commented on local_setup.sh
> +   ./binaries/bitcoind -datadir="$BITCOIN_NODE_DIR" -conf="$BITCOIN_NODE_DIR/bitcoin.conf" &
done :)

2024-10-18 14:04 UTC, nagarajm87 commented on local_setup.sh
> +    sleep 60
resolved :)

2024-10-21 07:26 UTC, rwlockbg submitted a review, later dismissed
Looks good ! In the feature it would be nice to add some extra scripting for pre-configuring the nodes connectivity in both genesis and config.tomls for each cometbft as this would help the dev enormously.

2024-10-22 11:56 UTC, arminsabouri commented
@nagarajm87 can you rebase this on top of the main branch?

2024-10-22 12:30 UTC, arminsabouri submitted a review, later dismissed
UTack! Just one question. Otherwise good to go

2024-10-22 12:30 UTC, arminsabouri commented on local_setup.sh
> +    Check if the directories already exist
Should this be comment?

2024-10-23 13:44 UTC, scottmillner submitted a review, later dismissed

2024-10-23 13:46 UTC, scottmillner commented
looks good! id say get the `lint/crate-checks` job passing then should be good to merge!

2024-10-23 13:53 UTC, nagarajm87 commented on local_setup.sh
> +    Check if the directories already exist
will update it :)

2024-10-24 13:40 UTC, scottmillner commented
for the last commit `rebased latest`:
- when rebasing, just rebase and force push so no new commit is added
- i see there's a small change in there (a comment): if you still need that change just `git reset --soft HEAD~1`, add that change to the previous changes and force push

2024-10-28 10:48 UTC, rwlockbg approved these changes

2024-10-28 14:19 UTC, merged