feat(repo): Added implementation for fed-utils for `get_balance` and `sweep_balance`
botanix-labs/Macbeth pull request #455
Opened 2024-10-22 12:13 UTC by nagarajm87

* Added implementation `client` and `rpc_method`.
* Added implementation `get_balance` and `sweep_balance`.
* updated `utils-cli` with new commands.
* Handling `error` crate. 
* Added test cases.
* Added method to support config.toml.
* Added method for deserialize private_key_validator.json

2024-10-23 20:20 UTC, scottmillner commented
looking good so far! will review again when not draft

2024-10-24 11:04 UTC, nagarajm87 commented
1. I have kept `wallet.rs` bcoz it contains some test cases, which was written by @scottmillner , once its reviewed, if everything is good, will delete it. 
2. For `sweep_balance` do we need to add `amount` params ? 
3. I have used chain_id `3636` to do transactions, its working for `sweep_balance`

2024-10-24 14:39 UTC, rwlockbg commented
@nagarajm87 Can you pls rebase as there is 1 conflict ?

2024-10-25 02:20 UTC, scottmillner commented
~~do you mind adding a README that gives a general description of how the wallet is used?~~
~~i realize i forgot to do that, sorry~~

~~for example, instead of the user saving a config, the user can set env vars~~

RESOLVED

2024-10-25 02:23 UTC, scottmillner commented
~~just a general question:~~
~~how did you decide on env vars over the user setting a config that will be saved?~~

~~it looks like the only env var available to the wallet is `SECRET_KEY_PATH`~~
~~which means the user has to pass in `chain_id`, `receiver_address` every time? is that correct?~~

~~not saying either approach is better just want to get group consensus on what we think node operators will prefer~~
@0xBEEFCAF3 @rwlockbg 

RESOLVED

2024-10-25 02:27 UTC, scottmillner commented on bin/federation-utils/src/client.rs
> +            provider_url: url.to_string(),
this is hardcoded to 1 which is ethereum mainnet 

the user could use this wallet with any evm compatible chain but imagine it will be used with a chain running our codebase

bc of that i'd prefer not to hardcode the chain id or we could default to ours

thoughts?

2024-10-25 02:40 UTC, scottmillner commented on bin/federation-utils/src/cli/mod.rs
>  #[command(name = "Wallet CLI")]
do you think we should allow the user to set any additional env vars besides `SECRET_KEY_PATH`?

2024-10-25 09:54 UTC, rwlockbg submitted a review, later dismissed

2024-10-25 10:00 UTC, nagarajm87 commented
> just a general question: how did you decide on env vars over the user setting a config that will be saved?
> 
> it looks like the only env var available to the wallet is `SECRET_KEY_PATH` which means the user has to pass in `chain_id`, `receiver_address` every time? is that correct?
> 
> not saying either approach is better just want to get group consensus on what we think node operators will prefer @0xBEEFCAF3 @rwlockbg

Regarding the environment variable, the user or node operator can set it directly, or the node operator can provide the SECRET_KEY_PATH manually—either option works. Alternatively, we could create a config file and load the required data from there, and I’m open to suggestions on which approach would be best.

2024-10-25 10:03 UTC, nagarajm87 commented on bin/federation-utils/src/cli/mod.rs
>  #[command(name = "Wallet CLI")]
user can pass, `chain_id`, `privded_url`, `address`, & `SECRET_KEY_PATH`,  one thing need to confirmation regarding `amount` for sweep_balance.

2024-10-25 10:59 UTC, nagarajm87 commented on bin/federation-utils/src/client.rs
> +            provider_url: url.to_string(),
@scottmillner  thank you :) I have updated it.

2024-10-25 13:45 UTC, scottmillner commented on bin/federation-utils/src/cli/mod.rs
>  #[command(name = "Wallet CLI")]
i mean do we always want to make the user pass those values?
from what i could see, there is only one env var being used, is that correct?

2024-10-25 13:48 UTC, scottmillner commented
> > just a general question: how did you decide on env vars over the user setting a config that will be saved?
> > it looks like the only env var available to the wallet is `SECRET_KEY_PATH` which means the user has to pass in `chain_id`, `receiver_address` every time? is that correct?
> > not saying either approach is better just want to get group consensus on what we think node operators will prefer @0xBEEFCAF3 @rwlockbg
> 
> Regarding the environment variable, the user or node operator can set it directly, or the node operator can provide the SECRET_KEY_PATH manually—either option works. Alternatively, we could create a config file and load the required data from there, and I’m open to suggestions on which approach would be best.

~~curious on which option you think node operators prefer?~~

RESOLVED

2024-10-28 10:43 UTC, rwlockbg commented on bin/federation-utils/README.md
> +  -c, --chain-id <CHAIN_ID>          Chain ID (default is 1) [default: 11155111]
@nagarajm87 I think this should be 3636 (our chain Id)

2024-10-28 10:43 UTC, rwlockbg commented on bin/federation-utils/src/cli/mod.rs
> +    #[arg(short, long, default_value_t = 11155111)]
again, I think this should be 3636 (our chain  id)

2024-10-28 10:43 UTC, rwlockbg commented on bin/federation-utils/src/client.rs
> +        let runtime = tokio::runtime::Builder::new_current_thread()
Question: why do we always create a new runtime for these commands ? The runtime could  be initialized on the main method if needed. First, we dont need all features of it (enable_all()) and I also think we dont need tihs to be inside the funcs. How about we move it to main. Putting #[tokio::main] implicitly starts the runtime

2024-10-28 10:43 UTC, rwlockbg commented on bin/federation-utils/src/main.rs
> +            let bal = handle_get_balance(get_balance, &cli.provider_url, cli.chain_id)
if we add #[tokio::main], the cli utils could directly call async .await here and we could drop the runtime we are creating everywhere. Creating a runtime is a heavy operation and is not needed. Is there a reason why we want our cli to be fully sync ?

2024-10-28 10:47 UTC, rwlockbg commented
> > > just a general question: how did you decide on env vars over the user setting a config that will be saved?
> > > it looks like the only env var available to the wallet is `SECRET_KEY_PATH` which means the user has to pass in `chain_id`, `receiver_address` every time? is that correct?
> > > not saying either approach is better just want to get group consensus on what we think node operators will prefer @0xBEEFCAF3 @rwlockbg
> > 
> > 
> > Regarding the environment variable, the user or node operator can set it directly, or the node operator can provide the SECRET_KEY_PATH manually—either option works. Alternatively, we could create a config file and load the required data from there, and I’m open to suggestions on which approach would be best.
> 
> curious on which option you think node operators prefer?

I believe having both might be confusing. Best is to have a .toml file that contains all info needed and we just pass over the cli a path where the file is located. This is how geth and all the others work. Of course, if need be, we could have the args also added, but that  might be too much. Adding ENVs on top of that is an overkill.

2024-10-28 14:57 UTC, scottmillner commented on bin/federation-utils/src/cli/mod.rs
>  #[command(name = "Wallet CLI")]
for `sweep_balance`: i think it'd be nice to allow an `amount` param that is an Option<> so they can sweep less than the full balance if they want

if they don't pass `amount`, the full balance will be sweeped

2024-10-30 14:05 UTC, arminsabouri commented
@nagarajm87 to squash relevant commits

2024-10-30 23:50 UTC, scottmillner commented on bin/federation-utils/src/cli/mod.rs
> +#[derive(Parser, Debug)]
should we get remove `env = "SECRET_KEY_PATH"` since we have a config now?

2024-10-30 23:54 UTC, scottmillner commented on bin/federation-utils/src/cli/mod.rs
> +    /// Init create config.toml in home directory.
i think we should add a GetConfig command so the user can see what their config values are? thoughts?

2024-10-30 23:57 UTC, scottmillner commented on bin/federation-utils/src/main.rs
> -            )?;
let's get rid of this `unwrap` and handle the case where the user hasn't passed in the `config_path`

as is, this will break if the user doesn't pass in `config_path` which is an Option
if you run `cargo run --package federation-utils-cli --bin utils init`

2024-10-31 00:09 UTC, scottmillner commented on bin/federation-utils/src/handler.rs
> +        "tendermint/PrivKeyEd25519" => {
let's error here instead since a user should only be using secp curve in comet

2024-10-31 00:29 UTC, scottmillner commented on bin/federation-utils/src/config.rs
> +
looks like if i use the `init` command, i will get default values only
i have no way to override those values unless i manually create the `config.toml` file, is that correct?

if so, and you don't think we should let the user override those values through a command, can you update the README to tell the user they have to manually create that file if they don't want the default values

2024-10-31 06:11 UTC, nagarajm87 commented on bin/federation-utils/src/config.rs
> +
`init` command which creates `config.toml` file with default values  and user has to update  `config.toml` with theirs address or `seceret_path`  all values will be loaded from config.toml or else user can pass via cli command.

2024-10-31 06:13 UTC, nagarajm87 commented on bin/federation-utils/src/handler.rs
> +        "tendermint/PrivKeyEd25519" => {
As we discussed this in yesterday meeting, will update it, thanks :)

2024-10-31 06:14 UTC, nagarajm87 commented on bin/federation-utils/src/cli/mod.rs
> +#[derive(Parser, Debug)]
yes, we will loading via config.toml or by cli command

2024-10-31 14:07 UTC, arminsabouri commented
Remaining TODOs 
* Squash relevant commits
* Update fed utils README

2024-10-31 17:13 UTC, scottmillner commented
once the TODOs Armin listed are done, it's good to go on my end and will ✅

2024-10-31 21:04 UTC, arminsabouri requested changes

2024-10-31 21:04 UTC, arminsabouri commented on bin/federation-utils/Cargo.toml
> +ed25519-dalek = { version = "2.1.1", features = ["pkcs8"] }
Do we need this dependency?

2024-10-31 21:04 UTC, arminsabouri commented on bin/federation-utils/README.md
> +  ../../target/debug/utils -c 36363 -u http://localhost:8545  get-balance -a <your address>
Assuming this this chain id?

```suggestion
  ../../target/debug/utils -c 3636 -u http://localhost:8545  get-balance -a <your address>
```

2024-10-31 21:04 UTC, arminsabouri commented on bin/federation-utils/README.md
> +from_address = ""                  // This addrress is used for get-balance.
Small typo here
"address"

2024-10-31 21:04 UTC, arminsabouri commented on bin/federation-utils/src/cli/mod.rs
> +    pub address: Option<String>,
should this take an argument? I think we are always checking the balance of the federation wallet. Not any address

2024-10-31 21:04 UTC, arminsabouri commented on bin/federation-utils/src/cli/mod.rs
> +    pub amount: Option<String>,
How can these be optional? Are there defaults?

2024-10-31 21:04 UTC, arminsabouri commented on bin/federation-utils/src/client.rs
> +        let wallet: LocalWallet = match &self.secret_key {
The client struct should probably not get initialized if there is no secret key. And then you dont need these match statments

2024-10-31 21:04 UTC, arminsabouri commented on bin/federation-utils/src/client.rs
> +        }
I'm not sure I understand this check. We should always expect a set of valid chain ids OR just pull it from provider when we are init'ing the client OR pass in a is-testnet flag that toggles between testnet and mainnet chain id

2024-10-31 21:04 UTC, arminsabouri commented on bin/federation-utils/src/client.rs
> +                amt
Let the EVM tell you there is insufficient balance. You dont need to do this.

2024-10-31 21:04 UTC, arminsabouri commented on bin/federation-utils/src/client.rs
> +        let tx: TypedTransaction = TransactionRequest::new().to(to).from(from_address).into();
Ethers has much easier interface for sending from a local wallet 
See [this example](https://docs.infura.io/tutorials/ethereum/send-a-transaction/use-rust)

2024-10-31 21:04 UTC, arminsabouri commented on bin/federation-utils/src/client.rs
> +    pub address: Option<Address>,
The address can always be generated from the sk. 
`address = keccak256(sk * G)` 
Let ethers do this

2024-10-31 21:04 UTC, arminsabouri commented on bin/federation-utils/src/client.rs
> +    pub receiver_address: Option<Address>,
Why are we storing this in a client struct? 
perhaps the client should just store the neccecary data needed to send txs, view balance, etc... and the methods such as `sweep_balance` just take in reciever_address as a param.

2024-10-31 21:04 UTC, arminsabouri commented on bin/federation-utils/src/config.rs
> +            amount: Some("10000000000000000".to_string()),
Defaults here are scary. These values should probably not be in config. 
Also do we need and/or use amount anywhere? we should be just sweeping

2024-10-31 21:04 UTC, arminsabouri commented on bin/federation-utils/src/handler.rs
> +/// Deseialise Ed25519 or Secp256k1 private key and return stirng.
Must be secp256k1

2024-10-31 21:04 UTC, arminsabouri commented on bin/federation-utils/src/handler.rs
> +/// Deseialise Ed25519 or Secp256k1 private key and return stirng.
panic otherwise

2024-10-31 21:04 UTC, arminsabouri commented on bin/federation-utils/src/main.rs
> +            let amount = U256::from_dec_str(&amount_str).expect("Failed to parse decimal to U256");
Same comment about amount as above. Since we are sweeping do we need to pass in amount?

2024-11-01 08:09 UTC, nagarajm87 commented on bin/federation-utils/README.md
> +  ../../target/debug/utils -c 36363 -u http://localhost:8545  get-balance -a <your address>
yes, its `chain_id`, we can either use as `-c` or `-chain-id` its already mentioned in readme.

2024-11-01 08:10 UTC, nagarajm87 commented on bin/federation-utils/Cargo.toml
> +ed25519-dalek = { version = "2.1.1", features = ["pkcs8"] }
I have removed, not push yet, after disscussion yesterday meeting

2024-11-01 08:18 UTC, nagarajm87 commented on bin/federation-utils/src/handler.rs
> +/// Deseialise Ed25519 or Secp256k1 private key and return stirng.
yep, it will return error mentioning `key_type not supported`

2024-11-01 08:24 UTC, nagarajm87 commented on bin/federation-utils/src/client.rs
> +                amt
balance value which I receive from `rpc_call` from `evm`, then I am comparing it with amount passed by the user.

2024-11-01 09:05 UTC, nagarajm87 commented on bin/federation-utils/src/cli/mod.rs
> +    pub address: Option<String>,
need to discuss :)

2024-11-01 09:06 UTC, nagarajm87 commented on bin/federation-utils/src/client.rs
> +    pub receiver_address: Option<Address>,
oops, i already removed it, not pushed yet. will update it

2024-11-01 09:07 UTC, nagarajm87 commented on bin/federation-utils/src/main.rs
> +            let amount = U256::from_dec_str(&amount_str).expect("Failed to parse decimal to U256");
need to discuss, amount params, allowing the user to either send their entire balance or specify a desired amount.

2024-11-01 10:08 UTC, nagarajm87 commented on bin/federation-utils/src/cli/mod.rs
> +    pub amount: Option<String>,
These fields are optional in the CLI because they can be loaded from the config.toml file, if not provided directly as command-line arguments.

2024-11-01 12:14 UTC, arminsabouri commented on bin/federation-utils/src/main.rs
> +            let amount = U256::from_dec_str(&amount_str).expect("Failed to parse decimal to U256");
The way we have spec'd this out was to send the entire balance

2024-11-04 07:49 UTC, rwlockbg submitted a review, later dismissed

2024-11-04 14:02 UTC, rwlockbg commented
@nagarajm87 need to rebase the conflicts again, sorry

2024-11-04 14:24 UTC, arminsabouri commented
@nagarajm87 Can you also squash the commits. Thanks

2024-11-05 02:41 UTC, arminsabouri reviewed
Great progress! Looks like some code spell and other ci jobs failing. I'll let @scottmillner do another pass as well

2024-11-05 02:41 UTC, arminsabouri commented on bin/federation-utils/src/client.rs
> +    async fn get_balance(&self, sceret_key: String) -> Result<U256, WalletError>;
Secret key typo

2024-11-05 02:41 UTC, arminsabouri commented on bin/federation-utils/src/client.rs
> +    pub chain_id: u64,
Can we pull this from the provider or is there a another reason to pass this in

2024-11-05 07:57 UTC, nagarajm87 commented on bin/federation-utils/src/client.rs
> +    pub chain_id: u64,
last time as discussed to keep it, `chain id` can be set via config or cli or can be fetch from provider, handling all cases :)

2024-11-05 12:09 UTC, arminsabouri commented on bin/federation-utils/src/client.rs
> +    pub chain_id: u64,
but why?

2024-11-05 16:24 UTC, scottmillner commented on bin/federation-utils/README.md
> +```bash
is --chain-id 36363 intentional or did you mean 3636?

2024-11-05 16:26 UTC, nagarajm87 commented on bin/federation-utils/README.md
> +```bash
its 3636, my bad

2024-11-05 16:36 UTC, scottmillner commented on bin/federation-utils/README.md
> +```bash
all good

im gonna ✅ and if you update the readme, ill ✅ again

nice job!!

2024-11-05 16:36 UTC, scottmillner submitted a review, later dismissed

2024-11-06 09:05 UTC, rwlockbg approved these changes

2024-11-07 15:11 UTC, scottmillner approved these changes

2024-11-07 15:20 UTC, arminsabouri approved these changes

2024-11-07 15:22 UTC, merged