feature(735-handle-missing-federation-member-pk): handling  federation toml missing public keys
botanix-labs/Macbeth pull request #473
Opened 2024-11-06 14:26 UTC by nagarajm87

* handling  `federation.toml` missing public keys.

2024-11-06 14:41 UTC, arminsabouri requested changes

2024-11-06 14:41 UTC, arminsabouri commented on bin/reth/src/commands/poa/mod.rs
> +                    Default::default()
Should we error out of the program here? If a node is saying they are a fed node but their key is not found maybe we should just exit

2024-11-07 16:48 UTC, scottmillner commented on bin/reth/src/commands/poa/mod.rs
> +                return Err(eyre::eyre!(
`try_new` can fail for other reasons besides `missing federation public keys`

2024-11-08 08:14 UTC, rwlockbg commented on crates/node/core/src/args/federation_args.rs
> +            .as_ref() // Get a reference to the inner Vec if it exists
Can you remove this comment please ?

2024-11-08 08:14 UTC, rwlockbg commented on crates/node/core/src/args/federation_args.rs
> +                            .expect("Invalid hex string for PublicKey");
Can we not expect here, but rather collect all Result<PubKey, Error> and check i any are Err typed and then create aan Error message just to know the exact reason ?

2024-11-08 08:14 UTC, rwlockbg commented on crates/node/core/src/args/federation_args.rs
> +                        let soc_addr = member.socket_addr.parse::<SocketAddr>().unwrap();
same here - to avoid the unwraps somwhow

2024-11-08 08:14 UTC, rwlockbg commented on bin/reth/src/commands/poa/mod.rs
> +                return Err(eyre::eyre!(
agree, maybe you can check the err type (if possible) and then react to it ?

2024-11-08 17:11 UTC, arminsabouri commented on bin/reth/src/commands/poa/mod.rs
> +                return Err(eyre::eyre!(
+1

2024-11-08 17:11 UTC, arminsabouri requested changes

2024-11-08 17:11 UTC, arminsabouri commented on crates/node/core/src/args/federation_args.rs
> +    pub federation_member_public_key: Option<Vec<FedMemberPubKey>>,
I dont think this should ever be optional

2024-11-11 15:21 UTC, rwlockbg submitted a review, later dismissed

2024-11-12 14:47 UTC, arminsabouri requested changes

2024-11-12 14:47 UTC, arminsabouri commented on bin/reth/src/commands/poa/mod.rs
> +                    eyre::eyre!("Federation public keys not found")
key* singular not plural. 

Maybe a better error message is "Your public key could not be found in the list of federation public keys"

2024-11-12 17:20 UTC, arminsabouri approved these changes

2024-11-12 17:21 UTC, merged