fix(abci): fixed retain height in abci commit function #814
botanix-labs/Macbeth pull request #502
Opened 2024-11-20 09:52 UTC by nagarajm87

*  fixed retain height in abci commit function.

2024-11-20 13:22 UTC, arminsabouri requested changes

2024-11-20 13:22 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                return ResponseCommit { retain_height: latest_block_height };
This doenst seem right.
The documentation reads: 
> Blocks below this height may be removed. Defaults to 0 (retain all).

If latest block height is anything besides 0 we will prune historical blocks

2024-12-02 14:45 UTC, scottmillner submitted a review, later dismissed

2024-12-02 14:59 UTC, rwlockbg approved these changes

2024-12-02 15:02 UTC, scottmillner approved these changes

2024-12-02 15:02 UTC, merged