feat(repo): Added state sync impl
botanix-labs/Macbeth pull request #506
Opened 2024-12-03 10:12 UTC by rwlockbg

2024-12-23 15:46 UTC, arminsabouri reviewed
first part of the review on abci stuff

2024-12-23 15:46 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                        hash: prost::bytes::Bytes::copy_from_slice(&snapshot.block_hash().0),
should this be a hash of the snapshot itself? is there benefit for having this hash be the block hash?

2024-12-23 15:46 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +            if snapshot.hash == prost::bytes::Bytes::default() {
since the snapshot hash is a block hash shoudl we check if we already have this block?
and if we decide that the snapshot hash should be some unique hash that reps the snapshot we should also check if this snapshot hash exists in our db

2024-12-23 15:46 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +
Should we be checking for valid chunk bytes? empty bytes? Is there any structure to them?

2024-12-23 15:46 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +        // has alredy run
alredy -> already 
typo

2024-12-23 15:46 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +            // Should we update the fork choice?
rm comment.

2024-12-23 15:46 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +    }
Is it possible for multiple apply_snapshot_chunk to be processed in parallel? I dont think it is but I sitll want to surface this question. Do we need to apply a state sync lock?

2024-12-24 15:42 UTC, scottmillner commented on crates/storage/db/src/tables/mod.rs
> +    /// Stores the uncles/ommers of the block.
nit: comment needs to be updated

2024-12-24 16:02 UTC, scottmillner commented on crates/consensus/authority/src/comet_bft/abci.rs
> +        // set the last applied chunk index
how are we enforcing that chunks are added in order?
above i see we check that the `last_applied_chunk_index` is not greater than the `request.index` but we don't check that it's sequential?

for example: if last chunk is 100, shouldn't the request.index have to be 101?

2024-12-24 17:01 UTC, scottmillner commented on crates/consensus/authority/src/snapshot_manager.rs
> +                    // check if we need to delete older snapshots (Retention policy)
eventually as the chain grows and we drop snapshots, this means a peer needing to sync the whole chain or from an old enough block, couldn't use state sync

i guess they could just sync using the CASS data we provide, right?

2024-12-24 19:28 UTC, scottmillner commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                client.latest_header().expect("should have latest").expect("should have header");
i have a similar comment below about applying chunks

for `snapshot.height` we only enforce that it's greater then our latest header

- don't we want to sync snapshots sequentially? or can we process them out of order? 

- or does comet always give us snapshots sequentially based on height?

what happens if:
- snapshot.height = 10 comes in
- then snapshot.height = 8
- and our latest header height is 7

2024-12-24 19:39 UTC, scottmillner commented on crates/consensus/authority/src/snapshot_manager.rs
> +                        Some((last_snapshot_id, last_snapshot_height)) => {
do we need to enforce we are creating snapshots in sequential order?
what if `last_snapshot_height` = 5 and `sealed.block.number` = 12

not sure how this could happen but wanted to mention

2024-12-24 19:45 UTC, scottmillner commented
did my first pass through and left some comments

wanted to say awesome work man!! 🔥 💪

2024-12-30 09:00 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +
This is what commet is sending is:

```
pub struct Snapshot {
    /// The height at which the snapshot was taken
    #[prost(uint64, tag = "1")]
    pub height: u64,
    /// The application-specific snapshot format
    #[prost(uint32, tag = "2")]
    pub format: u32,
    /// Number of chunks in the snapshot
    #[prost(uint32, tag = "3")]
    pub chunks: u32,
    /// Arbitrary snapshot hash, equal only if identical
    #[prost(bytes = "bytes", tag = "4")]
    pub hash: ::prost::bytes::Bytes,
    /// Arbitrary application metadata
    #[prost(bytes = "bytes", tag = "5")]
    pub metadata: ::prost::bytes::Bytes,
}
```

What we can check for are height, format, chunks count, hash and metadata. I am already checking them all, metadata is something we need to define as a team and put some structure into it.  Once we have it, I would check that it follows the expected structure and values are correct.

2024-12-30 09:14 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +        // has alredy run
fixed

2024-12-30 09:14 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +            // Should we update the fork choice?
done

2024-12-30 09:15 UTC, rwlockbg commented on crates/storage/db/src/tables/mod.rs
> +    /// Stores the uncles/ommers of the block.
done, thanks.

2024-12-30 09:26 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +        // set the last applied chunk index
yep, I have added this condition now

2024-12-30 09:28 UTC, rwlockbg commented on crates/consensus/authority/src/snapshot_manager.rs
> +                    // check if we need to delete older snapshots (Retention policy)
Well, not sure - I believe this is something we need to discuss internally. I believe the state sync is usually for catching up with a couple of tausend blocks, whereas syncing from genesis smells like the node operator downloads and applies a snapshot using the CASS data. Sending gigabytes of data over comet would result in bad experience, I guarantee.  @0xBEEFCAF3 @SatwikPrabhu ideas ?

2024-12-30 09:30 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                client.latest_header().expect("should have latest").expect("should have header");
I am running tests to find out how comet actually sends the data to us. Once I know better, will update here.

2024-12-30 09:42 UTC, rwlockbg commented on crates/consensus/authority/src/snapshot_manager.rs
> +                        Some((last_snapshot_id, last_snapshot_height)) => {
Sure. The idea behind the snapshot manager is that it receives over hte abci driver blocks in the order they are being added to the consensus by commet  meaning 1, 2, 3, ... N. I am fully relying on comet here and I believe that the moment it calls "commit" on the rpc side the commited block will be a sequential one, following the previous one. Correct me if I am mistaken here ! If that is the case the blocks will go in exactly the same order as they are commited as we send them over a channel from abci over to the snapshot manager. Also, as discussed, snapshot height = block num at which the snapshot was taken. Further down in the manager, if there is space and we add a block and all of its txs to the latest snapshot, the height of the snapshot goes up and matches the height of the sealed.block.number that was just passed over the channel.

2024-12-30 09:43 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +    }
ITs not quite clear to me from the docs how it works. Building tests and int. tests to confirm the order the chunks are being passed. Nevertheless, putting a sync lock is not a bad idea as this is not a critical part of the protocol where speed and latency matter. I will add one for sure.

2024-12-31 13:36 UTC, SatwikPrabhu commented on crates/consensus/authority/src/comet_bft/abci.rs
> +    REJECT_SENDER = 5, // Reject all snapshots from all senders of this snapshot, try others.
Nit: Maybe `REJECT_SENDERS` is a better name here?

2024-12-31 13:52 UTC, SatwikPrabhu commented on crates/consensus/authority/src/comet_bft/abci.rs
> +    fn offer_snapshot(&self, request: RequestOfferSnapshot) -> ResponseOfferSnapshot {
Do you think it would make sense to add info messages to distinguish between the different scenarios of the result `SnapshotOfferResult::REJECT`?

2024-12-31 14:10 UTC, SatwikPrabhu commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                    client.set_finalized(sealed_block_with_senders.header.clone());
Can't we use `sealed_header` here instead?

2024-12-31 14:12 UTC, SatwikPrabhu commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                    };
```suggestion
                    let _engine = engine_util::send_fork_choice_update_payload(
                        block_hash,
                        self.to_engine.clone(),
                    )
                    .await;
```

2025-01-01 10:13 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                    };
Thanks, that code got copied from elsewhere. The error makes no sense as it is 1:1 mapped to the one thrown from the method. I have also kept the .await? as we dont want to fail when sending it fork choice update payload.

2025-01-01 10:14 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +    REJECT_SENDER = 5, // Reject all snapshots from all senders of this snapshot, try others.
This error struct was taken from the abci.rs library  - I have literally copy-pasted it as it was not exported. Just kept it 1:1 for compat reasons. I have no issues with renaming here, but lets maybe keep 1:1 with comet defs.

2025-01-01 11:50 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                    client.set_finalized(sealed_block_with_senders.header.clone());
Well, header is sealed header here. Its just the name that we get from reth :)

2025-01-01 11:58 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +    fn offer_snapshot(&self, request: RequestOfferSnapshot) -> ResponseOfferSnapshot {
I added both info! and warn! messages dep. on the serverity. Thanks for the idea!

2025-01-01 12:04 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +            if snapshot.hash == prost::bytes::Bytes::default() {
I have added a check for the block_id = snapshot_height now. We (as receivers) do not store at the point of confirming the snapshot data yet. I.e. comet would call the syncing logic if it decides we need to sync. There is a clear distinction between snapshot manager (Data and tables) whose snapshots we deliver to other users and our own data during syncing. We only start having some of that once the we agree to receiving a snapshot - there is only one table row during a sync. We cannot have multiple snapshot syncs taking place.

2025-01-01 14:19 UTC, SatwikPrabhu commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                    client.set_finalized(sealed_block_with_senders.header.clone());
I meant that you have assigned this to the variable `sealed_header` earlier. Maybe we can just use that variable here or just remove the variable?

2025-01-01 14:28 UTC, SatwikPrabhu commented on crates/storage/db-api/src/models/chunks.rs
> +    chunk_ids: Vec<u64>,
Maybe we can use Vec<ChunkId> here? I think this holds generally at various places in this file. Also, is there any reason we don't similar types for block id, block hash etc.

2025-01-01 15:41 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                    client.set_finalized(sealed_block_with_senders.header.clone());
oh ,got you. Yep, fixed that, thx.

2025-01-01 15:43 UTC, rwlockbg commented on crates/storage/db-api/src/models/chunks.rs
> +    chunk_ids: Vec<u64>,
Not following your first comment about using Vec ??? We need are separate id types eventhough they are the same since we are following the tables convention already defined by reth.

2025-01-01 16:25 UTC, SatwikPrabhu commented on crates/storage/db-api/src/models/chunks.rs
> +    chunk_ids: Vec<u64>,
Sorry. I meant `Vec<ChunkId>` instead of `Vec<u64>` since we already have that type defined.

2025-01-01 17:01 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/sync/state_sync.rs
> +    let _address =
We can probably remove this

2025-01-01 17:01 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/sync/state_sync.rs
> +        .clone();
Could remove this I think

2025-01-01 17:01 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/sync/state_sync.rs
> +
Is there more work to do for this test? To me it seems like it does some eoas then checks if everyone is on the same block height. This is not an easy test to write. What we probably want is a test util that will safely delete reset comet blocks and reth blocks. For comet we need to first ensure the node has stopped the abci server then we can run the dangerous reset command on that data dir. For Reth i wonder if we just have to run rm -rf on the db and static files. not sure if we can do better

2025-01-01 17:01 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +            if snapshot.hash == prost::bytes::Bytes::default() {
ok that makes sense. Thanks for clarifying

2025-01-01 17:01 UTC, arminsabouri commented on crates/consensus/data-parser/src/lib.rs
> +impl<T: serde::Serialize + serde::de::DeserializeOwned + Clone + Send + Sync + Debug> DataParseable
This is just for my rust knowledge. But why it this impl neccecary?

2025-01-01 17:18 UTC, rwlockbg commented on crates/storage/db-api/src/models/chunks.rs
> +    chunk_ids: Vec<u64>,
yes, but the mbdx macros wont allow that as they need a clearly defined type and not a type alias. I already tried that until I realized that they dont support that.

2025-01-01 17:21 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/sync/state_sync.rs
> +
The test is currently a copy -paste of the builder test. Please dont look at it yet as its far from ready. The difficulty I am facing is to dynamically generate a poa member after a few snapshots are generated by the remaining N-1 poa members. I am still re-thinking the concept here, and yes, it is a really hard test to write.

2025-01-01 17:21 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/sync/state_sync.rs
> +        .clone();
please see below.

2025-01-01 17:21 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/sync/state_sync.rs
> +    let _address =
please see below.

2025-01-09 00:02 UTC, scottmillner commented on crates/consensus/authority/src/snapshot_manager.rs
> +                        Some((last_snapshot_id, last_snapshot_height)) => {
makes sense, thanks!

2025-01-13 15:11 UTC, arminsabouri commented
@rwlockbg can we start reviewing this again?

2025-01-13 21:59 UTC, rwlockbg commented
> @rwlockbg can we start reviewing this again?

Yes

2025-01-21 22:16 UTC, SatwikPrabhu commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                    client.set_finalized(sealed_block_with_senders.header.clone());
Sorry for being nitpicky here. I think you have just fixed this for `set_finalized()`. Same can be done for `set_canonical_head()` and `set_safe()` as well :)

2025-01-24 17:35 UTC, scottmillner commented on bin/test-suite/src/suite/consensus/sync/test_state_sync.rs
> +            // one must be ready
nit: add a short description of what this code block is doing? it's not hard to figure out but description could be nice

2025-01-24 17:45 UTC, scottmillner commented on bin/test-suite/src/suite/consensus/sync/test_state_sync_dynamic.rs
> +    let db_provider_syncing_member =
this test assumes there is just one syncing node correct? above in `saturating_sub(1)` as well
nit: small comment stating this

2025-01-24 17:46 UTC, scottmillner commented on bin/test-suite/src/suite/consensus/sync/test_state_sync_dynamic.rs
> +#[allow(clippy::too_many_lines)]
cool test!! i like it 😄

2025-01-24 22:03 UTC, scottmillner commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                            chunks: snapshot.chunk_ids().len() as u32,
nit: remove comment

2025-01-24 22:22 UTC, scottmillner commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                        let mapped_request_chunk = request.chunk + 1;
little confused by this comment?
if cometbft starts at 0, why do the chunks start at 1? is this the way MDBX works?

2025-01-24 22:42 UTC, scottmillner commented on crates/consensus/authority/src/comet_bft/abci.rs
> +        if let Err(e) =
just a heads up that in pr: https://github.com/botanix-labs/Macbeth/pull/545
the blockchain tree engine has been removed so can't use `insert_block` here but we can hop on a call to help rebase when the time comes

or we can merge this in first whatever makes the most sense
@0xBEEFCAF3 thoughts?

2025-01-24 22:45 UTC, scottmillner commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                    }));
im guessing this is commented out bc we don't want to prevent inserting blocks if creating a snapshot fails?
but if snapshot creation fails, do we have any way to retry creating it?

2025-01-24 22:46 UTC, scottmillner commented on crates/consensus/authority/src/comet_bft/abci.rs
> -            Arc::new(RwLock::new(Some((bitcoin_header, 0))));
i think `TokioRwLock` should be your new slack handle 😆

2025-01-24 22:52 UTC, scottmillner commented on crates/consensus/authority/src/comet_bft/light_client.rs
> -        let light_client = LightClientBuilder::prod(
are we using the light client anywhere or just an http provider?

2025-01-24 23:19 UTC, scottmillner commented on crates/consensus/authority/src/snapshot_manager.rs
> +
shouldn't this comment say the opposite?
we're serializing not deserialzing?

2025-01-26 18:03 UTC, rwlockbg commented on crates/consensus/authority/src/snapshot_manager.rs
> +
yep, exactly. Thanks, I have changed it now.

2025-01-26 18:04 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/light_client.rs
> -        let light_client = LightClientBuilder::prod(
We are not using it Scott. I am using the http provider instead due to the issues I mentioned to you.

2025-01-26 18:04 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> -            Arc::new(RwLock::new(Some((bitcoin_header, 0))));
:) agreed

2025-01-26 18:07 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                    }));
Nah, this was commented out as we cannot have blocking here - the runtime crashes if we allow blocking_Recv a this point. I have removed it now.

2025-01-26 18:08 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +        if let Err(e) =
I will wait for 545 then.

2025-01-26 18:12 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                        let mapped_request_chunk = request.chunk + 1;
I have fixed the comment and made it more self-explanatory.

2025-01-26 18:12 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                            chunks: snapshot.chunk_ids().len() as u32,
done

2025-01-26 18:12 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/sync/test_state_sync_dynamic.rs
> +#[allow(clippy::too_many_lines)]
thx

2025-01-26 18:17 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/sync/test_state_sync_dynamic.rs
> +    let db_provider_syncing_member =
yes, in the setup in the Makefile we set syncing-nodes = 1 https://github.com/botanix-labs/Macbeth/blob/feat/rwlock/state-sync/Makefile#L559

2025-01-26 18:18 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/sync/test_state_sync.rs
> +            // one must be ready
done

2025-01-26 18:22 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                    client.set_finalized(sealed_block_with_senders.header.clone());
done

2025-01-27 20:14 UTC, arminsabouri reviewed
I am 37 / 68 files deep. Leaving a review for now

2025-01-27 20:14 UTC, arminsabouri commented on Makefile
> +	--sync.max_snapshot_size_bytes 8388608 \
Why this number?

2025-01-27 20:14 UTC, arminsabouri commented on Makefile
> +	--sync.snapshot_keep_recent 3 \
Keep recent what? chunks?

2025-01-27 20:14 UTC, arminsabouri commented on bin/test-suite/src/context/mod.rs
> +            syncing_instances: args.syncing_nodes,
Are some of the federation nodes not able to serve syncing demands?

2025-01-27 20:14 UTC, arminsabouri commented on bin/test-suite/src/context/mod.rs
> +            syncing_instances: args.syncing_nodes,
Why do we need this distinction

2025-01-27 20:14 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/common/comet_node.rs
> +                    "7b3ca33b44aee2b296253fa69e1b2b74789655a8aacb7d53a29c397cc8a9b379".to_string(),
Is this always the hash of the first block (height=1)?

2025-01-27 20:14 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/sync/test_state_sync.rs
> +        bitcoind_rpc.get_new_address(None, None).expect("get new address").assume_checked();
Not used. please remove

2025-01-27 20:14 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/sync/test_state_sync.rs
> +    // take the first member as the inturn member
Inturn is not really a concept that we use.  I would remove this comment

2025-01-27 20:14 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/sync/test_state_sync.rs
> +            if snapshots.len() == 2 {
Should we check all members have the same snapshots at this point?

2025-01-27 20:14 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/sync/test_state_sync_dynamic.rs
> +        bitcoind_rpc.get_new_address(None, None).expect("get new address").assume_checked();
Not used remove

2025-01-27 20:14 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/sync/test_state_sync_dynamic.rs
> +    // take the first member as the inturn member
same comment about the comment here

2025-01-27 20:14 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/sync/test_state_sync_dynamic.rs
> +    }
Awesome test! Can we merge the two tests above into one?

2025-01-27 20:14 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/sync/test_state_sync_dynamic.rs
> +    // wait for the syncing node to catch up with expected_sync_height
Should we check that after the node has sync'd that they also have the same snapshots? Does it make sense to check this?

2025-01-27 20:14 UTC, arminsabouri commented on crates/btc-wallet/src/psbt.rs
> -    frost::Identifier::deserialize(&b).ok()
This change will conflict with #552 . In general I dont think this PR should touch btc server

2025-01-27 20:14 UTC, arminsabouri commented on crates/consensus/authority/src/builder.rs
> +            tokio::sync::mpsc::channel::<ABCIDriverMessage>(100);
I would pass canon notif reciever to the snapshot manager not the commit. Simply b/c there is a small chance that commit will error out and we will mistakenly save a block that was never committed

2025-01-27 20:14 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +    pub fn is_identical(
nit: can you impl PartialEq or Eq instead of this method?

2025-01-27 20:14 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +    pub fn is_identical(
or even derive

2025-01-27 20:14 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                                cbft_hash,
Same comment here about using the canon subscriber instead of a new queue. The canon state notifications are fired off when commit is successful. Ideally the snapshot manager can just subscribe to the same queue

2025-01-28 09:02 UTC, rwlockbg commented on Makefile
> +	--sync.max_snapshot_size_bytes 8388608 \
This is equivalent to 8 Mbs in bytes. Its just a hard limit we set here, but we need ot check this in practice in terms of network performance.

2025-01-28 09:03 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                                cbft_hash,
agree, but that is subject to merging Scotts pr first right ?

2025-01-28 09:04 UTC, rwlockbg commented on crates/btc-wallet/src/psbt.rs
> -    frost::Identifier::deserialize(&b).ok()
resolved.

2025-01-28 09:05 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/common/comet_node.rs
> +                    "7b3ca33b44aee2b296253fa69e1b2b74789655a8aacb7d53a29c397cc8a9b379".to_string(),
Nope, this is a random hash which gets overwritten with the correct one during the test runtime, before the commet node is spawned.

2025-01-28 09:06 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/common/comet_node.rs
> +                    "7b3ca33b44aee2b296253fa69e1b2b74789655a8aacb7d53a29c397cc8a9b379".to_string(),
block = 1 has a diff hash on each run. Only height = 0 has the same, but we are not lallowed to have block h = 0 in the config.

2025-01-28 10:01 UTC, rwlockbg commented on crates/consensus/authority/src/builder.rs
> +            tokio::sync::mpsc::channel::<ABCIDriverMessage>(100);
I agree, but lets add this after Scotts per gets merged as I fear there will be conflicts either way

2025-01-28 10:04 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/sync/test_state_sync.rs
> +    // take the first member as the inturn member
I have renamed it here and all the other tests having the same variable and description

2025-01-28 10:04 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/sync/test_state_sync_dynamic.rs
> +        bitcoind_rpc.get_new_address(None, None).expect("get new address").assume_checked();
removed

2025-01-28 10:04 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/sync/test_state_sync_dynamic.rs
> +    // take the first member as the inturn member
changed, see above

2025-01-28 10:08 UTC, rwlockbg commented on crates/consensus/authority/src/comet_bft/abci.rs
> +    pub fn is_identical(
done

2025-01-28 10:09 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/sync/test_state_sync.rs
> +        bitcoind_rpc.get_new_address(None, None).expect("get new address").assume_checked();
removed

2025-01-28 10:09 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/common/comet_node.rs
> +                    "7b3ca33b44aee2b296253fa69e1b2b74789655a8aacb7d53a29c397cc8a9b379".to_string(),
I have left a comment there for info.

2025-01-28 10:19 UTC, rwlockbg commented on Makefile
> +	--sync.max_snapshot_size_bytes 8388608 \
In the comet docs they recommend up to 10 mbs.

2025-01-28 10:21 UTC, rwlockbg commented on bin/test-suite/src/context/mod.rs
> +            syncing_instances: args.syncing_nodes,
Because we need to know how many of them fed members will be syncing. Why ? Because the cometbt nodes are not being prepared and run until we decide so during the test execution  unlike the standard fed members which are being pre-created alongside with their cometbft nodes. I did not find a better way of doing it as we need to have this dynamic nature for the state sync.

2025-01-28 10:25 UTC, rwlockbg commented on bin/test-suite/src/context/mod.rs
> +            syncing_instances: args.syncing_nodes,
And yes, as I have mentioned before, if the block_height > 0 then the sync shall start. When all nodes start simultaneously as now there is no sync. The idea of the syncing)instances is to pre-create them and allow us to actually start them when we want state sync to be triggered.SO, in other words, these instances are not serving syncing demands when they are first being created but only rather when they are being run and onwards.

2025-01-28 10:34 UTC, rwlockbg commented on bin/test-suite/src/suite/consensus/sync/test_state_sync_dynamic.rs
> +    // wait for the syncing node to catch up with expected_sync_height
Not really, as the syncing node's commit rpc endpoint wont be called by the cometbft network during syncing (this is how comet works). Because of this the snapshot builder wont be receiving any messages during state sync and wont have any snapshots persisted. Once state sync is done and the cometbft mechanism kicks in (commit rpc being called, abci driver messages forwarding to snapshot manager) then we will start building snapshots.

2025-01-28 10:48 UTC, rwlockbg commented on Makefile
> +	--sync.snapshot_keep_recent 3 \
keep recent snapshots. I have renamed it to `num_snapshots_to_keep` everywhere

2025-01-28 20:14 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/sync/test_state_sync_dynamic.rs
> +    }
@rwlockbg following up on this

2025-02-03 18:30 UTC, scottmillner commented on crates/consensus/authority/src/builder.rs
> +            tokio::sync::mpsc::channel::<ABCIDriverMessage>(100);
the way this works now:
- in driver `start` after inserting the block, the `CommitBlock` is sent to the snapshot manager. And the `CommitBlock` message has additional fields needed by the manager that the `canon notif receiver` will not have.

2025-02-03 18:31 UTC, scottmillner commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                                cbft_hash,
please see comment above

2025-02-03 18:57 UTC, scottmillner commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                        hash: prost::bytes::Bytes::copy_from_slice(&snapshot.block_hash().0),
this can be any arbitrary hash and at the moment we only check that it's not default bytes
so i guess the value should be whatever might be useful in the future

we're setting it as the comet `app_hash` at the `snapshot.height` which is the final block height contained in the snapshot

maybe that's useful maybe not...i'd say leave a todo to revisit since we're not really using the field

2025-02-03 23:50 UTC, scottmillner commented on crates/consensus/authority/src/comet_bft/abci.rs
> +    }
no based on the docs: `The chunk index, starting from 0. CometBFT applies chunks sequentially.`

and have confirmed this when running int test

2025-02-04 00:57 UTC, scottmillner commented on bin/test-suite/src/suite/consensus/sync/test_state_sync_dynamic.rs
> +    }
done!

2025-02-05 15:36 UTC, arminsabouri requested changes
This is alot to review. The biggest things as of now that give me pause in order of urgency are
1. Seemingly unrelated consensus changes in peg_contract. There were some ser/deser utils added. If these utils are related lmk and I can review this more carefully other wise please remove this and consider a seperate PR with test coverage
1. Each chunk appears to be a block. The main benefit of state sync over block sync is that we can save round of communication however that is completly negated if we need to do 2 rounds of comms for each block. It would make sense to me if we can fit many blocks into a 10MB chunks. 
1. Duplicated code in abci.rs. We've spent a while in Jan removing techdebt and I dont think it makes sense for new experimental features to add tech debt 
1. I have some questions about the use of `BlockWithContext`. Generally it doesnt make alot of sense to me that each chunk is a rich block with excecution context. Perhaps we need this so we can `insert_block_with_data` b/c we need the historical reciepts. However,  each chunk being a block seems to negate some of the benefits of state sync. Mainly we need to do a full 2 rounds of comms for each block (as is the case with block sync). It would make alot of sense to concat blocks into many chunks until we hit the max chunk size. 
1. Lower priority but I'd like to see some docs around the new tables. How they relate to each other and how they intended to be used. 
1. I imagine in prod we are going to want to reset the snapshot manager / snapshot tables if we need to. Do we have a plan for this? 

I undestand this is a lot of review but this is a lot of code. Thanks for your persistance on this PR. I greatly appreciate the patience

2025-02-05 15:36 UTC, arminsabouri commented on bin/btc-server/src/database/error.rs
> +use thiserror::Error;
In the future please keep these cosmetic changes in a different commit or differnt PR entirely

2025-02-05 15:36 UTC, arminsabouri commented on crates/storage/provider/src/traits/snapshot.rs
> +    /// Get snapshot by id
Wrong doc string for method

2025-02-05 15:36 UTC, arminsabouri commented on crates/storage/provider/src/traits/snapshot.rs
> +    fn get_snapshot_sync_by_height(&self, height: u64) -> ProviderResult<Option<SnapshotSync>>;
What is the difference beteween snapshot sync and snapshot itself?

2025-02-05 15:36 UTC, arminsabouri commented on crates/storage/provider/src/traits/snapshot.rs
> +    fn get_snapshot_id_by_block_id(
In someplaces in this trait we use height other places we use block number / block id.
I would just unify this terminology and use height. And rename this to `get_snapshot_id_by_height`

2025-02-05 15:36 UTC, arminsabouri commented on crates/storage/provider/src/traits/snapshot.rs
> +    fn delete_chunks_in_blocks(&self, range: RangeInclusive<ChunkId>) -> ProviderResult<()>;
How are these two different?

2025-02-05 15:36 UTC, arminsabouri commented on crates/storage/provider/src/traits/snapshot.rs
> +    ) -> ProviderResult<SnapshotId>;
What exactly is the differnce between these? And is there a better name for snapshotsync that would be more descriptive on what we are actually creating. B/c when we say `create_new_snapshot` I can conceptualize what data is being saved or created on the db. But i cannot say the same thing for snapshot_sync

2025-02-05 15:36 UTC, arminsabouri commented on bin/btc-server/src/wallet/psbt.rs
> +    frost::round2::SignatureShare::deserialize(b).ok()
Is this fixing a warning? I generally agree with this change but why is it needed as a part of state sync?

2025-02-05 15:36 UTC, arminsabouri commented on bin/reth/src/commands/poa/mod.rs
> +            tokio::sync::mpsc::channel::<ABCIDriverMessage>(100);
I gave this feedback somewhere else in this PR. But why can't we just use the canon state notifications?

2025-02-05 15:36 UTC, arminsabouri commented on bin/reth/src/commands/poa/mod.rs
> +            tokio::sync::mpsc::channel::<ABCIDriverMessage>(100);
A bit strange also that this queue can take up to 100 message but the one driver can only take 1? does that make sense?

2025-02-05 15:36 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/common/btc_server.rs
> +    }
Ack this change but in the future I will be more anal about unrelated improvments being merged in main first.

2025-02-05 15:36 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_utxo_sync.rs
> +    }
Nit: this operation can just be a method on `local_context()`.
```
suite.local_context.get_eth_providers()

```

This way each individual test doesnt need to remove syncing nodes

2025-02-05 15:36 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/sync/test_state_sync.rs
> +            if snapshots.len() == 2 {
@rwlockbg @scottmillner Following up on this

2025-02-05 15:36 UTC, arminsabouri commented on crates/consensus/authority/src/prost_parser.rs
> +/// Password hashing error types.
Password Hashing?

2025-02-05 15:36 UTC, arminsabouri commented on crates/consensus/authority/src/prost_parser.rs
> +#[allow(dead_code)]
Where do we expect to use this?

2025-02-05 15:36 UTC, arminsabouri commented on crates/primitives/src/botanix/peg_contract.rs
> +#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
I dont understand why these `Deserialize, Serialize` changes are included? Is there a strong reason for state sync? If not please revert these changes.

2025-02-05 15:36 UTC, arminsabouri commented on crates/primitives/src/botanix/utils.rs
> +    Ok(bitcoin::Address::from_str(&s).map_err(serde::de::Error::custom)?.assume_checked())
Dangerous use of `assumed_checked()` here. Can you justify why? 
Esp since I see this being used in peg_contract where we check for the validity of an address with respect to the bitcoin network

2025-02-05 15:36 UTC, arminsabouri commented on crates/storage/db/src/tables/mod.rs
> +    /// Table used when syncing snapshots.
Nit: The rest of the tables are self-descriptive. Snapshot sync im not sure i understand. Can you provide some more detail what this table is responsible for

2025-02-05 15:36 UTC, arminsabouri commented on crates/storage/provider/src/providers/database/provider.rs
> +        block_id: BlockNumber,
Nit: block_id means a specific thing in the reth world. Lets rename to block_number

2025-02-05 15:36 UTC, arminsabouri commented on crates/storage/provider/src/traits/snapshot.rs
> +    fn delete_chunks_in_blocks(&self, range: RangeInclusive<ChunkId>) -> ProviderResult<()>;
remove_chunks & delete_chunks_in_blocks

2025-02-05 15:36 UTC, arminsabouri commented on crates/storage/db/src/tables/mod.rs
> +    /// Stores block snapshots.
```suggestion
    /// Association table linking block number to snapshot id 
```

2025-02-05 15:36 UTC, arminsabouri commented on crates/storage/db/src/tables/mod.rs
> +    /// Stores the block number to chunk ids
is a `BlockChunksRegister` the same as a chunk id?

2025-02-05 15:36 UTC, arminsabouri commented on crates/storage/provider/src/providers/database/provider.rs
> +        Ok(snapshot_size + chunks_size)
Just double checking here. Isnt a snapshot consisting of a many chunks? So why are we not just returning `chunks_size`?

2025-02-05 15:36 UTC, arminsabouri commented on crates/storage/provider/src/providers/database/provider.rs
> +        let block_ids = snapshot.unwrap().block_ids().to_vec();
```suggestion
        let block_ids = snapshot.expect("checked above").block_ids().to_vec();
```

2025-02-05 15:36 UTC, arminsabouri commented on crates/storage/provider/src/providers/database/provider.rs
> +            blocks_data.push((block, concatenated));
Just want to understand? A block can be in many chunks? Is it possible for a many blocks to be in one chunk?

2025-02-05 15:36 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +        block_chain_provider_2: BlockchainProvider2<Arc<DatabaseEnv>>,
Nit: `_2` is unneccecary

2025-02-05 15:36 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                info!("Returned snapshots {:?}", resp);
Will this be a large print? If so can we just print the id and the number of chunks returned?

2025-02-05 15:36 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +        let db_rw = self.provider_factory.provider_rw().unwrap();
handle `unwrap()`

2025-02-05 15:36 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +            let block_with_context: BlockWithContext = compressor
Is each individual chunk a block with context? If so im not sure how this can be better than block sync. We would have to make a back and forth for each block in snapshot?

2025-02-05 15:36 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +        client.set_finalized(new_header);
There is a lot of duplicated code here. I will ask that we consolidate this as much as we can

2025-02-05 15:36 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +    }
So is the lock redundant then?

2025-02-05 15:36 UTC, arminsabouri commented on crates/consensus/authority/src/comet_bft/abci.rs
> +                        let (snapshot_manager_announced_tx, _snapshot_manager_announced_rx) =
Why is the mpsc required? Im not seeing the rx side used?

2025-02-05 20:03 UTC, scottmillner commented on crates/storage/provider/src/traits/snapshot.rs
> +    fn get_snapshot_sync_by_height(&self, height: u64) -> ProviderResult<Option<SnapshotSync>>;
`SnapshotSync` is a struct that is used while syncing and has metadata like `total_chunks: u64` and `last_applied_chunk_index: u64`

- this is used to enforce chunks are applied in sequential order

`Snapshot` is the final result after syncing all the chunks of a snapshot

2025-02-05 20:18 UTC, scottmillner commented on crates/storage/provider/src/traits/snapshot.rs
> +    fn delete_chunks_in_blocks(&self, range: RangeInclusive<ChunkId>) -> ProviderResult<()>;
these methods use two different tables

`Chunks` table which is a mapping of `ChunkId` and the chunk data itself
- `remove_chunks` updates this table

` ChunkBlocks` is a mapping of `ChunkId` to `BlockNumber`
- ` delete_chunks_in_blocks` updates this table

2025-02-05 20:47 UTC, scottmillner commented on crates/storage/provider/src/traits/snapshot.rs
> +    fn get_snapshot_id_by_block_id(
done in https://github.com/botanix-labs/Macbeth/pull/569

i looked at doing the same for methods like `get_snapshot_by_id` but `id` and `height`  are separate fields on `SnapShot`

2025-02-05 20:48 UTC, scottmillner commented on crates/storage/provider/src/traits/snapshot.rs
> +    /// Get snapshot by id
fixed in https://github.com/botanix-labs/Macbeth/pull/569

2025-02-06 14:52 UTC, arminsabouri commented on crates/node/core/src/args/state_sync.rs
> +pub(crate) const DEFAULT_MAX_SNAPSHOT_SIZE_BYTES: usize = 8 * 1024 * 1024; // 8 Mbs max size
Per the [cometBFT Docs](https://docs.cometbft.com/main/spec/abci/abci++_app_requirements#taking-snapshots)  the suggested size of chunks is 10MB. Where did 8MB come from for the snapshot size? This appears too low.

2025-02-06 16:13 UTC, scottmillner commented on crates/node/core/src/args/state_sync.rs
> +pub(crate) const DEFAULT_MAX_SNAPSHOT_SIZE_BYTES: usize = 8 * 1024 * 1024; // 8 Mbs max size
made it 10mb and non-configurable(const in snapshot_manager)

2025-02-06 16:16 UTC, scottmillner commented on crates/consensus/authority/src/comet_bft/abci.rs
> +    }
yes

2025-02-11 18:44 UTC, merged