feat(btc-server): Add conflicting input when retyring pegouts
botanix-labs/Macbeth pull request #510
Opened 2024-12-10 00:13 UTC by scottmillner

2024-12-11 20:07 UTC, arminsabouri reviewed
Just some comments at first glance. Overall this seems to be moving in the right direction!

2024-12-11 20:07 UTC, arminsabouri commented on bin/btc-server/src/coordinator.rs
> +        validate_psbt(psbt, ROUND1, self.min_signers, &self.db, &self.pegout_scheduler).await?;
Would it make more sense to pass a ref to a list of pending txs? You could also get a iter() from the db which is already passed in. I would try to see if sled has a smart way of doing lookups rather than trying to read in all of tracked inputs

2024-12-11 20:07 UTC, arminsabouri commented on bin/btc-server/src/main.rs
> +        let pegout_id = PegoutId::new(tx_id, tx_idx);
We have a test util to generate random pegoutIds. I would use that to save on code diff

2024-12-11 20:07 UTC, arminsabouri commented on bin/btc-server/src/signer.rs
> +        validate_psbt(psbt, ROUND1, self.min_signers, &self.db, &self.pegout_scheduler).await?;
We should think about feature flags here. 
if we feature flag this we can start to write int. tests for this code and ship it turned off. 
Otherwise We cant ship it

2024-12-11 20:07 UTC, arminsabouri commented on bin/btc-server/src/util.rs
> +        let tx_idx = rng.gen_range(0..u32::MAX);
Same pegoutId comment here

2024-12-12 21:54 UTC, scottmillner commented on bin/btc-server/src/coordinator.rs
> +        validate_psbt(psbt, ROUND1, self.min_signers, &self.db, &self.pegout_scheduler).await?;
yeah i def shouldve approached this a different way, not sure why i went this route

i need two things: the `tracked inputs` and the `pegout request ids` both of which i get from the `tracked_txs` 
im gonna see if i can do smart lookups with the db since it's already passed in

thanks for suggesting that!

2024-12-17 00:15 UTC, scottmillner commented on bin/btc-server/src/coordinator.rs
> +        validate_psbt(psbt, ROUND1, self.min_signers, &self.db, &self.pegout_scheduler).await?;
refactored so no additional args are passed to `validate_psbt`, will just use the db
but see my comment about `has_conflicting_input`, not sure it's really much better than reading all the tracked_txs into memory

2024-12-17 00:15 UTC, scottmillner commented on bin/btc-server/src/main.rs
> +        let pegout_id = PegoutId::new(tx_id, tx_idx);
done, thanks!

2024-12-17 00:15 UTC, scottmillner commented on bin/btc-server/src/util.rs
> +        let tx_idx = rng.gen_range(0..u32::MAX);
done!

2024-12-17 00:17 UTC, scottmillner commented on bin/btc-server/src/database.rs
> +    /// Checks a PSBT has a conflicting input if it contains a tracked PegoutId.
@0xBEEFCAF3 
im not a big fan of what im doing here...its O(n2) since we have two for loops
was trying not to read all `tracked_txs` into memory first and this is the only way to really do it
sled doesn't offer any smarter way since I have to deserialize `Tx` first and then check it's fields

2024-12-17 01:03 UTC, scottmillner commented on bin/btc-server/src/signer.rs
> +        validate_psbt(psbt, ROUND1, self.min_signers, &self.db, &self.pegout_scheduler).await?;
added feature flags
will start on integration test now

2024-12-18 00:36 UTC, scottmillner commented on bin/btc-server/src/signer.rs
> +        validate_psbt(psbt, ROUND1, self.min_signers, &self.db, &self.pegout_scheduler).await?;
integration test added

2024-12-18 16:35 UTC, arminsabouri requested changes
Thanks for adding those feature flags!  I was thinking env vars but I like your approach much better. just leaving some ideas around code structure and testing approach. And found one extract_tx() call that I think was removed b.c it wasn't commented well.

2024-12-18 16:35 UTC, arminsabouri commented on bin/btc-server/src/util.rs
> +    } else {
I agree that this if else makes sense but since we return err in the first if can we just call `db.has_conflicting_input(psbt)?;` without the else. Imo its a bit easier to read

2024-12-18 16:35 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_conflicting_input.rs
> +    }
We have this specific assertion in a different test. I would just remove this from the conflicting inputs test.

2024-12-18 16:35 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_conflicting_input.rs
> +    //    "txn-mempool-conflict" since the first psbt is still in the mempool.
```suggestion
    //    "txn-mempool-conflict" since the first tx is still in the mempool.
```

2024-12-18 16:35 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_conflicting_input.rs
> +    // 1) Signers will reject the psbt if it contains no conflicting input.
```suggestion
    // 1) Signers will reject the psbt if it contains no conflicting input. This does not happen b/c the coordinator will include a conflicting input and signers will validate against this
```

2024-12-18 16:35 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_conflicting_input.rs
> +    Err(anyhow::anyhow!("expected txn-mempool-conflict error"))
Another testing case that is interesting is to do round 1 FROST but never do round 2. And then in a new signing session do round 1 & round 2 and broadcast.

2024-12-18 16:35 UTC, arminsabouri commented on bin/btc-server/src/util.rs
> +            db.has_conflicting_input(psbt)?;
Any opinions on creating a the `has_conflicting_input` method in `util.rs` instead of db? And passing the db down? Just thinking domain seperation

2024-12-18 16:35 UTC, arminsabouri commented on bin/btc-server/src/signer.rs
> -
Do we want to remove this? Eventho _tx is never used extract_tx() performs several fee sanity checks.
maybe we need a comment to justify the use here.

2024-12-18 16:35 UTC, arminsabouri commented on bin/btc-server/src/database.rs
> +    /// Checks a PSBT has a conflicting input if it contains a tracked PegoutId.
is there a way to do contains with sled?
im thinking 
```
for pegout_id in pegouts_ids {
   if self.tracked_txs.contains(pegout_id) -> look_for_conflicting_input()
}

2024-12-18 18:01 UTC, SatwikPrabhu commented on bin/btc-server/src/database.rs
> +    /// Checks a PSBT has a conflicting input if it contains a tracked PegoutId.
Isn't this technically O(n3) because we are also using any(). I think that maybe it is possible to do O(n2). I'll get back if what I have in mind makes sense

2024-12-18 19:19 UTC, SatwikPrabhu commented on bin/btc-server/src/database.rs
> +    /// Checks a PSBT has a conflicting input if it contains a tracked PegoutId.
For example, maybe the following (untested) is  valid and also having better complexity:
`


    let psbt_inputs: HashSet<_> = psbt.unsigned_tx.input
        .iter()
        .map(|input| input.previous_output)
        .collect();

    let pegout_ids: HashSet<_> = psbt
        .pegout_ids()
        .iter()
        .map(|id| PegoutId::from_bytes(id).expect("valid pegout id"))
        .collect();

    for res in self.tracked_txs.iter() {
        let (_k, v) = res?;
        let tx: pegout_scheduler::Tx =
            ciborium::de::from_reader(v.as_ref()).expect("corrupt db: tracked tx");
        
        let has_matching_pegout = tx.pegout_requests
            .iter()
            .any(|request| pegout_ids.contains(&request.id));
            
        if has_matching_pegout {
            let has_shared_input = tx.inputs()
                .any(|input| psbt_inputs.contains(&input));
                
            if has_shared_input {
                return Ok(());
            } else {
                return Err(Error::NoConflictingInput);
            }
        }
    }`

2024-12-18 19:30 UTC, SatwikPrabhu commented on bin/btc-server/src/main.rs
> +    // this test ensures a conflicting input in included in the psbt when retyring the same
Nit:
```suggestion
    // this test ensures a conflicting input is included in the psbt when retrying the same
```

2024-12-18 20:10 UTC, SatwikPrabhu commented on bin/btc-server/src/signer.rs
> +        }
Maybe the assignment of the variable `pending_pegout_ids` should be moved inside the if as well?

2024-12-18 21:13 UTC, scottmillner commented on bin/btc-server/src/database.rs
> +    /// Checks a PSBT has a conflicting input if it contains a tracked PegoutId.
> is there a way to do contains with sled? im thinking
> 
> ```
> for pegout_id in pegouts_ids {
>    if self.tracked_txs.contains(pegout_id) -> look_for_conflicting_input()
> }
> ```

unfortunately there isn't a way to do that
you can only do `contains_key` which is `txid` in this case and isn't useful

sled doesn't have a concept of a complex data structure at rest...values are just arbitrary byte arrays
would be easy with a relational database but we have to deserialize `Tx` and then check it's fields

2024-12-18 21:23 UTC, scottmillner commented on bin/btc-server/src/database.rs
> +    /// Checks a PSBT has a conflicting input if it contains a tracked PegoutId.
> For example, maybe the following (untested) is valid and also having better complexity: `
> 
> ```
> let psbt_inputs: HashSet<_> = psbt.unsigned_tx.input
>     .iter()
>     .map(|input| input.previous_output)
>     .collect();
> 
> let pegout_ids: HashSet<_> = psbt
>     .pegout_ids()
>     .iter()
>     .map(|id| PegoutId::from_bytes(id).expect("valid pegout id"))
>     .collect();
> 
> for res in self.tracked_txs.iter() {
>     let (_k, v) = res?;
>     let tx: pegout_scheduler::Tx =
>         ciborium::de::from_reader(v.as_ref()).expect("corrupt db: tracked tx");
>     
>     let has_matching_pegout = tx.pegout_requests
>         .iter()
>         .any(|request| pegout_ids.contains(&request.id));
>         
>     if has_matching_pegout {
>         let has_shared_input = tx.inputs()
>             .any(|input| psbt_inputs.contains(&input));
>             
>         if has_shared_input {
>             return Ok(());
>         } else {
>             return Err(Error::NoConflictingInput);
>         }
>     }
> }`
> ```

thanks, ill take a look!

2024-12-19 00:22 UTC, scottmillner commented on bin/btc-server/src/signer.rs
> +        }
done, thanks!

2024-12-19 00:22 UTC, scottmillner commented on bin/btc-server/src/signer.rs
> -
added back, sorry i missed that!

2024-12-19 00:23 UTC, scottmillner commented on bin/btc-server/src/util.rs
> +            db.has_conflicting_input(psbt)?;
yeah was thinking to do that and forgot so thanks!

2024-12-19 00:23 UTC, scottmillner commented on bin/btc-server/src/util.rs
> +    } else {
done!

2024-12-19 00:27 UTC, scottmillner commented on bin/test-suite/src/suite/consensus/frost/test_conflicting_input.rs
> +    }
done!

2024-12-19 00:31 UTC, scottmillner commented on bin/test-suite/src/suite/consensus/frost/test_conflicting_input.rs
> +    Err(anyhow::anyhow!("expected txn-mempool-conflict error"))
not quite following:
- a tx is tracked in `finalize_signing` when it's broadcast (after round 2 is finished)
- so there would be no conflicting input needed in this scenario

what am i missing?

2024-12-19 00:48 UTC, scottmillner commented on bin/btc-server/src/database.rs
> +    /// Checks a PSBT has a conflicting input if it contains a tracked PegoutId.
@SatwikPrabhu went with a slightly refactored version of what you suggested
thanks, it's def better now!

2024-12-19 09:18 UTC, SatwikPrabhu commented on bin/btc-server/src/signer.rs
> +        }
Maybe my comment was not totally clear (sorry abou that), because I meant moving the line with `let pending_pegout_ids = ` inside the if block that checks for the feature. I thought that this is better because we don't use the variable if the feature is not enabled.

2024-12-19 13:24 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_conflicting_input.rs
> +    Err(anyhow::anyhow!("expected txn-mempool-conflict error"))
txs are tracked as soon as signers sign. if they start tracking only after witness has been added then a coordinator could replay round 1 spending to the same set of outputs with different set of inputs and signers will double spend. This is why its crutial that signers start tracking post round1.

2024-12-19 13:39 UTC, arminsabouri reviewed
Just a few more comments. And after reviewing this code I think I found some missing checks in out psbt validation method. So i'll be fixing those. Particularly the case for duplicate outputs

2024-12-19 13:39 UTC, arminsabouri commented on bin/btc-server/src/util.rs
> +        .map(|id| PegoutId::from_bytes(id).expect("valid pegout id"))
should we error out here instead of expect?

2024-12-19 13:39 UTC, arminsabouri commented on bin/btc-server/src/util.rs
> +        assert_eq!(res.unwrap_err().to_string(), "no conflicting input");
Can we enumerate over a few more test cases?
- conflicting inputs not needed
- conflicting inputs across two different txs. Lets say we are retrying tx A with outputs A_o and B with B_o. Tx C will be a batch that spends another outputs but also retries A_o and B_o. So we need conflicting inputs from both

2024-12-19 13:39 UTC, arminsabouri commented on bin/btc-server/src/util.rs
> +        psbt.outputs[0].set_pegout_id(pegout_id.as_bytes());
its interesting that this just setting the pegout id is all it takes for a conflicting inputs check. In someway I think the pegout id needs to commit to the output. im not sure yet. What do you think?

2024-12-19 14:19 UTC, scottmillner commented on bin/btc-server/src/signer.rs
> +        }
i understood and made that change 😃

2024-12-19 21:16 UTC, scottmillner commented on bin/test-suite/src/suite/consensus/frost/test_conflicting_input.rs
> +    Err(anyhow::anyhow!("expected txn-mempool-conflict error"))
ah gotchya, at the moment the tx is only being tracked in `get_round2_signing_package` and `finalize_signing`

but we need to track the tx before `get_round2_signing_package` as well and write an int test for the case above

2024-12-19 21:24 UTC, arminsabouri commented on bin/test-suite/src/suite/consensus/frost/test_conflicting_input.rs
> +    Err(anyhow::anyhow!("expected txn-mempool-conflict error"))
Sorry I mispoke. the tx is being tracked in `get_round2_signing_package` and that is the correct functionality. The only reason we also track in finalize is incase he coordinator didnt sign (which in our current state machine would never be the case).

So the test case is really: Ensure that signers don't need conflicting inputs if they never got to round 2.

2024-12-19 21:31 UTC, scottmillner commented on bin/btc-server/src/util.rs
> +        psbt.outputs[0].set_pegout_id(pegout_id.as_bytes());
maybe we can whiteboard this a bit

my thoughts:
- a `PegoutId` is composed of `txid` and `idx` on the L2 which is a unique and discreet event that will never happen again
- an `Output` is composed of `value` and `script_pubkey` and could occur multiple times (ie, the user pegouts at a different time for the same amount to the same address)

so what does commiting to the `Output` give us? 
im probably missing something here

2024-12-23 14:50 UTC, scottmillner commented on bin/btc-server/src/util.rs
> +        psbt.outputs[0].set_pegout_id(pegout_id.as_bytes());
we discussed offline
- problem: how can we know if btc-server is given malicious payloads to sign 
- a possible approach is adding additional keys for authentication (like Liquid) but needs further research and is outside the scope of this PR

2024-12-24 00:52 UTC, scottmillner commented on bin/btc-server/src/util.rs
> +        .map(|id| PegoutId::from_bytes(id).expect("valid pegout id"))
we should and done!

2024-12-24 00:53 UTC, scottmillner commented on bin/btc-server/src/util.rs
> +        assert_eq!(res.unwrap_err().to_string(), "no conflicting input");
done!

2024-12-24 00:58 UTC, scottmillner commented on bin/test-suite/src/suite/consensus/frost/test_conflicting_input.rs
> +    Err(anyhow::anyhow!("expected txn-mempool-conflict error"))
just a follow up on this one: `validate_psbt` which isn't called in round 1 is the only way to trigger the `has_conflicting_input` check

2024-12-24 10:41 UTC, SatwikPrabhu commented on bin/btc-server/src/coordinator.rs
> +        let mut selected = selection
Why is this `mut`?

2024-12-24 14:09 UTC, scottmillner commented on bin/btc-server/src/coordinator.rs
> +        let mut selected = selection
ah thanks, it shouldn't be, it was from a previous refactor that i changed
done!

2024-12-26 18:45 UTC, scottmillner commented on bin/test-suite/src/suite/consensus/frost/test_conflicting_input.rs
> +    Err(anyhow::anyhow!("expected txn-mempool-conflict error"))
i added a test to cover this called `test_round1_then_new_signing_session`

2025-01-01 19:03 UTC, arminsabouri reviewed
This PR is pretty much ready to go but I would like to hop on a quick call to make sure we have covered all of our edge cases.

2025-01-01 19:03 UTC, arminsabouri commented on bin/btc-server/src/coordinator.rs
> +                .flat_map(|tx| tx.pegout_requests.clone().into_iter().map(|p| p.id))
Nit: do we need to clone here?

2025-01-01 19:03 UTC, arminsabouri commented on bin/btc-server/src/coordinator.rs
> +        });
Just a note that https://github.com/botanix-labs/Macbeth/pull/358 will be extracting coin selection into its own mod. Once that happens we can write granular unit tests for this

2025-01-01 19:03 UTC, arminsabouri commented on bin/btc-server/src/coordinator.rs
> +                .map(|tx| tx.inputs().next().ok_or_else(|| CoordinatorError::NoConflictingInputs))
Aplogies if I am just misunderstanding this line. But why is this map needed? Are we just checking after we filter the tracked txs for matching pegout ids that the inputs are non empty?

2025-01-01 19:03 UTC, arminsabouri commented on bin/btc-server/src/coordinator.rs
> +                            conflicting_utxos.insert(op.clone(), u.clone());
Do we need to include every UTXO from the prev tracked tx? is sufficient just to add one. I worry that requiring all these utxos could lead to unnatural utxo selection.

2025-01-01 19:03 UTC, arminsabouri commented on bin/btc-server/src/signer.rs
> +        if cfg!(feature = "conflicting_input") {
One other note that came to mind. Do we need to update the tracked txs if we are including a conflicting input? 
Bc we will have a set of pegouts we are tracking and now there will be a another tx with a subset of the same pegouts. It seems like we can track both txs but once one is confirmed the other MUST be deleted. And perhaps we should also have a retention period for how long we track the pegout that is not in a block (mempool tracking).

This can get complicated. Lets hop on a quick call to talk the rest of this out

2025-01-01 19:42 UTC, SatwikPrabhu commented on bin/btc-server/src/signer.rs
> +        if cfg!(feature = "conflicting_input") {
Im generally available for a call after an hour. Let me know when is a good time.

2025-01-03 20:00 UTC, arminsabouri commented
@scottmillner im assigning my self to this PR to rebase on the latest in main. I've discovered a bug in the fee calculation

2025-01-06 23:26 UTC, scottmillner commented on bin/btc-server/src/coordinator.rs
> +                .map(|tx| tx.inputs().next().ok_or_else(|| CoordinatorError::NoConflictingInputs))
this is what im thinking which may be wrong:
- im finding every tracked tx that was honoring a pegout that is being retried in this psbt
- then getting an input from each of those tracked txs
- so there is a conflicting input from each of those tracked txs

bc:
- if i don't include a conflicting input from each tracked tx that has a pegout being retried
- that tracked tx and the current psbt about to be broadcast could both be confirmed and we have double spent the same output

2025-01-07 00:04 UTC, scottmillner commented on bin/btc-server/src/coordinator.rs
> +                .flat_map(|tx| tx.pegout_requests.clone().into_iter().map(|p| p.id))
nope, it was bc i was using `into_iter()` when i didn't need to

using `iter()` now and removed `clone()`, thanks!

2025-01-07 00:06 UTC, scottmillner commented on bin/btc-server/src/coordinator.rs
> +                            conflicting_utxos.insert(op.clone(), u.clone());
see my answer above which describes my thinking

2025-01-07 00:15 UTC, scottmillner commented on bin/btc-server/src/signer.rs
> +        if cfg!(feature = "conflicting_input") {
yes i think we do
based on our follow-up call, made new ticket: https://github.com/botanix-labs/botanix/issues/858

2025-01-07 01:42 UTC, arminsabouri commented on bin/btc-server/src/coordinator.rs
> +                .map(|tx| tx.inputs().next().ok_or_else(|| CoordinatorError::NoConflictingInputs))
Actually my question was regarding the .inputs().next() semantics you used rather than the check it self.

2025-01-07 13:09 UTC, merged

2025-01-07 14:34 UTC, scottmillner commented on bin/btc-server/src/coordinator.rs
> +                .map(|tx| tx.inputs().next().ok_or_else(|| CoordinatorError::NoConflictingInputs))
ah my bad, `.inputs().next()` returns the first element by the iterator...so i'm grabbing the first input to use as a conflicting input