feat(repo): Pending pegouts controller
botanix-labs/Macbeth pull request #512
Opened 2024-12-11 00:03 UTC by rwlockbg

Related issue: https://github.com/botanix-labs/botanix/issues/757

2024-12-11 01:13 UTC, scottmillner submitted a review, later dismissed
thanks for doing this which will prevent that annoying error log now 😃 !

looks like `test_notify_pegout` is failing

2024-12-11 01:24 UTC, arminsabouri requested changes

2024-12-11 01:24 UTC, arminsabouri commented on bin/btc-server/src/server.rs
> +            get_available_utxos(&self.pegout_scheduler, &self.db).await.map_err(|e| {
its possible that we may pre-maturely reject a pegout even if there are tracked tx i.e change coming into the spendable utxo set. I believe the check should be if there are no available utxos and no tracked txs then there is no possible way there can be pending tx.

2024-12-11 01:43 UTC, scottmillner commented on bin/btc-server/src/server.rs
> +            get_available_utxos(&self.pegout_scheduler, &self.db).await.map_err(|e| {
yeah that makes sense bc the `tracked_tx` could get deeply confirmed and the change returned to the utxo set before the epoch ends and the pegouts are honored

2024-12-11 09:20 UTC, rwlockbg commented on bin/btc-server/src/server.rs
> +            get_available_utxos(&self.pegout_scheduler, &self.db).await.map_err(|e| {
yep, totally! I made the change now.

2024-12-11 19:48 UTC, scottmillner submitted a review, later dismissed

2024-12-11 20:10 UTC, arminsabouri commented on bin/btc-server/src/server.rs
> +            return Ok(tonic::Response::new(rpc::Empty {}));
Sorry i should have picked up on this earlier. can we log an error here.
"Recieved a pegout request when there are no utxos or pending transactions"

2024-12-11 20:10 UTC, arminsabouri commented on bin/btc-server/src/util.rs
> +    let tracked_inputs = pegout_scheduler.lock().await.tracked_inputs();
I think you can just pull the tracked inputs from the db that way you dont need to lock

2024-12-13 16:42 UTC, rwlockbg commented on bin/btc-server/src/server.rs
> +            return Ok(tonic::Response::new(rpc::Empty {}));
done

2024-12-13 16:42 UTC, rwlockbg commented on bin/btc-server/src/util.rs
> +    let tracked_inputs = pegout_scheduler.lock().await.tracked_inputs();
done

2024-12-18 13:57 UTC, arminsabouri approved these changes

2024-12-18 16:04 UTC, scottmillner submitted a review, later dismissed

2024-12-18 16:14 UTC, arminsabouri requested changes
Looks like some unit tests in btc server are failing for legit reasons

2024-12-23 07:52 UTC, rwlockbg commented
> Looks like some unit tests in btc server are failing for legit reasons

Yes, the notify pegouts is failing for legit reasons. Maybe we should think about whether this code application is always correct. In the case of pegouts there are 0 tracked txs in the db hence its failing. Suggestions ?

2024-12-23 16:48 UTC, arminsabouri commented
> > Looks like some unit tests in btc server are failing for legit reasons
> 
> Yes, the notify pegouts is failing for legit reasons. Maybe we should think about whether this code application is always correct. In the case of pegouts there are 0 tracked txs in the db hence its failing. Suggestions ?

@rwlockbg to get around this in the test, I would just add some random utxos to the db before we notify the pegout. And I would also add a test condition to the `test_notify_pegouts` that ensures no pending pegouts are added when there are no utxos available.

2024-12-30 13:23 UTC, arminsabouri approved these changes

2024-12-30 13:23 UTC, merged