Set reth version to 1.0.0
botanix-labs/Macbeth pull request #518
Opened 2024-12-16 19:36 UTC by SatwikPrabhu

2024-12-16 19:56 UTC, arminsabouri requested changes
Do you mind also changing the hardcoded app version in abci.rs? Ideally we can just pull in one version and not hardcode it in multiple places?

https://github.com/botanix-labs/Macbeth/blob/4147460070a646bfbc6379ea1ab8bf47084803d0/crates/consensus/authority/src/comet_bft/abci.rs#L380

2024-12-16 19:56 UTC, arminsabouri commented on bin/reth/Cargo.toml
> +version = "1.0.0"
Will this version reflect in the rpc call? https://www.quicknode.com/docs/ethereum/web3_clientVersion

2024-12-16 21:01 UTC, SatwikPrabhu commented on bin/reth/Cargo.toml
> +version = "1.0.0"
It should be fixed now.

2024-12-16 21:39 UTC, arminsabouri approved these changes

2024-12-17 00:03 UTC, scottmillner approved these changes

2024-12-17 15:09 UTC, merged