use timestamp to determine if in turn
botanix-labs/Macbeth pull request #57
Opened 2024-01-02 20:17 UTC by scottmillner

2024-01-02 20:24 UTC, BatiGencho approved these changes

2024-01-03 14:24 UTC, arminsabouri requested changes
This is awesome 🔥 
I had comment that needs some change. 
Additionally we should also update the consensus validation to check the correct signer was in_turn.

I know we said this ticket https://github.com/botanix-labs/botanix/issues/289
But could make sense to include this as well.

Since this is super involved, happy to hop on call to white board some ideas out

2024-01-03 14:24 UTC, arminsabouri commented on crates/consensus/authority/src/epoch_manager.rs
> +        if timestamp <= prev_best_block_timestamp {
This is a good sanity check. This really means that our system clock is behind.
Maybe out of scope for this PR but there should be some async task that regularly syncs with an NTP server.

https://en.wikipedia.org/wiki/Network_Time_Protocol

2024-01-03 14:24 UTC, arminsabouri commented on crates/consensus/authority/src/epoch_manager.rs
> +            timestamp % (storage.authorities.len() as u64) == signer_index as u64;
Is the time denominated in seconds? If so, it seems like the allocation isn't completely round-robin. Consider this: with 5 federation members, at t = 1704291331, t % N = 1. Later, after processing blocks, let's say 3 seconds have passed (best case scenario, unlikely due to pre-commitment). At t = 1704291334, t % N = 4. Then, after another second, at t = 1704291336, t % N = 1 again.

If this pattern persists, certain signers might face block production starvation. An alternative approach could involve using minutes and adjusting the timer in the epoch_manager to trigger every minute, allowing for a check to determine if it's their turn.

2024-01-03 15:05 UTC, stevenroose commented on crates/consensus/authority/src/epoch_manager.rs
> +        if timestamp <= prev_best_block_timestamp {
It can also mean that the previous block maker put on a timestamp too far into the future. I don't know how Ethereum regularly checks that. In Bitcoin it's kinda lax because it's not so critical, but if you're going to use the timestamps more critically, then node validators should validate block timestamps as well.

It's a bit non-trivial though. FWIW in Liquid there is no time check on consensus, the time is only used for leader picking in the block making protocol which is totally independent from consensus.

2024-01-03 15:08 UTC, stevenroose commented on crates/consensus/authority/src/epoch_manager.rs
> +            timestamp % (storage.authorities.len() as u64) == signer_index as u64;
We discussed this in our call last week, you should first divide the time by N and then to mod N. Otherwise it's indeed never round robin. Imagine you have a 10-second round robin and also 10 block makers, the same one would always be picked.

2024-01-03 15:18 UTC, stevenroose commented on crates/consensus/authority/src/epoch_manager.rs
> +            timestamp % (storage.authorities.len() as u64) == signer_index as u64;
Using block height to do the round robin seems a lot more robust, tbh

2024-01-09 14:01 UTC, arminsabouri reviewed
Just some nit comments and questions. Over all this looks 🔥

2024-01-09 14:01 UTC, arminsabouri commented on bin/reth/src/poa/mod.rs
> +                    // TODO (scott) pass in ntp url as arg
No changes now but Once this comes an arg we should use a strong type like Address or Url

2024-01-09 14:01 UTC, arminsabouri commented on bin/reth/src/poa/mod.rs
> +                            info!("System clock is in sync with NTP server. System timestamp: {}, NTP timestamp: {}", system_timestamp, ntp_timestamp);
Should this log be wrapped in an else?

2024-01-09 14:01 UTC, arminsabouri commented on crates/consensus/authority/src/lib.rs
> +    pub fn validate_inturn(block_timestamp: u64, authorities_len: u64, signer_index: u64) -> Result<(), ConsensusError> {
Is the timestamp on the eth blocks denominated in minutes or seconds? Do we convert min -> sec somewhere

2024-01-09 14:01 UTC, arminsabouri commented on crates/consensus/authority/src/task.rs
> +                        drop(storage_inner);
Could move this drop up a line. ideally we release the lock as soon as we are done using it

2024-01-09 16:01 UTC, scottmillner commented on bin/reth/src/poa/mod.rs
> +                            info!("System clock is in sync with NTP server. System timestamp: {}, NTP timestamp: {}", system_timestamp, ntp_timestamp);
yep! nice catch, thanks!

done

2024-01-09 16:01 UTC, scottmillner commented on crates/consensus/authority/src/lib.rs
> +    pub fn validate_inturn(block_timestamp: u64, authorities_len: u64, signer_index: u64) -> Result<(), ConsensusError> {
ah i forget to convert:
the block_timestamp is in seconds and need to convert to minutes

done

2024-01-09 16:05 UTC, scottmillner commented on crates/consensus/authority/src/task.rs
> +                        drop(storage_inner);
done

2024-01-09 16:10 UTC, BatiGencho commented on crates/consensus/authority/src/task.rs
> +                                return
Should not we be doing a `continue` here in order to move up in the loop {} where we are blocked waiting on a channel to receive ?

2024-01-09 16:38 UTC, scottmillner commented on crates/consensus/authority/src/task.rs
> +                                return
yep! nice catch

done

2024-01-09 17:50 UTC, arminsabouri approved these changes
tACK [8dfa92f](https://github.com/botanix-labs/Macbeth/pull/57/commits/8dfa92f3dc5d08520a4d912b61a92bf5d304bc24)

Tested in_turn logic ✅ 
Validating incoming blocks is failing but we know the fix for that is on #63

2024-01-09 18:23 UTC, merged