replaced old mempool url with our private one
botanix-labs/Macbeth pull request #64
Opened 2024-01-09 10:42 UTC by BatiGencho

This PR replaces old mempool url with new one

2024-01-09 13:31 UTC, arminsabouri commented
Once the instance is ready, @birozuru do you mind dropping an approve on this PR.

2024-01-29 14:46 UTC, arminsabouri requested changes
The new domain is 
`esplora.botanixlabs.dev`

2024-01-29 21:21 UTC, BatiGencho commented
> The new domain is `esplora.botanixlabs.dev`

Fixed

2024-01-30 14:48 UTC, arminsabouri approved these changes

2024-01-30 14:48 UTC, merged