feature: added poa frost networking with dkg
botanix-labs/Macbeth pull request #98
Opened 2024-02-13 07:43 UTC by BatiGencho

First version of poa frost protocol integrated into reth with support for dkg generation.

There are two open points to resolve:

1. Who is triggering the dkg building process - the currently in turn fed member ? I believe there should be one fed member only while being in turn triggering the process which means we should mark that there is a running dkg job so we dont trigger a new one. This is the current implementation in the MR.
2. Do we need to clear the state machine after each successful dkg process (meaning rounds 1+2) ?
3. How should we currently make use of the generated public key (for the time being) - store it ?
4. Failure scenarios - what if ... (I have put TODOs in some places for discussions)

Current problem: the btc server takes authority index e.g. 1 and it converts this to frost_peer. The reth node uses the node_peer to convert that to frost_peer. Because of this discrepancy the frost message wont get transferred (I tested it with authority indexes and it was fine, but now we need to decide). We need to see which way we want to go!

2024-02-20 14:17 UTC, arminsabouri commented on bin/btc-server/proto/btc_server.proto
> +    rpc IsRound3TransitionPossible(Empty) returns (TransitionResponse) {}
Do we need these? The get Pk endpoint will throw if a transition is not possible. Same thing for getting the round2 packages

2024-02-20 15:08 UTC, BatiGencho commented on bin/btc-server/proto/btc_server.proto
> +    rpc IsRound3TransitionPossible(Empty) returns (TransitionResponse) {}
I thought of that too, but then I thought we need to parse the errors. I guess you are right, I will change it but we need to set those err strings to consts or something at least to prevent easily changing them.

2024-02-20 17:36 UTC, arminsabouri commented on bin/btc-server/proto/btc_server.proto
> +    rpc IsRound3TransitionPossible(Empty) returns (TransitionResponse) {}
Agreed the less endpoints the better. I would prefer just error'ing from the existing endpoing

2024-02-20 17:39 UTC, arminsabouri commented on crates/consensus/authority/src/block_builder.rs
> +                                        frost_handle.send_command(FrostCommand::NewDkgRoundStart);
Should there be some check here that we already have done DKG? or is that handled by the calling function?

2024-02-20 17:40 UTC, arminsabouri commented on crates/net/network/src/frost/dkg.rs
> +    public_key_package: Option<String>,
what is the string here? If its a agg public key it should be secp Public key

2024-02-20 17:40 UTC, arminsabouri commented on crates/net/network/src/frost/dkg.rs
> +    pub fn get_publick_key_package(&self) -> Option<String> {
Typo

```suggestion
    pub fn get_public_key_package(&self) -> Option<String> {
```

2024-02-20 17:43 UTC, arminsabouri commented on crates/net/network/src/frost/dkg.rs
> +                println!("round2_packages: {:?}", dkg2_package);
Nit: remove this

2024-02-20 17:45 UTC, arminsabouri commented on crates/net/network/src/frost/dkg.rs
> +    frost::Identifier::derive(peer_id.as_slice()).expect("can derive identifier")
Frost id's should be dervied from the the signers index into the federation list

2024-02-20 17:50 UTC, arminsabouri requested changes

2024-02-20 17:50 UTC, arminsabouri commented on crates/net/network/src/frost/messages.rs
> +    pub identifier: Vec<u8>,
What are your thoughts on including a version as part of the request/response payload?
For future backward compatible upgradability

2024-02-20 17:50 UTC, arminsabouri commented on crates/net/network/src/frost/messages.rs
> +                buf.put_u8(resource.identifier.len() as u8); // Assuming identifier is not too long
Id's should be u16

2024-02-20 17:50 UTC, arminsabouri commented on crates/net/network/src/frost/mod.rs
> +        // the connection direction - we connected to them, or they to us
Nit: triple slashes if this is documenting these fields or the linter will complain

2024-02-21 14:48 UTC, BatiGencho commented on crates/net/network/src/frost/messages.rs
> +                buf.put_u8(resource.identifier.len() as u8); // Assuming identifier is not too long
This is a different identifier - its the protocol message identifier, not the frost one. So far we have a few hence a u8 will suffice

2024-02-21 14:50 UTC, BatiGencho commented on crates/net/network/src/frost/dkg.rs
> +    public_key_package: Option<String>,
hex string was returned by the grpc api. I now changed to use secp pubkey, ty

2024-02-21 14:50 UTC, BatiGencho commented on crates/net/network/src/frost/dkg.rs
> +    pub fn get_publick_key_package(&self) -> Option<String> {
done, ty

2024-02-21 14:50 UTC, BatiGencho commented on crates/net/network/src/frost/dkg.rs
> +                println!("round2_packages: {:?}", dkg2_package);
ty, removed

2024-02-21 14:53 UTC, BatiGencho commented on crates/net/network/src/frost/mod.rs
> +        // the connection direction - we connected to them, or they to us
Yeah, thanks. I fixed these, there is more cleanup to be done in general.

2024-02-21 15:20 UTC, BatiGencho commented on crates/net/network/src/frost/messages.rs
> +    pub identifier: Vec<u8>,
added one

2024-02-21 21:03 UTC, arminsabouri commented
> Current problem: the btc server takes authority index e.g. 1 and it converts this to frost_peer. The reth node uses the node_peer to convert that to frost_peer. Because of this discrepancy the frost message wont get transferred (I tested it with authority indexes and it was fine, but now we need to decide). We need to see which way we want to go!

I vote for authority index. Must easier to communicate that to the federation members

2024-02-21 21:04 UTC, arminsabouri commented on crates/net/network/src/frost/messages.rs
> +                buf.put_u8(resource.identifier.len() as u8); // Assuming identifier is not too long
Got it!

2024-02-21 21:07 UTC, arminsabouri commented
>How should we currently make use of the generated public key (for the time being) - store it ?

We don't need to store this. Its only needed when we are retrieving gateway address via RPC. I would ensure that functionality still works. it  should be the `eth_gatewayAddress` RPC endpoint

2024-02-21 22:49 UTC, scottmillner commented on crates/consensus/common/src/utils.rs
>      ),
nit...spelling
`FailedToRetrieveEopchHeader` > `FailedToRetrieveEpochHeader`

2024-02-21 23:09 UTC, scottmillner commented on crates/net/network/src/frost/manager.rs
> +    command_rx: UnboundedReceiverStream<FrostCommand>,
nit, i think some of this comments need to be updated for frost

2024-02-21 23:12 UTC, scottmillner commented on crates/net/network/src/frost/manager.rs
> +
this isn't getting used anywhere?

2024-02-21 23:16 UTC, scottmillner commented on crates/net/network/src/frost/manager.rs
> +
nit, `PeersManager` > `FrostManager`

2024-02-21 23:16 UTC, scottmillner commented on crates/net/network/src/frost/manager.rs
> +
same, FrostManager

2024-02-21 23:19 UTC, scottmillner commented on crates/net/network/src/frost/mod.rs
> +pub enum NetworkFrostEvent {
nit, update comment for frost

2024-02-21 23:32 UTC, scottmillner commented
just wanted to say awesome work! this was a huge task to tackle!!

2024-02-22 09:29 UTC, BatiGencho commented on crates/net/network/src/frost/dkg.rs
> +    frost::Identifier::derive(peer_id.as_slice()).expect("can derive identifier")
Yes, I have changed that. Getting the authority over to that point was  quite difficult.

2024-02-22 09:31 UTC, BatiGencho commented on crates/consensus/common/src/utils.rs
>      ),
thanks, changed

2024-02-22 09:34 UTC, BatiGencho commented on crates/net/network/src/frost/manager.rs
> +
fixed, thanks.

2024-02-22 09:36 UTC, BatiGencho commented on crates/net/network/src/frost/manager.rs
> +
Not yet since we dont have that part yet (see armins comment above), but soon we will be fetching the pub key using the handle and calling this method.  Its only needed when we are retrieving gateway address via RPC

2024-02-22 09:36 UTC, BatiGencho commented on crates/net/network/src/frost/mod.rs
> +pub enum NetworkFrostEvent {
updated, thanks.

2024-02-22 11:31 UTC, BatiGencho commented on bin/btc-server/proto/btc_server.proto
> +    rpc IsRound3TransitionPossible(Empty) returns (TransitionResponse) {}
I forgot to commit that part, now it should be all there.

2024-02-22 11:32 UTC, BatiGencho commented on crates/net/network/src/frost/manager.rs
> +    command_rx: UnboundedReceiverStream<FrostCommand>,
done

2024-02-22 11:35 UTC, BatiGencho commented on crates/consensus/authority/src/block_builder.rs
> +                                        frost_handle.send_command(FrostCommand::NewDkgRoundStart);
This is the part where I am not qutie sure of, do we do it every new poa epoch (whoever the current in turn fed member is) or not ? Current implementation is: whoever is in turn will perform it once in the poa epoch. The calls are so designed that he would be quering the dkg core until its either successful or it fails.

2024-02-22 17:57 UTC, stevenroose reviewed
Definitely not knowledgable enough on FROST matters to review the FROST stuff, but left some general comments on Rusty-ness.

2024-02-22 17:57 UTC, stevenroose commented on bin/btc-server/src/main.rs
> +        assert_eq!(pk_1.publickey, pub_key.to_string());
hint: `PublicKey::from_str` exists, doing exactly this ;)

2024-02-22 17:57 UTC, stevenroose commented on crates/consensus/authority/src/dkg.rs
> +                tonic::Code::Internal if e.message().contains("Missing round1 dkg package") => {
Uff, doing string matching is a really bad idea...

tonic's Status has 2 things that might help here: "details", which is a freeform binary field, and "metadata" which is a key-value map similar to HTTP headers. I never used them before, but it seems like we can just use them. So we could encode a 32-bit integer error code into the details if we wanted to. Using traits on `Status`, it's possible to create a nice API for them. Can make an enum with codes.

But before doing all that work, I guess it makes sense to ask how valuable it is to have that information at the client side..

2024-02-22 17:57 UTC, stevenroose commented on crates/consensus/authority/src/dkg.rs
> +                self.next_state(DKGEvent::Round1, btc_server_client, frost_peers_connections).await;
Bit of a strange pattern to have a recursive function that sets a new state and then calls the next_state function again. Did you consider using a transformation method that takes a state and returns a new state, then you can have a loop that calls the method repeatedly until a certain success or error state is reached?

2024-02-22 17:57 UTC, stevenroose commented on crates/consensus/authority/src/frost_task.rs
> +        + 'static,
nit: I don't think you need all these generic constraints here.

2024-02-22 17:57 UTC, stevenroose commented on crates/consensus/authority/src/utils.rs
> +        bloom.contains_input(BloomInput::Raw(MINT_TOPIC.as_ref()))
Are these intentional formatting changes?

2024-02-22 17:57 UTC, stevenroose commented on crates/net/network/src/frost/manager.rs
> +                let _ = tx.send(self.frost_peers_connections.clone()).ok();
nit: There `.ok()`'s are not having any need. If you want to ignore the error, you can just do `let _ = ` with the result without the `.ok()`.

2024-02-22 17:57 UTC, stevenroose commented on crates/net/network/src/frost/manager.rs
> +    pub max_signers: u16,
Could these be documented? :pray:

2024-02-22 17:57 UTC, stevenroose commented on crates/node-core/src/node_config.rs
> +        }
nit: just a hint to avoid having a unnecessarily mutable variable down the line:
```rust
let frost_handle = frost.map(|frost| {
    let ret = front.handle();
    task_executor.spawn_critical("p2p frost", frost);
    ret
});
```

2024-02-23 08:08 UTC, BatiGencho commented on crates/consensus/authority/src/dkg.rs
> +                tonic::Code::Internal if e.message().contains("Missing round1 dkg package") => {
I agree with all you are saying, but the errors are loosely typed as strings. I guess for better handling we should introduce codes in the metadata or something. For now its irrelevant as I dont really distinguish between error A or B, just treat the error as a whole. I will put a todo to refactor this part in the next round, ty.

2024-02-23 08:09 UTC, BatiGencho commented on crates/consensus/authority/src/frost_task.rs
> +        + 'static,
agree, just copy-paste. Removed them

2024-02-23 08:09 UTC, BatiGencho commented on crates/consensus/authority/src/utils.rs
> +        bloom.contains_input(BloomInput::Raw(MINT_TOPIC.as_ref()))
yes, cargo fmt

2024-02-23 08:09 UTC, BatiGencho commented on crates/net/network/src/frost/manager.rs
> +                let _ = tx.send(self.frost_peers_connections.clone()).ok();
agreed, missed that when coding :)

2024-02-23 08:09 UTC, BatiGencho commented on crates/net/network/src/frost/manager.rs
> +    pub max_signers: u16,
I have added docs for everything now.

2024-02-23 08:09 UTC, BatiGencho commented on crates/node-core/src/node_config.rs
> +        }
good refactor, ty. I have adopted it.

2024-02-23 08:11 UTC, BatiGencho commented on crates/consensus/authority/src/dkg.rs
> +                self.next_state(DKGEvent::Round1, btc_server_client, frost_peers_connections).await;
I have reworked this part anyway as it wasnt really suiting our new critical FrostTask handling the dkg state machine logic. You are indeed right.

2024-02-23 08:11 UTC, BatiGencho commented on bin/btc-server/src/main.rs
> +        assert_eq!(pk_1.publickey, pub_key.to_string());
Yes, did not see this method:) Ty.

2024-02-27 16:07 UTC, arminsabouri commented on crates/consensus/authority/Cargo.toml
can you leave a reminder to change this once tr gets merged

2024-02-27 16:09 UTC, arminsabouri commented on crates/consensus/authority/src/dkg.rs
> +                tonic::Code::Internal if e.message().contains("Missing round1 dkg package") => {
We could do error code number that could help

2024-02-27 16:15 UTC, arminsabouri reviewed
Just had a few questions

2024-02-27 16:15 UTC, arminsabouri commented on crates/consensus/authority/src/dkg.rs
> +    pub(crate) async fn start(
How does DKG get initiated?

2024-02-27 16:15 UTC, arminsabouri commented on crates/consensus/authority/src/frost_task.rs
> +                // start the dkg process / restart ?
Maybe we can get_public_key and use that as an indication to start dkg or not?

2024-02-27 16:15 UTC, arminsabouri commented on crates/net/network/src/manager.rs
> +    from_frost_protol_events: UnboundedReceiverStream<FrostProtocolEvent>,
typo here 
```suggestion
    from_frost_protocol_events: UnboundedReceiverStream<FrostProtocolEvent>,
```

2024-02-27 21:09 UTC, scottmillner commented on crates/consensus/authority/src/dkg.rs
> +    pub(crate) async fn start(
looks like `poa_builder.launch()` spawns the `frost_task` which has a `loop` that checks if `dkg` is in the `running` state and if not, it starts `dkg`

wrote this comment more for me just to make sure i understand how it starts

2024-02-27 21:12 UTC, scottmillner approved these changes
@BatiGencho 
approving pr to signal that everything has been addressed that's within my knowledge

im not a frost expert so leave that focus to @0xBEEFCAF3 and certainly wouldn't merge until his approval

2024-02-29 10:39 UTC, BatiGencho commented on crates/consensus/authority/src/dkg.rs
> +    pub(crate) async fn start(
The DKG is started inside of the frost task which checks its has not started it yet and we are in turn. In other words once in turn the dkg is initiated until it completes.

2024-02-29 10:52 UTC, BatiGencho commented on crates/net/network/src/manager.rs
> +    from_frost_protol_events: UnboundedReceiverStream<FrostProtocolEvent>,
thanks, fixed.

2024-02-29 11:12 UTC, BatiGencho commented on crates/consensus/authority/src/frost_task.rs
> +                // start the dkg process / restart ?
I have added this condition now. Now we are onlyu starting the dkg process if:

- we are in turn 
- we get an error calling the get_public_key grpc
- we are in DKGState::Initial state

2024-02-29 11:13 UTC, BatiGencho commented on crates/consensus/authority/Cargo.toml
added

2024-02-29 13:56 UTC, arminsabouri commented on crates/consensus/authority/src/frost_task.rs
> +                // start the dkg process / restart ?
Perfect that should work fine. If DKG is already finished the btc_server signers will just reject any dkg requests

2024-02-29 14:08 UTC, arminsabouri reviewed
Just a few more questions

2024-02-29 14:08 UTC, arminsabouri commented on bin/reth/src/poa_builder.rs
> +        let frost_config = FrostConfig::new(authority_index, total_authorities, 2, 2);
Can we leave a todo to make max/min singer configuarable

2024-02-29 14:08 UTC, arminsabouri commented on crates/consensus/authority/src/dkg.rs
> +pub(crate) enum Error {
Just a heads up. Im refactoring the errors in BTC to have a bit more structure. No changes needed at the moment. but I thought I let you know

Root Error 
----DKGError
-------Round1Error
----------KeyPackageAlreadyExists
----SigningError
...
----CordinatorError
...

2024-02-29 14:08 UTC, arminsabouri commented on crates/consensus/authority/src/dkg.rs
> +        let round1_group_packages: HashMap<frost::Identifier, frost::keys::dkg::round2::Package> =
Maybe we re-name this to round2_group_packages

2024-02-29 14:08 UTC, arminsabouri commented on crates/consensus/authority/src/dkg.rs
> +        if round2_group_packages.len() >= (self.max_signers - 1) as usize {
One other way to check this condition is to call get_publickey

2024-02-29 14:08 UTC, arminsabouri commented on crates/consensus/authority/src/dkg.rs
> +        let round1_group_packages: HashMap<frost::Identifier, frost::keys::dkg::round2::Package> =
Or is the type here wrong? Should it be `frost::keys::dkg::round1::Package`

2024-02-29 14:08 UTC, arminsabouri commented on crates/consensus/authority/src/dkg.rs
> +        if round2_group_packages.len() >= (self.max_signers - 1) as usize {
And if you get a pk we can put the state machine in a success state

2024-03-04 20:06 UTC, BatiGencho commented on bin/reth/src/poa_builder.rs
> +        let frost_config = FrostConfig::new(authority_index, total_authorities, 2, 2);
added

2024-03-04 20:07 UTC, BatiGencho commented on crates/consensus/authority/src/dkg.rs
> +        let round1_group_packages: HashMap<frost::Identifier, frost::keys::dkg::round2::Package> =
already fixed that, thanks

2024-03-04 20:07 UTC, BatiGencho commented on crates/consensus/authority/src/dkg.rs
> +pub(crate) enum Error {
thanks, noted

2024-03-05 13:38 UTC, BatiGencho commented on crates/consensus/authority/src/dkg.rs
> +        if round2_group_packages.len() >= (self.max_signers - 1) as usize {
Should we rather tackle this in the next MR where we do the signing ? The current one is already massive, maybe I could do a new one and add it in ?

2024-03-05 20:40 UTC, arminsabouri commented
@BatiGencho I ran some manual tests. My set up was two federation nodes. I seems like we never get past round 1 on the node where the federation index is 1. 
The first fed memeber successfully stores the round 1 message. however the second one seems to acknowlege it but never stores it 

```
2024-03-05T20:34:30.202357Z  INFO >>>>>>>>>>> [FROST_TASK] Peer messaged received Response { response_type: DkgRound1, identifier: [52, 39, 160, 118, 176, 185, 222, 25, 54, 213, 2, 171, 233, 2, 75, 75, 154, 59, 199, 10, 16, 208, 24, 249, 238, 56, 171, 146, 37, 245, 114, 93], data: [0, 35, 15, 138, 179, 2, 2, 5, 55, 243, 226, 160, 169, 71, 151, 232, 171, 245, 3, 212, 46, 92, 76, 58, 212, 164, 250, 191, 212, 118, 6, 140, 72, 85, 72, 134, 193, 67, 63, 2, 247, 177, 226, 44, 140, 100, 234, 125, 225, 35, 121, 224, 134, 18, 191, 1, 128, 168, 163, 167, 60, 243, 171, 19, 219, 54, 243, 8, 132, 69, 238, 20, 65, 3, 168, 155, 251, 7, 80, 254, 78, 199, 72, 224, 188, 11, 243, 146, 64, 164, 53, 188, 185, 68, 127, 178, 179, 60, 211, 195, 215, 145, 12, 6, 193, 190, 121, 219, 94, 167, 31, 201, 229, 163, 65, 74, 98, 170, 162, 195, 28, 23, 55, 7, 125, 185, 190, 236, 208, 1, 231, 55, 145, 87, 232, 72, 113, 165] }
2024-03-05T20:34:30.202458Z  INFO >>>>>>>>>>> [PROCESS_ROUND1] identifiers Identifier("3427a076b0b9de1936d502abe9024b4b9a3bc70a10d018f9ee38ab9225f5725d") Identifier("3427a076b0b9de1936d502abe9024b4b9a3bc70a10d018f9ee38ab9225f5725d")
2024-03-05T20:34:30.202869Z  INFO >>>>>>>>>>> [FROST_TASK] Processed Round 1 package successfully
2024-03-05T20:34:30.453969Z  INFO Epoch manager inturn: true
2024-03-05T20:34:30.454004Z  INFO >>>>>>>>>>> [FROST_TASK] Peer messaged received Response { response_type: DkgRound2,
...
```


Im running the second btc server with these flags
`cargo run -- --network testnet --db "./db2" --identifier 2 --address 0.0.0.0:8081`

2024-03-05 23:40 UTC, arminsabouri commented
Problem was frost identifiers via the cli flags start indexing at 0
tACK [1718a35](https://github.com/botanix-labs/Macbeth/pull/98/commits/1718a3595cb1c707fe690bd41acaf39d9a3b3562)

2024-03-05 23:40 UTC, arminsabouri approved these changes

2024-03-06 06:50 UTC, merged